// Quellen: jede Angabe einzeln per Crossref (Autoren, Jahr, Titel, Zeitschrift, Band, Seiten) und PubMed (Abstract) geprüft
// (03.10.2026); die Aussagen im Text wurden mit dem Abstract abgeglichen:
// - Okubo, Schoene & Lord (2017), Br J Sports Med 51(7), 586–593; Abstract bestätigt: sieben randomisierte Studien (n = 660) mit
//   Schritt-Training (gewollte und ausgelöste Schritte) bei Älteren (ab 60), Rate Ratio der Stürze 0,48 (95 %-KI 0,36–0,65);
//   verbessert waren einfache und Wahl-Schrittreaktionszeit, Einbeinstand und Timed Up and Go, nicht die Kraft.
// - Lord & Fitzpatrick (2001), J Gerontol A 56(10), M627–M632; Abstract bestätigt: 477 Bewohner von Seniorenwohnanlagen (62–95 Jahre),
//   Wahl-Schrittaufgabe auf vier aufleuchtende Felder; Personen mit Stürzen in der Vorgeschichte brauchten im Mittel länger
//   (1322 ± 331 ms gegenüber 1168 ± 203 ms); die Zeit sagte Stürze unabhängig von anderen Maßen voraus.
// - Woollacott & Shumway-Cook (2002), Gait Posture 16(1), 1–14; Abstract bestätigt: Übersicht zur Rolle der Aufmerksamkeit bei
//   Haltung und Gehen; Doppelaufgaben zeigten, dass der Aufmerksamkeitsbedarf der Gleichgewichtskontrolle bei gesunden und
//   gleichgewichtsgestörten Älteren zur Instabilität beiträgt; der Bedarf hängt von der Schwierigkeit der Haltungsaufgabe und
//   der Art der zweiten Aufgabe ab.
// - Sherrington et al. (2019), Cochrane Database Syst Rev 2019(1), CD012424; Abstract bestätigt: 108 randomisierte Studien mit
//   23.407 Menschen ab 60 Jahren, die zu Hause leben; Bewegungsprogramme senken die Sturzrate (Rate Ratio 0,77), Gleichgewichts-
//   und Funktionsübungen allein 0,76 (hohe Sicherheit der Evidenz).
// - Pronk et al. (2020) und Guo et al. (2025): wie in den übrigen Labor-Übungen geprüft (Behav Res Methods 52, 1371–1382;
//   Front Physiol 16).
// - Muchnick (2008), Lehrbuch (ISBN 9780323029612), S. 6 und 28: Warnzeichen mit Abklärungsbedarf (Doppelbilder, Schwindel, Kopf-
//   und Augenschmerz); Seitenangaben wie in den übrigen Übungen der App.
// Nicht aufgenommen (nicht belegt oder Wirkversprechen): jede Aussage, dass diese Bildschirm-Übung das Gleichgewicht verbessert,
// Stürze verhindert oder sich auf Alltag, Sport oder Verkehr überträgt; dass die Bestätigung durch die Hilfsperson eine Messung der
// Bewegung ist; Normwerte für Zeiten. Nicht bestätigt werden konnte: nichts Aufgenommenes; für genau diese Übung gibt es keine Studie.
import type { ScienceEntry } from '../../content/science';

const src = (label: string, url: string) => ({ label, url });

export const science: ScienceEntry = {
  id: 'labor-orientierung',
  evidence: 'weak',
  texts: {
    de: {
      trains:
        'Nach einem sichtbaren Reiz gezielt eine von vier oder acht Richtungen einnehmen (zum Beispiel Neigen oder ein Schritt) und – wahlweise – zur Mitte zurückkehren. Eine Hilfsperson bestätigt auf dem Bildschirm, wann die Richtung erreicht ist; die App misst die Zeit bis zu diesem Tipp. Anzahl, Richtungen, Rückkehr zur Mitte, Pause, Zeitlimit und Punktgröße stellst du selbst ein.',
      daily:
        'Überall, wo man auf ein Zeichen hin den Körper in eine bestimmte Richtung bewegen muss, zum Beispiel beim Ausweichen oder in Ballsportarten. Ob die Übung dabei hilft, ist nicht belegt.',
      research:
        'Bei älteren Menschen wird untersucht, ob Training, bei dem man auf Reize hin gezielt Schritte in eine Richtung macht, Stürze vermindert: In einer Übersicht von sieben randomisierten Studien mit 660 Personen ab 60 Jahren gab es danach deutlich weniger Stürze (Rate Ratio 0,48), und einfache und Wahl-Schrittreaktionszeit, Einbeinstand und „Timed Up and Go“ waren verbessert, die Kraft nicht (Okubo et al., 2017). In einer Studie mit 477 Bewohnern von Seniorenwohnanlagen (62 bis 95 Jahre) wurde eine Wahl-Schrittaufgabe – auf eines von vier aufleuchtenden Feldern treten – als Marker für das Sturzrisiko untersucht: Wer schon gestürzt war, brauchte im Mittel länger (1.322 gegenüber 1.168 ms), und die Zeit sagte Stürze unabhängig von anderen Maßen voraus (Lord & Fitzpatrick, 2001). Das Halten des Gleichgewichts braucht Aufmerksamkeit: Eine Übersicht fand bei gesunden und bei gleichgewichtsgestörten älteren Menschen, dass dieser Bedarf zur Unsicherheit beiträgt; wie groß er ist, hängt von der Schwierigkeit der Haltungsaufgabe und von der Art der zweiten Aufgabe ab (Woollacott & Shumway-Cook, 2002). Eine Cochrane-Übersicht mit 108 Studien an 23.407 Menschen ab 60 Jahren, die zu Hause leben, fand, dass Bewegungsprogramme die Sturzrate senken, am deutlichsten Gleichgewichts- und Funktionsübungen (Rate Ratio 0,76; hohe Sicherheit der Evidenz) (Sherrington et al., 2019). Das waren betreute Programme mit echten Schritten und Bewegungen, keine Bildschirmübung; diese Übung misst keine Schrittzeit, kein Gleichgewicht und kein Sturzrisiko, und für gesunde Menschen ist ein Nutzen dieser Übung nicht belegt. Die App sieht deine Bewegung nicht: Sie zählt nur, was die Hilfsperson tippt, und die Zeit enthält deren Reaktion. In Studien zu Bildschirmübungen fallen Verbesserungen deutlich größer aus, wenn die Prüfung der geübten Aufgabe ähnelt – ein großer Teil ist Gewöhnung an Aufgabe und Gerät (Guo et al., 2025); Touchscreens messen die Reaktionszeit durchweg etwas zu lang, je nach Gerät unterschiedlich (Pronk et al., 2020; Tablets wurden dort nicht untersucht). Darum zählt nur der Vergleich mit dir selbst, mit derselben Hilfsperson, demselben Aufbau und denselben Einstellungen. Schwindel, Doppelbilder, Kopf- oder Augenschmerz gehören abgeklärt (Lehrbuchwissen: Muchnick, 2008). Für genau diese Übung gibt es keine Studie; ein Nutzen für Alltag, Sport oder Verkehr ist nicht belegt.',
      improved:
        'Die Richtungen sind gleichmäßig verteilt; das Ziel ist gefüllt und trägt einen Pfeil nach außen, die übrigen Richtungen sind nur Umrisse (die Richtung steht nicht nur in der Farbe), und ein Text oben sagt, was gerade gilt. Die Hilfsperson hat große Tasten „Erreicht“ und „Falsche Richtung“ (mindestens 56 Pixel, mit Text und Zeichen) und die Tastatur (Leertaste, X); ein zweiter Tipp direkt nach einer Bestätigung wird ignoriert, damit er nicht zugleich die Rückkehr zur Mitte bestätigt. Die Punktgröße wird in Zentimetern eingestellt (nach Kalibrierung des Bildschirms) und so begrenzt, dass alle Richtungen Platz haben. Die Rückmeldung ist ruhig: ✓ und ✗ als Zeichen, kein Flackern, kein Rotblitz. Ohne Zeitlimit wartet die Übung auf die Hilfsperson. Gezeigt werden erreichte Ziele, falsche Richtungen, Zeit bis zur Bestätigung (Mittel, Median, Streuung), Zeit zurück zur Mitte und die Zeit je Richtung – nur Zählwerte, keine Messung von Gleichgewicht oder Haltung, ohne Noten, Normwerte und Ranglisten. Verlauf, Bestwert und „Letztes Mal“ vergleichen nur Durchläufe mit gleichen Einstellungen.',
    },
    it: {
      trains:
        'Dopo uno stimolo visibile prendere in modo mirato una di quattro o otto direzioni (per esempio inclinarsi o un passo) e – a scelta – tornare al centro. Una persona di aiuto conferma sullo schermo quando la direzione è raggiunta; l’app misura il tempo fino a quel tocco. Numero, direzioni, ritorno al centro, pausa, limite di tempo e dimensione dei punti li imposti tu.',
      daily:
        'Ovunque si debba muovere il corpo in una certa direzione a un segnale, per esempio nello schivare o negli sport con la palla. Che l’esercizio aiuti non è dimostrato.',
      research:
        'Negli anziani si studia se un allenamento in cui si fanno passi mirati in una direzione in risposta a stimoli riduca le cadute: in una rassegna di sette studi randomizzati con 660 persone dai 60 anni in su dopo ci sono state nettamente meno cadute (rapporto di tassi 0,48) e il tempo di reazione al passo semplice e a scelta, l’appoggio su una gamba e il «Timed Up and Go» erano migliorati, la forza no (Okubo et al., 2017). In uno studio su 477 residenti in residenze per anziani (da 62 a 95 anni) si è studiato come indicatore del rischio di caduta un compito di passo a scelta – posare il piede su uno di quattro campi che si illuminano: chi era già caduto impiegava in media più tempo (1.322 contro 1.168 ms) e il tempo prediceva le cadute indipendentemente da altre misure (Lord & Fitzpatrick, 2001). Mantenere l’equilibrio richiede attenzione: una rassegna ha trovato, negli anziani sani e in quelli con disturbi dell’equilibrio, che questo fabbisogno contribuisce all’instabilità; quanto sia grande dipende dalla difficoltà del compito posturale e dal tipo di secondo compito (Woollacott & Shumway-Cook, 2002). Una rassegna Cochrane con 108 studi su 23.407 persone dai 60 anni in su che vivono a casa ha trovato che i programmi di movimento riducono il tasso di cadute, nel modo più netto gli esercizi di equilibrio e funzionali (rapporto di tassi 0,76; certezza delle prove alta) (Sherrington et al., 2019). Erano programmi seguiti da specialisti con passi e movimenti reali, non un esercizio sullo schermo; questo esercizio non misura i tempi di passo, né l’equilibrio, né il rischio di caduta e per le persone sane un’utilità di questo esercizio non è dimostrata. L’app non vede il tuo movimento: conta solo ciò che tocca la persona di aiuto e il tempo comprende la sua reazione. Negli studi sugli esercizi sullo schermo i miglioramenti risultano nettamente maggiori quando la verifica somiglia al compito allenato – gran parte è abitudine al compito e al dispositivo (Guo et al., 2025); i touchscreen misurano il tempo di reazione sistematicamente un po’ in eccesso, in modo diverso a seconda del dispositivo (Pronk et al., 2020; i tablet non erano stati studiati). Per questo conta solo il confronto con te stesso, con la stessa persona di aiuto, lo stesso allestimento e le stesse impostazioni. Vertigini, visione doppia, mal di testa o dolore agli occhi vanno chiariti (manuale: Muchnick, 2008). Per questo esercizio non esiste uno studio; un’utilità per vita quotidiana, sport o traffico non è dimostrata.',
      improved:
        'Le direzioni sono distribuite in modo uniforme; il bersaglio è pieno e porta una freccia verso l’esterno, le altre direzioni sono solo contorni (la direzione non è solo nel colore) e un testo in alto dice che cosa vale in quel momento. La persona di aiuto ha grandi tasti «Raggiunto» e «Direzione sbagliata» (almeno 56 pixel, con testo e simbolo) e la tastiera (barra spaziatrice, X); un secondo tocco subito dopo una conferma viene ignorato, perché non confermi anche il ritorno al centro. La dimensione dei punti si imposta in centimetri (dopo la calibrazione dello schermo) ed è limitata in modo che tutte le direzioni abbiano spazio. Il riscontro è sobrio: ✓ e ✗ come segni, nessuno sfarfallio, nessun lampo rosso. Senza limite di tempo l’esercizio aspetta la persona di aiuto. Vengono mostrati bersagli raggiunti, direzioni sbagliate, tempo fino alla conferma (media, mediana, variazione), tempo di ritorno al centro e tempo per direzione – solo valori di conteggio, nessuna misurazione di equilibrio o postura, senza voti, valori di riferimento e classifiche. Andamento, record e «ultima volta» confrontano solo giri con le stesse impostazioni.',
    },
  },
  sources: [
    src('Okubo, Schoene & Lord (2017). Step training improves reaction time, gait and balance and reduces falls in older people: a systematic review and meta-analysis. British Journal of Sports Medicine', 'https://doi.org/10.1136/bjsports-2015-095452'),
    src('Lord & Fitzpatrick (2001). Choice stepping reaction time: A composite measure of falls risk in older people. The Journals of Gerontology Series A: Biological Sciences and Medical Sciences', 'https://doi.org/10.1093/gerona/56.10.m627'),
    src('Woollacott & Shumway-Cook (2002). Attention and the control of posture and gait: a review of an emerging area of research. Gait & Posture', 'https://doi.org/10.1016/S0966-6362(01)00156-4'),
    src('Sherrington, Fairhall, Wallbank, Tiedemann, Michaleff, Howard et al. (2019). Exercise for preventing falls in older people living in the community. Cochrane Database of Systematic Reviews', 'https://doi.org/10.1002/14651858.CD012424.pub2'),
    src('Pronk, Wiers, Molenkamp & Murre (2020). Mental chronometry in the pocket? Timing accuracy of web applications on touchscreen and keyboard devices. Behavior Research Methods', 'https://doi.org/10.3758/s13428-019-01321-2'),
    src('Guo, Yuan, Yang & Qiu (2025). Does the "learning effect" caused by digital devices exaggerate sports visual training outcomes? A systematic review and meta-analysis. Frontiers in Physiology', 'https://doi.org/10.3389/fphys.2025.1664572'),
    src('Muchnick (2008). Clinical Medicine in Optometric Practice, 2nd ed. Mosby/Elsevier, S. 6 und 28 (Warnzeichen mit Abklärungsbedarf)', 'https://openlibrary.org/isbn/9780323029612'),
  ],
};
