// Quellen: jede Angabe einzeln per Crossref (Autoren, Jahr, Titel, Zeitschrift, Band, Seiten) geprüft (03.10.2026), soweit
// vorhanden auch per PubMed (Abstract); die Aussagen im Text wurden mit dem Abstract abgeglichen:
// - Julesz (1960): Bell System Technical Journal 39(5), 1125–1162; DOI 10.1002/j.1538-7305.1960.tb03954.x (Crossref:
//   Titel „Binocular Depth Perception of Computer-Generated Patterns“); kein Abstract in PubMed, nur Titel und Angaben
//   bestätigt – im Text wird deshalb nur wiedergegeben, dass Zufallspunktbilder für das Tiefensehen beschrieben wurden.
//   (Der DOI der Anfrage 10.1002/j.1538-7305.1960.tb00990.x existiert nicht; richtig ist …tb03954.x.)
// - Ding & Levi (2011): Proc Natl Acad Sci U S A 108(37), E733–E741 (Crossref und PubMed; Titel „Recovery of stereopsis
//   through perceptual learning in human adults with abnormal binocular vision“); Abstract bestätigt: fünf Erwachsene, die
//   zuvor stereoblind oder stereoanomal waren, Wahrnehmungslernen mit Tausenden Durchgängen mit stereoskopischen Gittern
//   (mit Hinweisen für ein Auge, die genau zur Disparität passten), danach deutliche Erholung des Stereosehens in
//   Prüfungen ohne solche Hinweise und in klinischen Messungen; die erholte Stereowahrnehmung hatte geringere Auflösung und
//   Genauigkeit. Nur als kleine Studie mit Erwachsenen mit gestörtem Binokularsehen wiedergegeben.
// - Read (2015): Eye 29(2), 214–224 (Crossref und PubMed; Titel „Stereo vision and strabismus“); Abstract bestätigt: Übersicht
//   zu Stereosehen, zur Störung bei Schielen, zu den üblichen Messverfahren mit Vor- und Nachteilen und zur klinischen
//   Bedeutung solcher Messungen.
// - Birch (2012): J Opt Soc Am A 29(3), 313–320; Abstract bestätigt: bei Menschen europäischer Herkunft etwa 8 % der Männer und
//   etwa 0,4 % der Frauen.
// - Muchnick (2008), Lehrbuch (ISBN 9780323029612), S. 6 und 28: Warnzeichen mit Abklärungsbedarf (Doppelbilder, Schwindel,
//   Kopf- und Augenschmerz); Seitenangaben wie in den übrigen Übungen der App.
// Nicht aufgenommen (nicht belegt oder nicht geprüft): jede Aussage zu einer Stereoschwelle, zu Normwerten (auch zu
// „Stereoacuity“-Grenzen klinischer Verfahren), zu einem Nutzen für Menschen ohne Befund, zum Ersatz einer Untersuchung;
// Quellenangaben aus Unterlagen ohne Prüfung. Als Erfahrungswissen der Praxis der funktionellen Optometrie ohne Quelle
// gekennzeichnet (nicht durch Studien belegt): weich auf das ganze Feld schauen, bei Unsicherheit raten statt starren, Pausen.
// Nicht bestätigt werden konnte: nichts Aufgenommenes; für genau diese Übung gibt es keine Studie.
import type { ScienceEntry } from '../../content/science';

const src = (label: string, url: string) => ({ label, url });

export const science: ScienceEntry = {
  id: 'labor-stereo',
  evidence: 'weak',
  texts: {
    de: {
      trains:
        'Mit einer Rot-Grün-Brille in einem Feld aus Zufallspunkten ein Quadrat finden, das vor oder hinter der Fläche zu schweben scheint, und angeben, wo es liegt (oben, unten, links, rechts). Jedes Auge sieht sein eigenes Punktbild; der Unterschied zwischen beiden (Disparität, in Winkelsekunden) wird mit der Sehentfernung aus der Kalibrierung berechnet. Du stellst Disparität, Steuerung (automatisch, fest, Trainer), Feld- und Quadratgröße, Punkte, Rauschen und Farben selbst ein.',
      daily:
        'Räumliches Sehen mit beiden Augen spielt beim Greifen, Treppensteigen und im Straßenverkehr eine Rolle. Ob diese Übung dabei hilft, ist nicht belegt.',
      research:
        'Zufallspunktbilder, wie sie hier genutzt werden, wurden schon 1960 für die Untersuchung des Tiefensehens beschrieben (Julesz, 1960). Eine Übersicht erklärt, wie Stereosehen bei Schielen gestört sein kann, welche Messverfahren es gibt, welche Vor- und Nachteile sie haben und wie wichtig solche Messungen klinisch sind (Read, 2015). In einer kleinen Studie mit fünf Erwachsenen, die zuvor stereoblind oder stereoanomal waren, erholte sich das Stereosehen nach Tausenden Durchgängen mit stereoskopischen Gittern deutlich, auch in Prüfungen ohne Hinweise für ein Auge und in klinischen Messungen; das erholte Stereosehen hatte aber geringere Auflösung und Genauigkeit (Ding & Levi, 2011). Das war eine kleine Studie mit Erwachsenen mit gestörtem Binokularsehen, kein Bildschirmspiel mit Rot-Grün-Brille wie dieses. Für Menschen ohne Befund ist für diese Übung kein Nutzen belegt, und sie ist keine Behandlung, keine Messung einer Schwelle und kein Ersatz für eine Untersuchung. Ehrlich zu den Grenzen: Anaglyphen lassen Farbsäume sichtbar; ein Bildschirm gibt nur grobe Orientierung und verschiebt nur in ganzen Pixeln (die feinste Stufe steht im Ergebnis); ein 2D-Bildschirm liefert den Unterschied zwischen den Augenbildern, aber keine natürliche Tiefe, denn die Schärfe bleibt am Bildschirm. In der Praxis der funktionellen Optometrie wird weich auf das ganze Feld geschaut statt auf einzelne Punkte, bei Unsicherheit geraten statt gestarrt und Pausen gemacht – als Erfahrungswissen beschrieben, nicht durch Studien belegt. Eine Rot-Grün-Farbsehschwäche haben bei Menschen europäischer Herkunft etwa 8 % der Männer und etwa 0,4 % der Frauen (Birch, 2012); für sie passt die Übung nicht. Schwindel, Kopfschmerz, Augenschmerz oder Doppelbilder gehören abgeklärt (Lehrbuchwissen: Muchnick, 2008); bei Schielen oder Doppelbildern wird deshalb nur nach Absprache mit der behandelnden Fachperson geübt. Für genau diese Übung gibt es keine Studie; ein Nutzen für Alltag, Sport oder Verkehr ist nicht belegt.',
      improved:
        'Auf Schwarz stehen reines Rot (255, 0, 0) und reines Grün (0, 255, 0) – wahlweise Cyan oder Blau (0, 160, 255; Rot-Cyan-Brillen funktionieren mit dem Farbpaar Rot–Blau) –, die Helligkeit jeder Farbe stellst du getrennt ein (30 bis 100 %, Schritte von 10 %). Im Intro gibt es ein Prüfbild Schritt für Schritt (Brille aufsetzen, je ein Auge zuhalten, Glas wählen, Helligkeit einstellen, ein Hinweis zu Geisterbildern); es bewertet nichts. Ein schmaler neutraler Rahmen um das Feld sieht jedes Auge und hält die beiden Bilder zusammen. Das Quadrat liegt je Durchgang zufällig oben, unten, links oder rechts und schwebt zufällig vor oder hinter der Fläche; die Punkte außerhalb können zufällig verschobenes Rauschen haben. Die Disparität wird in Winkelsekunden geführt und mit der Sehentfernung aus der Kalibrierung in Zentimeter und Pixel umgerechnet; automatisch wird sie nach zwei richtigen Antworten kleiner und nach jedem Fehler größer, bei „fest“ bleibt sie der Startwert, bei „Trainer“ bestimmt sie allein der Regler. In der Trainer- und Entwickler-Ansicht gibt es eine schmale Leiste am Rand außerhalb des Feldes, mit der die Disparität während der Übung verändert werden kann (höchstens 400 ″ je Tastendruck, die Anzeige gleitet weich, jede Änderung wird mit Zeitpunkt festgehalten und im Ergebnis ausgewiesen). Im Ergebnis stehen der Anteil richtiger Antworten (Zufall: etwa 25 %), die letzte Disparität, die Antwortzeit und die Disparität eines einzelnen Pixels als feinste Stufe des Bildschirms – als Übungswerte, ohne Noten, Normwerte und Ranglisten, und ohne Aussage über Sehschärfe oder Stereosehen. Bei Schwindel, Kopfschmerz oder Doppelbildern sofort aufhören; bei Schielen oder Doppelbildern nur nach Absprache mit der behandelnden Fachperson. Weil das Ergebnis von den Einstellungen abhängt, vergleichen Verlauf, Bestwert und „Letztes Mal“ nur Durchläufe mit gleichen Einstellungen (auch gleicher Steuerung und gleichem Startwert); die Änderungen am Regler teilen den Verlauf nicht.',
    },
    it: {
      trains:
        'Con gli occhiali rosso-verdi trovare, in un campo di punti casuali, un quadrato che sembra fluttuare davanti o dietro la superficie, e indicare dove si trova (sopra, sotto, sinistra, destra). Ogni occhio vede la propria immagine di punti; la differenza tra le due (disparità, in secondi d’arco) viene calcolata con la distanza visiva della calibrazione. Disparità, guida (automatica, fissa, trainer), dimensione di campo e quadrato, punti, rumore e colori li imposti tu.',
      daily:
        'La visione spaziale con due occhi ha un ruolo nell’afferrare, nel salire le scale e nel traffico. Che l’esercizio aiuti in questo non è dimostrato.',
      research:
        'Le immagini di punti casuali, come quelle usate qui, furono descritte già nel 1960 per lo studio della visione della profondità (Julesz, 1960). Una rassegna spiega come la visione stereoscopica possa essere alterata nello strabismo, quali metodi di misura esistono, quali vantaggi e svantaggi hanno e quanto siano importanti clinicamente tali misure (Read, 2015). In un piccolo studio con cinque adulti che prima erano stereocechi o stereoanomali, la visione stereoscopica si è ripresa nettamente dopo migliaia di passaggi con reticoli stereoscopici, anche in prove senza indizi per un solo occhio e in misurazioni cliniche; la visione stereoscopica ritrovata aveva però risoluzione e precisione minori (Ding & Levi, 2011). Era un piccolo studio con adulti con visione binoculare alterata, non un gioco su schermo con occhiali rosso-verdi come questo. Per le persone senza disturbi non è dimostrata alcuna utilità di questo esercizio, che non è un trattamento, non è una misurazione di una soglia e non sostituisce una visita. Con onestà sui limiti: gli anaglifi lasciano aloni colorati; uno schermo dà solo un orientamento grossolano e sposta solo in pixel interi (il passo più fine è nel risultato); uno schermo 2D fornisce la differenza tra le immagini degli occhi, ma non una profondità naturale, perché la messa a fuoco resta sullo schermo. Nella pratica dell’optometria funzionale si guarda con morbidezza tutto il campo invece di singoli punti, si indovina nel dubbio invece di fissare e si fanno pause – descritto come sapere empirico, non dimostrato da studi. Un’alterazione della visione dei colori rosso-verde ce l’hanno, nelle persone di origine europea, circa l’8 % degli uomini e circa lo 0,4 % delle donne (Birch, 2012); per loro l’esercizio non è adatto. Vertigini, mal di testa, dolore agli occhi o visione doppia vanno chiariti (manuale: Muchnick, 2008); in caso di strabismo o visione doppia ci si esercita perciò solo dopo accordo con lo specialista che segue la persona. Per questo esercizio non esiste uno studio; un’utilità per vita quotidiana, sport o traffico non è dimostrata.',
      improved:
        'Su nero ci sono rosso puro (255, 0, 0) e verde puro (0, 255, 0) – a scelta ciano o blu (0, 160, 255; gli occhiali rosso-ciano funzionano con la coppia rosso–blu) –, la luminosità di ogni colore la imposti separatamente (dal 30 al 100 %, a passi del 10 %). Nell’introduzione c’è un’immagine di controllo passo dopo passo (mettere gli occhiali, coprire un occhio alla volta, scegliere la lente, regolare la luminosità, un’indicazione sulle immagini fantasma); non valuta nulla. Una stretta cornice neutra attorno al campo è vista da ogni occhio e tiene insieme le due immagini. In ogni passaggio il quadrato si trova a caso sopra, sotto, a sinistra o a destra e fluttua a caso davanti o dietro la superficie; i punti all’esterno possono avere un rumore spostato a caso. La disparità è guidata in secondi d’arco e convertita in centimetri e pixel con la distanza visiva della calibrazione; automaticamente diminuisce dopo due risposte giuste e aumenta dopo ogni errore, con “fissa” resta il valore iniziale, con “Trainer” la decide solo il regolatore. Nella vista del trainer e dello sviluppatore c’è una stretta barra al margine, fuori dal campo, con cui la disparità può essere cambiata durante l’esercizio (al massimo 400 ″ per tasto, la visualizzazione scorre dolcemente, ogni modifica viene registrata con l’orario e riportata nel risultato). Nel risultato ci sono la quota di risposte giuste (caso: circa 25 %), l’ultima disparità, il tempo di risposta e la disparità di un singolo pixel come passo più fine dello schermo – come valori di esercizio, senza voti, valori di riferimento e classifiche, e senza indicazioni su acuità visiva o visione stereoscopica. In caso di vertigini, mal di testa o visione doppia smetti subito; in caso di strabismo o visione doppia solo dopo accordo con lo specialista che ti segue. Poiché il risultato dipende dalle impostazioni, andamento, record e “ultima volta” confrontano solo giri con le stesse impostazioni (anche stessa guida e stesso valore iniziale); le modifiche al regolatore non dividono l’andamento.',
    },
  },
  sources: [
    src('Julesz (1960). Binocular depth perception of computer-generated patterns. Bell System Technical Journal', 'https://doi.org/10.1002/j.1538-7305.1960.tb03954.x'),
    src('Ding & Levi (2011). Recovery of stereopsis through perceptual learning in human adults with abnormal binocular vision. Proceedings of the National Academy of Sciences', 'https://doi.org/10.1073/pnas.1105183108'),
    src('Read (2015). Stereo vision and strabismus. Eye', 'https://doi.org/10.1038/eye.2014.279'),
    src('Birch (2012). Worldwide prevalence of red-green color deficiency. Journal of the Optical Society of America A', 'https://doi.org/10.1364/JOSAA.29.000313'),
    src('Muchnick (2008). Clinical Medicine in Optometric Practice, 2nd ed. Mosby/Elsevier, S. 6 und 28 (Warnzeichen mit Abklärungsbedarf)', 'https://openlibrary.org/isbn/9780323029612'),
  ],
};
