import type { ExerciseTexts } from '../../core/types';
import { ANA_FEEDBACK, ANA_PARAM_TEXTS, COMMON } from '../_shared/pruefung-texte';

// Funktionsübung der Marke „Labor“ nach dem Prinzip des klassischen Worth-Vier-Punkte-Verfahrens (Rot-Grün-Brille), Texte in
// du-Form und einfacher Sprache. Regeln: kein Ersatz für die Untersuchung, keine Befunddeutung (die Zahl der Lichter wird
// nicht gedeutet), keine Richtwerte, kein Wirkversprechen; gezeigt werden Übungswerte (wie oft welche Zahl gemeldet wurde).

export const de: ExerciseTexts = {
  title: 'Worth-Vier-Punkte',
  tagline: 'Vier Lichter in Rautenform: zähle, wie viele du siehst.',
  steps: ['Rot-Grün-Brille auf, Raum eher dunkel.', 'Schaue ruhig auf die Mitte der vier Lichter.', 'Zähle die Lichter und tippe die Zahl.'],
  why:
    'Das Worth-Vier-Punkte-Verfahren nutzen Fachleute seit mehr als hundert Jahren. Vier Lichter stehen in einer Raute: oben ein rotes, links und rechts je ein grünes, unten ein weißes. Mit einer Rot-Grün-Brille sieht jedes Auge durch sein Glas nur Teile davon; das weiße Licht sehen beide Augen. Hier machst du eine digitale Näherung als Funktionsübung nach diesem Prinzip: Du zählst, wie viele Lichter du siehst, und tippst die Zahl. Die App zählt nur deine Antworten und deutet sie nicht; was eine Zahl bedeutet, gehört in die Hand von Fachleuten. Sie ersetzt keine Untersuchung. Ob die Übung für Alltag oder Sehen etwas bringt, ist nicht belegt.',
  goodFor: ['Beidäugiges Sehen kennenlernen', 'Ruhiges Hinschauen', 'Lichter zählen'],
  captions: {
    look: 'Vier Lichter in einer Raute.',
    count: 'Zähle, wie viele Lichter du siehst.',
    answer: 'Tippe die Zahl.',
    done: 'Danach siehst du deine Zählung.',
  },
  metrics: {
    answered: 'Beantwortete Darbietungen',
    lights4: 'Mit vier Lichtern gemeldet',
    lights2: 'Mit zwei Lichtern gemeldet',
    lights3: 'Mit drei Lichtern gemeldet',
    lights5: 'Mit fünf Lichtern gemeldet',
  },
  metricHints: {
    answered: 'Wie viele Darbietungen du beantwortet hast. Das ist nur die Zahl deiner Eingaben, keine Leistung und kein Befund.',
    lights4: 'Wie oft du vier Lichter gemeldet hast. Die App deutet das nicht.',
    lights2: 'Wie oft du zwei Lichter gemeldet hast. Die App deutet das nicht.',
    lights3: 'Wie oft du drei Lichter gemeldet hast. Die App deutet das nicht.',
    lights5: 'Wie oft du fünf Lichter gemeldet hast. Die App deutet das nicht.',
  },
  tips: {
    calm: 'Zähle nur die Lichter, nicht die Farben. Antworte nach dem ersten Eindruck, ohne zu raten, und lasse die Augen offen.',
    unclear: 'Bei „Unklar“: Prüfe zuerst das Prüfbild (Brille, Glas, Helligkeit), dunkle den Raum ab und schaue ruhig auf die Mitte der Raute.',
  },
  feedback: {
    ...ANA_FEEDBACK.de,
    progress: '{n} / {total}',
    ask: 'Wie viele Lichter siehst du?',
    unclear: 'Unklar',
    valuesTitle: 'Übungswerte (keine Deutung)',
    rowLights: '{k} Lichter gemeldet',
    rowUnclear: 'Unklar oder wechselnd',
    countValue: '{k} von {n}',
    rowSame: 'Häufigste Antwort: Anteil an allen Antworten',
    sameValue: '{v} %',
    layoutTitle: 'Anordnung',
    layoutRow: 'Zuordnung der Lichter',
    layoutValue: 'oben {a} · links und rechts {b} · unten weiß',
    layoutText: 'Das rote Licht gehört zum {eyeA} (Glas {lensA}), die beiden {adjB}n Lichter zum {eyeB} (Glas {lensB}); das weiße Licht sehen beide Augen.',
    eyeLeft: 'linken Auge',
    eyeRight: 'rechten Auge',
    sizeRow: 'Durchmesser der Lichter',
    sizeValue: '{cm} cm',
    sizeValue2: 'klein {s} cm, groß {b} cm',
    limited: 'auf diesem Bildschirm begrenzt',
    notCalibrated: 'nicht kalibriert: nur eine Schätzung',
    valuesNote: `Gezählt wird nur, was du eingegeben hast. Was eine Zahl bedeutet, deutet die App nicht; das gehört in die Hand von Augenärztin, Augenarzt, Orthoptistin oder Optometrist. ${COMMON.de.values}`,
    fewNote: COMMON.de.fewValues,
  },
  progression: [
    'Leichter: größere Lichter (2 bis 4 cm).',
    'Umfangreicher: kleine Lichter (0,5 bis 1 cm) und mehr Darbietungen (8 bis 12), damit sich zeigt, wie einheitlich deine Antworten sind.',
    'Mit „Größe wechseln“ sind die Lichter abwechselnd klein und groß (2,5-fach).',
    'Zum Vergleichen mit dir selbst: immer dieselbe Lichtgröße, derselbe Abstand und dasselbe Raumlicht.',
  ],
  cautions: [
    COMMON.de.principle,
    'Die Zählung hängt von der Brille (richtig herum, richtiges Glas), von Raumlicht und Bildschirm ab. Dunkle den Raum eher ab, halte den Kopf gerade und ruhig und halte die Augen nicht zu.',
    'Antworten wie „zwei“, „drei“ oder „fünf“ können auch an Brille, Helligkeit oder Spiegelungen liegen. Prüfe erst das Prüfbild; die App sagt dazu nichts über deine Augen.',
    COMMON.de.warn,
    COMMON.de.epilepsy,
    COMMON.de.colorBlind,
    COMMON.de.calm,
  ],
  params: {
    repeats: { label: 'Anzahl der Darbietungen', hint: 'Wie oft die vier Lichter gezeigt werden (2 bis 12). Mehr Darbietungen zeigen, wie einheitlich deine Antworten sind.', short: '{v} Darbietung|{v} Darbietungen' },
    dotCm: {
      label: 'Durchmesser der Lichter',
      hint: 'Größe eines Lichts in Zentimetern (nach Kalibrierung). Auf kleinen Bildschirmen wird sie begrenzt, damit die Raute auf die Bühne passt; im Ergebnis steht die gezeichnete Größe.',
      short: '{v} cm',
    },
    varySize: {
      label: 'Größe wechseln',
      hint: 'Bei „Ja“ sind die Lichter abwechselnd klein und 2,5-fach groß. Bei „Nein“ bleibt die Größe gleich.',
      options: { yes: 'Ja', no: 'Nein' },
    },
    ...ANA_PARAM_TEXTS.de,
  },
};

export const it: ExerciseTexts = {
  title: 'Quattro punti di Worth',
  tagline: 'Quattro luci a forma di rombo: conta quante ne vedi.',
  steps: ['Occhiali rosso-verdi, stanza piuttosto buia.', 'Guarda con calma il centro delle quattro luci.', 'Conta le luci e tocca il numero.'],
  why:
    'Il metodo dei quattro punti di Worth è usato dagli specialisti da più di cent’anni. Quattro luci sono disposte a rombo: in alto una rossa, a sinistra e a destra una verde ciascuna, in basso una bianca. Con gli occhiali rosso-verdi ogni occhio vede attraverso la sua lente solo una parte delle luci; la luce bianca la vedono entrambi gli occhi. Qui fai un’approssimazione digitale come esercizio funzionale secondo questo principio: conti quante luci vedi e tocchi il numero. L’app conta solo le tue risposte e non le interpreta; che cosa significhi un numero spetta agli specialisti. Non sostituisce una visita. Che l’esercizio serva alla vita quotidiana o alla vista non è dimostrato.',
  goodFor: ['Conoscere la visione con due occhi', 'Guardare con calma', 'Contare luci'],
  captions: {
    look: 'Quattro luci a rombo.',
    count: 'Conta quante luci vedi.',
    answer: 'Tocca il numero.',
    done: 'Poi vedi il tuo conteggio.',
  },
  metrics: {
    answered: 'Presentazioni con risposta',
    lights4: 'Segnalato con quattro luci',
    lights2: 'Segnalato con due luci',
    lights3: 'Segnalato con tre luci',
    lights5: 'Segnalato con cinque luci',
  },
  metricHints: {
    answered: 'A quante presentazioni hai risposto. È solo il numero delle tue immissioni, non una prestazione e non un referto.',
    lights4: 'Quante volte hai segnalato quattro luci. L’app non lo interpreta.',
    lights2: 'Quante volte hai segnalato due luci. L’app non lo interpreta.',
    lights3: 'Quante volte hai segnalato tre luci. L’app non lo interpreta.',
    lights5: 'Quante volte hai segnalato cinque luci. L’app non lo interpreta.',
  },
  tips: {
    calm: 'Conta solo le luci, non i colori. Rispondi secondo la prima impressione, senza tirare a indovinare, e tieni gli occhi aperti.',
    unclear: 'In caso di «Poco chiaro»: controlla prima l’immagine di controllo (occhiali, lente, luminosità), oscura la stanza e guarda con calma il centro del rombo.',
  },
  feedback: {
    ...ANA_FEEDBACK.it,
    progress: '{n} / {total}',
    ask: 'Quante luci vedi?',
    unclear: 'Poco chiaro',
    valuesTitle: 'Valori dell’esercizio (nessuna interpretazione)',
    rowLights: '{k} luci segnalate',
    rowUnclear: 'Poco chiaro o variabile',
    countValue: '{k} su {n}',
    rowSame: 'Risposta più frequente: quota di tutte le risposte',
    sameValue: '{v} %',
    layoutTitle: 'Disposizione',
    layoutRow: 'Assegnazione delle luci',
    layoutValue: 'in alto {a} · a sinistra e a destra {b} · in basso bianca',
    layoutText: 'La luce rossa appartiene all’{eyeA} (lente {lensA}), le due luci {adjB} all’{eyeB} (lente {lensB}); la luce bianca la vedono entrambi gli occhi.',
    eyeLeft: 'occhio sinistro',
    eyeRight: 'occhio destro',
    sizeRow: 'Diametro delle luci',
    sizeValue: '{cm} cm',
    sizeValue2: 'piccola {s} cm, grande {b} cm',
    limited: 'limitato su questo schermo',
    notCalibrated: 'non calibrato: solo una stima',
    valuesNote: `Si conta solo ciò che hai inserito. Che cosa significhi un numero, l’app non lo interpreta; spetta all’oculista, all’ortottista o all’optometrista. ${COMMON.it.values}`,
    fewNote: COMMON.it.fewValues,
  },
  progression: [
    'Più facile: luci più grandi (da 2 a 4 cm).',
    'Più completo: luci piccole (da 0,5 a 1 cm) e più presentazioni (da 8 a 12), così si vede quanto sono uniformi le tue risposte.',
    'Con «Cambia dimensione» le luci sono alternativamente piccole e grandi (2,5 volte).',
    'Per confrontarti con te stesso: sempre la stessa dimensione delle luci, la stessa distanza e la stessa luce nella stanza.',
  ],
  cautions: [
    COMMON.it.principle,
    'Il conteggio dipende dagli occhiali (messi nel verso giusto, lente giusta), dalla luce della stanza e dallo schermo. Oscura piuttosto la stanza, tieni la testa dritta e ferma e non chiudere gli occhi.',
    'Risposte come «due», «tre» o «cinque» possono dipendere anche da occhiali, luminosità o riflessi. Controlla prima l’immagine di controllo; l’app non dice nulla sui tuoi occhi.',
    COMMON.it.warn,
    COMMON.it.epilepsy,
    COMMON.it.colorBlind,
    COMMON.it.calm,
  ],
  params: {
    repeats: { label: 'Numero di presentazioni', hint: 'Quante volte vengono mostrate le quattro luci (da 2 a 12). Più presentazioni mostrano quanto sono uniformi le tue risposte.', short: '{v} presentazione|{v} presentazioni' },
    dotCm: {
      label: 'Diametro delle luci',
      hint: 'Dimensione di una luce in centimetri (dopo la calibrazione). Sugli schermi piccoli viene limitata perché il rombo stia nell’area; nel risultato è indicata la dimensione disegnata.',
      short: '{v} cm',
    },
    varySize: {
      label: 'Cambia dimensione',
      hint: 'Con «Sì» le luci sono alternativamente piccole e grandi 2,5 volte. Con «No» la dimensione resta uguale.',
      options: { yes: 'Sì', no: 'No' },
    },
    ...ANA_PARAM_TEXTS.it,
  },
};
