// Quellen: jede Angabe einzeln per Crossref (Metadaten) und über PubMed (Abstract) geprüft (02.10.2026); die Aussagen im
// Text halten sich an das, was im Abstract steht. Alle Quellen sind gesucht und geprüft:
// - Engel et al. (2000): Augen- und Handführung reagieren auf einen Richtungswechsel ähnlich (Abstract).
// - Danion & Flanagan (2018): beim Führen mit der Hand weniger Aufholsprünge der Augen, genaueres Mitgleiten (Abstract;
//   Laborgerät mit Handgriff und Zeiger, nicht Finger auf dem Bildschirm – so im Text vermerkt).
// - Miall et al. (1993): Handführen als „ruckweises“ Nachregeln; bei höherem Zieltempo wuchs der Startfehler (Abstract).
// - de’Sperati & Viviani (1997): Genauigkeit der Augen auf Ellipsen hängt von Tempo und Krümmung ab (Abstract).
// - Eibenberger et al. (2012): kleine Studie (10 Personen), Training des Augenfolgens – nur so wiedergegeben.
// - Pronk et al. (2020), Guo et al. (2025): Grenzen der Messung am Touchgerät bzw. Gewöhnungseffekt (Abstract).
// - Muchnick (2008, S. 32–35, Tabelle 3-2): klinische Prüfung der Augenfolgebewegung mit dem „H-Muster“ (Lehrbuch, nur als
//   Abgrenzung genannt: Die Übung ist keine Prüfung).
// Nicht aufgenommen: Aussagen ohne Quelle („bei höheren Geschwindigkeiten oder unvorhersehbaren
// Bewegungen schalten die Augen auf Aufholsprünge um“ – im Abstract nicht bestätigt; „trainiert das gleitende Verfolgen“ –
// Wirkversprechen, für diese Übung nicht untersucht). Für genau diese Übung (Finger auf bewegtem Ziel) wurde keine Studie
// gefunden. Das Verfolgen einer kreisenden Marke (rotierende Scheibe) mit Steigerung bis zum Zeigen auf die Marke ist als
// Praxisangabe der klassischen Sehtherapie beschrieben, nicht belegt (nur so genannt). Nicht bestätigt werden konnte:
// Volltext der Studien (nur Abstracts gelesen).
import type { ScienceEntry } from '../../content/science';

const src = (label: string, url: string) => ({ label, url });

export const science: ScienceEntry = {
  id: 'labor-ziel-verfolgen',
  evidence: 'weak',
  texts: {
    de: {
      trains: 'Den Finger auf einem gleichmäßig wandernden Ziel halten – die Augen folgen dem Ziel, die Hand führt mit. Bahn, Tempo, Größe und Spielraum stellst du selbst ein.',
      daily: 'Überall, wo Auge und Hand gemeinsam ein bewegtes Ziel verfolgen, etwa beim Führen eines Zeigers oder Stifts über den Bildschirm. Ob die Übung dabei hilft, ist nicht belegt.',
      research:
        'Wer ein bewegtes Ziel mit den Augen verfolgt, gleitet mit und macht dabei kleine Aufholsprünge. Bei einem abrupten Richtungswechsel des Ziels reagierten Augen und Hand in einer Laborstudie ähnlich; die Autoren schließen auf gemeinsame Mechanismen (Engel et al., 2000). Wer mit der Hand folgt, benutzt die Augen etwas anders als beim reinen Zuschauen: weniger Aufholsprünge, genaueres Mitgleiten (Danion & Flanagan, 2018; dort mit Handgriff statt Finger auf dem Bildschirm). Die Hand führt dabei nicht ganz gleichmäßig, sondern in kleinen Korrekturschritten, und bei höherem Zieltempo wuchs der Abstand, bei dem eine Korrektur einsetzt (Miall et al., 1993). Wie genau die Augen einer Ellipse folgen, hängt von Tempo und Krümmung ab (de’Sperati & Viviani, 1997); hier läuft das Ziel mit gleichbleibendem Tempo – das ist wie Bahnformen, Tempo, Größe und Spielraum eine eigene Festlegung der App. In einer kleinen Studie mit zehn Personen verbesserte kurzes Üben des Augenfolgens am Bildschirm das Folgen in einer anschließenden Prüfung (Eibenberger et al., 2012); ob das Führen mit dem Finger ähnlich profitiert, ist nicht untersucht. Verbesserungen in der geübten Aufgabe sind zum Teil Gewöhnung an Aufgabe und Gerät: In Studien zu solchen Übungen fielen sie deutlich größer aus, wenn die Prüfung der geübten Aufgabe ähnelte (Guo et al., 2025). Touchscreens messen Reaktionszeiten durchweg etwas zu lang, je nach Gerät unterschiedlich (Pronk et al., 2020; Tablets wurden dort nicht untersucht); hier wird zwar keine Reaktionszeit gemessen, aber es zählt trotzdem nur der Vergleich mit dir selbst auf demselben Gerät und mit denselben Einstellungen. Klinisch wird die Folgebewegung der Augen geprüft, indem die Augen einem nahen Ziel folgen, das auf einer H-förmigen Bahn geführt wird (Muchnick, 2008, S. 32–35); diese Übung ist keine solche Prüfung. Aus der klassischen Sehtherapie ist das Verfolgen einer kreisenden Marke (rotierende Scheibe) bekannt, bei ruhigem Kopf und mit schrittweise gesteigertem Tempo, später mit Zeigen auf die Marke; das ist eine Praxisangabe, eine Wirkung ist nicht belegt. Wohin du schaust, wird nicht gemessen (kein Eye-Tracking). Für genau diese Übung gibt es keine Studie.',
      improved:
        'Das Ziel läuft mit gleichbleibendem Tempo (in Zentimetern pro Sekunde, nicht pro Bild) auf einer geschlossenen Bahn; vor Beginn steht es einen Moment still, damit du den Finger auflegen kannst, und erst dann zählt die Zeit. Als „auf dem Ziel“ gilt, wenn der Finger aufliegt und höchstens um Zielradius plus Spielraum von der Mitte entfernt ist; gemessen wird also nur dein Finger, und es zählt nur ein Finger. Größe und Tempo werden in Zentimetern angegeben (nach Kalibrierung des Bildschirms), das Ziel wird nie größer als die Bühne, die Trefferfläche hat eine Mindestgröße für Touch-Eingaben, und beim Drehen des Tablets bleibt das Ziel an derselben Stelle der Runde. Ein Ring um das Ziel zeigt den Spielraum (gestrichelt, bei „auf dem Ziel“ durchgezogen und dicker, dazu ein ✓ – nicht nur ein Farbwechsel), und eine gestrichelte Linie führt zum Ziel, wenn der Finger daneben liegt. Jeder Durchlauf merkt sich seine Einstellungen, und Verlauf, Bestwert und „Letztes Mal“ vergleichen nur Läufe mit gleichen Einstellungen. Gezeigt werden der Anteil auf dem Ziel (bezogen auf die ganze Zeit), die längste Verfolgung, verlorene Verbindungen, die Zeit mit Fingerkontakt und die mittlere Abweichung – ohne Noten, Normwerte und Ranglisten.',
    },
    it: {
      trains: 'Tenere il dito su un bersaglio che si muove in modo regolare – gli occhi seguono il bersaglio, la mano guida insieme. Percorso, velocità, dimensione e margine li scegli tu.',
      daily: 'Ovunque occhio e mano seguano insieme un bersaglio in movimento, per esempio guidando un puntatore o una penna sullo schermo. Che l’esercizio aiuti non è dimostrato.',
      research:
        'Chi segue con gli occhi un bersaglio in movimento scorre con esso e fa piccoli scatti di recupero. In un cambio improvviso di direzione del bersaglio, occhi e mano hanno reagito in modo simile in uno studio di laboratorio; gli autori deducono meccanismi comuni (Engel et al., 2000). Chi segue con la mano usa gli occhi in modo un po’ diverso rispetto al solo guardare: meno scatti di recupero, inseguimento più preciso (Danion & Flanagan, 2018; lì con un’impugnatura invece del dito sullo schermo). La mano non guida in modo del tutto uniforme, ma a piccoli passi di correzione, e a velocità maggiori del bersaglio cresceva la distanza alla quale parte una correzione (Miall et al., 1993). Quanto gli occhi seguono con precisione un’ellisse dipende da velocità e curvatura (de’Sperati & Viviani, 1997); qui il bersaglio si muove a velocità costante – come forma del percorso, velocità, dimensione e margine è una scelta propria dell’app. In un piccolo studio con dieci persone, un breve allenamento dell’inseguimento con gli occhi sullo schermo ha migliorato l’inseguimento in una verifica successiva (Eibenberger et al., 2012); se la guida con il dito ne tragga lo stesso vantaggio non è stato studiato. I miglioramenti nel compito allenato sono in parte abitudine al compito e al dispositivo: negli studi su esercizi di questo tipo erano nettamente maggiori quando la verifica somigliava al compito allenato (Guo et al., 2025). I touchscreen misurano i tempi di reazione sistematicamente un po’ in eccesso, in modo diverso a seconda del dispositivo (Pronk et al., 2020; i tablet non erano stati studiati); qui non viene misurato un tempo di reazione, ma conta comunque solo il confronto con te stesso sullo stesso dispositivo e con le stesse impostazioni. Clinicamente il movimento di inseguimento degli occhi si esamina facendo seguire agli occhi un bersaglio vicino condotto lungo un percorso a forma di H (Muchnick, 2008, pag. 32–35); questo esercizio non è un esame di questo tipo. Dalla terapia visiva classica è noto l’inseguimento di un segno in movimento circolare (disco rotante), a testa ferma e con velocità aumentata gradualmente, poi con puntamento sul segno; è un’indicazione pratica, un effetto non è dimostrato. Dove guardi non viene misurato (nessun eye-tracking). Per questo esercizio non esiste uno studio.',
      improved:
        'Il bersaglio si muove a velocità costante (in centimetri al secondo, non per fotogramma) su un percorso chiuso; prima dell’inizio resta fermo un momento, così puoi appoggiare il dito, e solo allora il tempo conta. “Sul bersaglio” vale quando il dito è appoggiato e dista dal centro al massimo il raggio del bersaglio più il margine; si misura quindi solo il dito, e conta un solo dito. Dimensione e velocità sono espresse in centimetri (dopo la calibrazione dello schermo), il bersaglio non diventa mai più grande dell’area di gioco, l’area di tocco ha una dimensione minima per l’input touch e, girando il tablet, il bersaglio resta nello stesso punto del giro. Un anello intorno al bersaglio mostra il margine (tratteggiato, “sul bersaglio” continuo e più spesso, con un ✓ – non solo un cambio di colore), e una linea tratteggiata porta al bersaglio quando il dito è fuori. Ogni giro ricorda le sue impostazioni, e andamento, record e “ultima volta” confrontano solo giri con le stesse impostazioni. Vengono mostrati la quota sul bersaglio (rispetto a tutto il tempo), l’inseguimento più lungo, i contatti persi, il tempo con il dito sullo schermo e lo scostamento medio – senza voti, valori di riferimento e classifiche.',
    },
  },
  sources: [
    src('Engel, Anderson & Soechting (2000). Similarity in the response of smooth pursuit and manual tracking to a change in the direction of target motion. Journal of Neurophysiology', 'https://doi.org/10.1152/jn.2000.84.3.1149'),
    src('Danion & Flanagan (2018). Different gaze strategies during eye versus hand tracking of a moving target. Scientific Reports', 'https://doi.org/10.1038/s41598-018-28434-6'),
    src('Miall, Weir & Stein (1993). Intermittency in human manual tracking tasks. Journal of Motor Behavior', 'https://doi.org/10.1080/00222895.1993.9941639'),
    src('de’Sperati & Viviani (1997). The relationship between curvature and velocity in two-dimensional smooth pursuit eye movements. The Journal of Neuroscience', 'https://doi.org/10.1523/JNEUROSCI.17-10-03932.1997'),
    src('Eibenberger, Ring & Haslwanter (2012). Sustained effects for training of smooth pursuit plasticity. Experimental Brain Research', 'https://doi.org/10.1007/s00221-012-3009-8'),
    src('Pronk, Wiers, Molenkamp & Murre (2020). Mental chronometry in the pocket? Timing accuracy of web applications on touchscreen and keyboard devices. Behavior Research Methods', 'https://doi.org/10.3758/s13428-019-01321-2'),
    src('Guo, Yuan, Yang & Qiu (2025). Does the "learning effect" caused by digital devices exaggerate sports visual training outcomes? A systematic review and meta-analysis. Frontiers in Physiology', 'https://doi.org/10.3389/fphys.2025.1664572'),
    src('Muchnick (2008). Clinical Medicine in Optometric Practice, 2nd ed., S. 32–35 (Prüfung der Augenfolgebewegung, „H-Muster“). Mosby/Elsevier', 'https://openlibrary.org/isbn/9780323029612'),
  ],
};
