import type { ExerciseTexts } from '../../core/types';

// Formulierungsregeln (Optiker-Seite): nur beschreiben, was man in der Übung tut; keine Wirk-,
// Heil- oder Sicherheitsversprechen, kein „Test“, keine Normwerte, Vergleich nur mit sich selbst.
// Gemessen wird die Reaktionszeit Ziel → Touch (Hinsehen, Erkennen, Entscheiden, Fingerbewegung), nicht der Blick.
// In feedback stehen auch die Texte der Ergebnistabellen; {n}, {m}, {s}, {a}, {b} sind Platzhalter.

export const de: ExerciseTexts = {
  title: '4-Ziele-Wechsel',
  tagline: 'Vier Ziele, vier Ecken: tippe immer das markierte Ziel.',
  steps: [
    'Stelle das Tablet ruhig auf und sitze mittig davor.',
    'Tippe das Ziel an, das einen Ring bekommt.',
    'Halte den Kopf möglichst ruhig – nur die Augen wandern.',
  ],
  why:
    'Im Alltag wechselt dein Blick ständig zwischen weit entfernten Stellen. Hier übst du genau das zwischen vier Ecken. Gemessen wird die Zeit vom Erscheinen des Rings bis zu deinem Tipp – nicht, wohin du schaust. Ob sich das auf Sport, Verkehr oder Sehen überträgt, ist nicht belegt.',
  goodFor: ['Blickwechsel', 'Schnell erkennen', 'Überblick'],
  captions: {
    start: 'Vier Zeichen in den Ecken',
    ring: 'Der Ring zeigt das Ziel: tippen!',
    next: 'Der Ring springt in eine andere Ecke',
    only: 'Nur das markierte Ziel zählt',
    wrong: 'Falsch getippt? Das Ziel bleibt aktiv',
    again: 'Und weiter – immer ein neues Ziel',
  },
  metrics: {
    level: 'Stufe',
    reaction: 'Reaktionszeit Ziel → Touch',
    hits: 'Treffer',
    wrong: 'Falsches Ziel',
    omitted: 'Ausgelassen',
    distractor: 'Ablenker berührt',
  },
  tips: {
    wrong: 'Du tippst öfter ein falsches Ziel. Schau erst, wo der Ring ist, dann tippe – ein Augenblick mehr hilft oft beim Treffen.',
    distractor: 'Du hast öfter ein Ablenker-Zeichen berührt. Nur das Ziel mit dem Ring zählt – die anderen Zeichen darfst du ignorieren.',
    slow: 'Bei einigen Zielen hat es länger gedauert. Such den Ring zuerst mit den Augen und tippe dann gleich.',
    tired: 'In der zweiten Hälfte ging es etwas langsamer. Mach zwischen den Durchgängen eine kurze Pause und lass die Augen ruhen.',
    direction: 'Manche Richtungen fallen dir leichter als andere. Schau dir die Tabelle an und übe ruhig öfter die langsamere Richtung.',
    great: 'Stark! Der Wechsel zwischen den Ecken klappt gleichmäßig. Bleib locker – dann geht es auch auf der nächsten Stufe.',
  },
  feedback: {
    level: 'Stufe',
    block: 'Block {n}/{m}',
    restTitle: 'Kurze Pause',
    restText: 'Block {n} von {m} geschafft. Lass die Augen kurz ruhen.',
    restIn: 'Weiter in {s} s',
    next: 'Weiter',
    overviewTitle: 'Erste und letzte Hälfte',
    first: 'Erste Hälfte',
    last: 'Letzte Hälfte',
    halfText: '{a} von {b} Zielen richtig',
    distractorRow: 'Ablenker berührt',
    dirTitle: 'Richtungen (vom vorigen zum neuen Ziel)',
    right: 'nach rechts',
    left: 'nach links',
    down: 'nach unten',
    up: 'nach oben',
    downRight: 'nach rechts unten',
    upLeft: 'nach links oben',
    upRight: 'nach rechts oben',
    downLeft: 'nach links unten',
    fastest: 'schnellste Richtung',
    slowest: 'langsamste Richtung',
    fewHits: 'noch zu wenige Treffer',
    count: '{n}×',
    note:
      'Die Zeit enthält Hinsehen, Erkennen, Entscheiden und die Fingerbewegung – nicht den Blick allein, der wird nicht gemessen. Touchscreens messen je nach Gerät 30–130 ms zu lang. Vergleiche nur mit deinen eigenen Werten auf diesem Gerät. Waagerechte, senkrechte und schräge Wege sind unterschiedlich lang (je nach Hoch- oder Querformat).',
    noData: '–',
  },
};

export const it: ExerciseTexts = {
  title: 'Cambio tra 4 bersagli',
  tagline: 'Quattro bersagli, quattro angoli: tocca sempre quello evidenziato.',
  steps: [
    'Appoggia il tablet fermo e siediti al centro, davanti.',
    'Tocca il bersaglio che riceve un anello.',
    'Tieni la testa ferma – muovi solo gli occhi.',
  ],
  why:
    'Nella vita di tutti i giorni lo sguardo passa di continuo tra punti lontani. Qui lo eserciti tra quattro angoli. Viene misurato il tempo da quando compare l’anello fino al tuo tocco – non dove guardi. Non è dimostrato che questo si trasferisca allo sport, al traffico o alla vista.',
  goodFor: ['Cambio di sguardo', 'Riconoscere in fretta', 'Visione d’insieme'],
  captions: {
    start: 'Quattro simboli negli angoli',
    ring: 'L’anello indica il bersaglio: tocca!',
    next: 'L’anello salta in un altro angolo',
    only: 'Conta solo il bersaglio evidenziato',
    wrong: 'Toccato quello sbagliato? Resta attivo',
    again: 'E avanti – sempre un nuovo bersaglio',
  },
  metrics: {
    level: 'Livello',
    reaction: 'Tempo di reazione bersaglio → tocco',
    hits: 'Colpiti',
    wrong: 'Bersaglio sbagliato',
    omitted: 'Saltati',
    distractor: 'Distrattori toccati',
  },
  tips: {
    wrong: 'Tocchi spesso il bersaglio sbagliato. Guarda prima dov’è l’anello, poi tocca – un attimo in più spesso aiuta a colpire.',
    distractor: 'Hai toccato spesso un simbolo di disturbo. Conta solo il bersaglio con l’anello – gli altri simboli puoi ignorarli.',
    slow: 'Con alcuni bersagli ci è voluto più tempo. Cerca prima l’anello con gli occhi e poi tocca subito.',
    tired: 'Nella seconda metà è andata un po’ più lenta. Fai una breve pausa tra una serie e l’altra e lascia riposare gli occhi.',
    direction: 'Alcune direzioni ti riescono meglio di altre. Guarda la tabella ed esercita più spesso la direzione più lenta.',
    great: 'Ottimo! Il passaggio tra gli angoli riesce in modo regolare. Resta rilassato – così funziona anche al livello successivo.',
  },
  feedback: {
    level: 'Livello',
    block: 'Serie {n}/{m}',
    restTitle: 'Breve pausa',
    restText: 'Serie {n} di {m} completata. Lascia riposare un attimo gli occhi.',
    restIn: 'Si riparte tra {s} s',
    next: 'Avanti',
    overviewTitle: 'Prima e seconda metà',
    first: 'Prima metà',
    last: 'Seconda metà',
    halfText: '{a} di {b} bersagli giusti',
    distractorRow: 'Distrattori toccati',
    dirTitle: 'Direzioni (dal bersaglio precedente a quello nuovo)',
    right: 'verso destra',
    left: 'verso sinistra',
    down: 'verso il basso',
    up: 'verso l’alto',
    downRight: 'in basso a destra',
    upLeft: 'in alto a sinistra',
    upRight: 'in alto a destra',
    downLeft: 'in basso a sinistra',
    fastest: 'direzione più veloce',
    slowest: 'direzione più lenta',
    fewHits: 'ancora troppo pochi colpi',
    count: '{n}×',
    note:
      'Il tempo comprende guardare, riconoscere, decidere e il movimento del dito – non lo sguardo da solo, che non viene misurato. I touchscreen misurano, a seconda del dispositivo, 30–130 ms in più. Confrontati solo con i tuoi valori su questo dispositivo. I percorsi orizzontali, verticali e diagonali hanno lunghezze diverse (a seconda che il dispositivo sia in verticale o in orizzontale).',
    noData: '–',
  },
};
