import type { ExerciseTexts } from '../../core/types';

// Formulierungsregeln (Optiker-Seite): nur beschreiben, was man in der Übung tut; keine Wirk-,
// Heil- oder Sicherheitsversprechen, kein „Test“, keine Normwerte, Vergleich nur mit sich selbst.
// Gemessen wird nur die Zeit von Tipp zu Tipp (Suchen, Erkennen, Fingerbewegung), nicht der Blick.
// In feedback stehen auch die Texte der Ergebnistabellen und des Regelhinweises; {n}, {m}, {s}, {a}, {b}, {d}, {e}
// sind Platzhalter.

export const de: ExerciseTexts = {
  title: '4-Ziele-Wechsel',
  tagline: 'Vier Tafeln in den Ecken: tippe reihum von jeder Tafel einen Buchstaben.',
  steps: [
    'Tablet ruhig aufstellen, mittig sitzen, Kopf ruhig halten.',
    'Tippe von jeder Tafel reihum einen Buchstaben an.',
    'Getippte Buchstaben werden blass: so siehst du, wo du bist.',
  ],
  why:
    'Im Alltag springt dein Blick zwischen weit entfernten Stellen hin und her. Hier liest du reihum von vier Tafeln in den Ecken – ähnlich wie bei Hart-Charts, den Buchstabentafeln der funktionellen Optometrie. Gemessen wird nur die Zeit von Tipp zu Tipp, nicht wohin du schaust. Ob sich das auf Sport, Verkehr oder Sehen überträgt, ist nicht belegt.',
  goodFor: ['Blickwechsel', 'Reihenfolge halten', 'Überblick'],
  captions: {
    start: 'Vier Tafeln in den Ecken',
    ring: 'Der Ring zeigt den nächsten Buchstaben',
    first: 'Reihum: ein Buchstabe von jeder Tafel',
    pale: 'Getippte Buchstaben werden blass',
    again: 'Dann der nächste Buchstabe von vorn',
    wrong: 'Falsch getippt? Such den richtigen',
  },
  metrics: {
    level: 'Stufe',
    time: 'Zeit je Buchstabe (Tipp → Tipp)',
    hits: 'Buchstaben gelesen',
    wrong: 'Fehler',
    beat: 'Im Takt',
  },
  tips: {
    wrong: 'Du tippst öfter einen falschen Buchstaben. Such zuerst den nächsten Buchstaben der Tafel – das ist der erste, der noch nicht blass ist – und tippe dann. Ein Augenblick mehr hilft oft beim Treffen.',
    tired: 'In der zweiten Hälfte ging es etwas langsamer. Mach zwischen den Runden eine kurze Pause und lass die Augen ruhen.',
    jump: 'Der Wechsel zur anderen Tafel dauert länger als der zweite Buchstabe in derselben Tafel – der Weg ist ja weiter. Vergleiche den Unterschied nur mit deinen früheren Sitzungen.',
    direction: 'Die Richtungen unterscheiden sich schon durch die Weglänge. Mit wenigen Durchgängen sagt die Tabelle nur grob etwas; vergleiche über mehrere Sitzungen.',
    great: 'Stark! Das Lesen reihum klappt gleichmäßig. Bleib locker – dann geht es auch auf der nächsten Stufe.',
  },
  feedback: {
    level: 'Stufe',
    round: 'Runde {n}/{m}',
    restTitle: 'Kurze Pause',
    restText: 'Runde {n} von {m} geschafft. Lass die Augen kurz ruhen.',
    restIn: 'Weiter in {s} s',
    next: 'Weiter',
    orderReading: 'Reihum in Leserichtung  ↖ ↗ ↙ ↘',
    orderCw: 'Reihum im Uhrzeigersinn  ↖ ↗ ↘ ↙',
    orderZigzag: 'Reihum über Kreuz  ↖ ↘ ↗ ↙',
    orderFree: 'Reihenfolge der Tafeln frei – jede einmal',
    scanCols: 'In jeder Tafel spaltenweise lesen',
    roundsTitle: 'Runden',
    roundText: '{n} Buchstaben · Dauer {d} · {e} Fehler',
    timeTitle: 'Zeit je Buchstabe',
    median: 'Median',
    wholeSession: 'ganze Sitzung',
    first: 'Erste Hälfte',
    last: 'Letzte Hälfte',
    halfText: '{a} von {b} Buchstaben ohne Fehler',
    dirTitle: 'Zeit von Tipp zu Tipp nach Richtung (Tafelwechsel)',
    right: 'nach rechts',
    left: 'nach links',
    down: 'nach unten',
    up: 'nach oben',
    downRight: 'nach rechts unten',
    upLeft: 'nach links oben',
    upRight: 'nach rechts oben',
    downLeft: 'nach links unten',
    fastest: 'schnellste Richtung',
    slowest: 'langsamste Richtung',
    fewHits: 'noch zu wenige Wechsel',
    count: '{n}×',
    note:
      'Gemessen wird die Zeit von Tipp zu Tipp: Suchen, Erkennen und die Fingerbewegung – nicht der Blick allein, der wird nicht gemessen. Der erste Tipp jeder Runde und Buchstaben mit einem Fehler davor zählen nicht als Zeit. Die Zeit hängt zum großen Teil vom Fingerweg ab: Waagerechte, senkrechte und schräge Wege sind unterschiedlich lang (je nach Hoch- oder Querformat). Touchscreens messen etwas zu lang (bei Smartphones rund 50–70 ms, bei Tablets nicht untersucht). Vergleiche nur mit deinen eigenen Werten auf diesem Gerät.',
    jumpTitle: 'Tafelwechsel gegen Zeit in derselben Tafel',
    jumpSwitch: 'Beim Tafelwechsel',
    jumpWithin: 'Innerhalb derselben Tafel',
    jumpCost: 'Unterschied',
    jumpNote: 'Der Unterschied zeigt, wie viel länger der Wechsel zu einer anderen Tafel dauert. Er ist nur ein Vergleich mit dir selbst und mit früher.',
    beatTitle: 'Takt (Option)',
    beatTempo: 'Takt',
    beatShare: 'Im Takt',
    beatShareText: '{a} von {b} Tipps innerhalb von ±0,3 s um einen Taktschlag',
    beatNote:
      'Der Takt ist nur ein Ton und nie ein Fehlergrund; Stufe und Zeiten werden wie ohne Takt berechnet. Wer auf den Takt wartet, wird langsamer – vergleiche Zeiten mit Takt nur mit Sitzungen mit gleichem Takt. Je schneller der Takt, desto öfter liegt ein Tipp auch zufällig im Fenster; der Wert zählt nur im Vergleich mit dir selbst.',
    noData: '–',
  },
  options: {
    metronome: {
      title: 'Takt (Metronom)',
      hint: 'Ein leiser, gleichmäßiger Ton: ein Schlag für einen Buchstaben (so unsere Annahme). Mittel sind 60 Schläge pro Minute. Nur zu hören – bei ausgeschaltetem Ton gibt es keinen Takt. Takt ist optional; ob er etwas bringt, ist nicht belegt.',
      choices: { slow: 'Langsam\n1,4 s', medium: 'Mittel\n1,0 s', fast: 'Schnell\n0,8 s' },
    },
  },
};

export const it: ExerciseTexts = {
  title: 'Cambio tra 4 bersagli',
  tagline: 'Quattro tavole negli angoli: tocca a turno una lettera da ogni tavola.',
  steps: [
    'Tablet fermo, siediti al centro, tieni la testa ferma.',
    'Tocca a turno una lettera da ogni tavola.',
    'Le lettere toccate diventano chiare: vedi dove sei.',
  ],
  why:
    'Nella vita di tutti i giorni lo sguardo salta tra punti lontani. Qui leggi a turno da quattro tavole negli angoli – in modo simile alle Hart-Chart, le tavole di lettere dell’optometria funzionale. Viene misurato solo il tempo da tocco a tocco, non dove guardi. Non è dimostrato che questo si trasferisca allo sport, al traffico o alla vista.',
  goodFor: ['Cambio di sguardo', 'Tenere l’ordine', 'Visione d’insieme'],
  captions: {
    start: 'Quattro tavole negli angoli',
    ring: 'L’anello indica la lettera successiva',
    first: 'A turno: una lettera per tavola',
    pale: 'Le lettere toccate diventano chiare',
    again: 'Poi la lettera successiva, da capo',
    wrong: 'Sbagliato? Cerca quella giusta',
  },
  metrics: {
    level: 'Livello',
    time: 'Tempo per lettera (tocco → tocco)',
    hits: 'Lettere lette',
    wrong: 'Errori',
    beat: 'A tempo',
  },
  tips: {
    wrong: 'Tocchi spesso una lettera sbagliata. Cerca prima la lettera successiva della tavola – la prima che non è ancora chiara – e poi tocca. Un attimo in più spesso aiuta a colpire.',
    tired: 'Nella seconda metà è andata un po’ più lenta. Fai una breve pausa tra un giro e l’altro e lascia riposare gli occhi.',
    jump: 'Il passaggio all’altra tavola richiede più tempo della seconda lettera nella stessa tavola – il percorso è più lungo. Confronta la differenza solo con le tue sedute precedenti.',
    direction: 'Le direzioni si distinguono già per la lunghezza del percorso. Con pochi giri la tabella dice solo qualcosa di approssimativo; confronta su più sedute.',
    great: 'Ottimo! La lettura a turno riesce in modo regolare. Resta rilassato – così funziona anche al livello successivo.',
  },
  feedback: {
    level: 'Livello',
    round: 'Giro {n}/{m}',
    restTitle: 'Breve pausa',
    restText: 'Giro {n} di {m} completato. Lascia riposare un attimo gli occhi.',
    restIn: 'Si riparte tra {s} s',
    next: 'Avanti',
    orderReading: 'A turno nel senso di lettura  ↖ ↗ ↙ ↘',
    orderCw: 'A turno in senso orario  ↖ ↗ ↘ ↙',
    orderZigzag: 'A turno in diagonale  ↖ ↘ ↗ ↙',
    orderFree: 'Ordine delle tavole libero – ognuna una volta',
    scanCols: 'In ogni tavola leggi per colonne',
    roundsTitle: 'Giri',
    roundText: '{n} lettere · durata {d} · {e} errori',
    timeTitle: 'Tempo per lettera',
    median: 'Mediana',
    wholeSession: 'intera seduta',
    first: 'Prima metà',
    last: 'Seconda metà',
    halfText: '{a} di {b} lettere senza errori',
    dirTitle: 'Tempo da tocco a tocco per direzione (cambio di tavola)',
    right: 'verso destra',
    left: 'verso sinistra',
    down: 'verso il basso',
    up: 'verso l’alto',
    downRight: 'in basso a destra',
    upLeft: 'in alto a sinistra',
    upRight: 'in alto a destra',
    downLeft: 'in basso a sinistra',
    fastest: 'direzione più veloce',
    slowest: 'direzione più lenta',
    fewHits: 'ancora troppo pochi cambi',
    count: '{n}×',
    note:
      'Viene misurato il tempo da tocco a tocco: cercare, riconoscere e il movimento del dito – non lo sguardo da solo, che non viene misurato. Il primo tocco di ogni giro e le lettere con un errore prima non contano come tempo. Il tempo dipende in buona parte dal percorso del dito: i percorsi orizzontali, verticali e diagonali hanno lunghezze diverse (a seconda che il dispositivo sia in verticale o in orizzontale). I touchscreen misurano un po’ in più (negli smartphone circa 50–70 ms, nei tablet non studiato). Confrontati solo con i tuoi valori su questo dispositivo.',
    jumpTitle: 'Cambio di tavola e tempo nella stessa tavola',
    jumpSwitch: 'Al cambio di tavola',
    jumpWithin: 'Nella stessa tavola',
    jumpCost: 'Differenza',
    jumpNote: 'La differenza mostra quanto ci vuole di più per passare a un’altra tavola. È solo un confronto con te stesso e con prima.',
    beatTitle: 'Ritmo (opzione)',
    beatTempo: 'Ritmo',
    beatShare: 'A tempo',
    beatShareText: '{a} di {b} tocchi entro ±0,3 s da un battito',
    beatNote:
      'Il ritmo è solo un suono e mai un motivo di errore; livello e tempi vengono calcolati come senza ritmo. Chi aspetta il ritmo diventa più lento – confronta i tempi con ritmo solo con sedute con lo stesso ritmo. Più il ritmo è veloce, più spesso un tocco cade anche per caso nella finestra; il valore conta solo nel confronto con te stesso.',
    noData: '–',
  },
  options: {
    metronome: {
      title: 'Ritmo (metronomo)',
      hint: 'Un suono leggero e regolare: un battito per una lettera (è una nostra ipotesi). Medio sono 60 battiti al minuto. Solo da ascoltare: con l’audio spento non c’è ritmo. Il ritmo è facoltativo; che serva a qualcosa non è dimostrato.',
      choices: { slow: 'Lento\n1,4 s', medium: 'Medio\n1,0 s', fast: 'Veloce\n0,8 s' },
    },
  },
};
