/**
 * Alle Texte der Oberfläche an einer Stelle (Deutsch). Für Italienisch später ein zweites Objekt `it` mit
 * demselben Typ anlegen und in `t` auswählen.
 */
import type { GameMessage } from './game/types';

/** Pflichthinweis (Wortlaut der Spezifikation, Abschnitt Sicherheit) */
export const SAFETY_NOTICE =
  'Diese Software ist ein Forschungs-/Trainingsprototyp. Sie ersetzt keine augenärztliche oder optometrische Untersuchung und ist nicht als eigenständige Behandlung von Amblyopie validiert.';

const de = {
  appName: 'Binocular Mine',
  pageTitle: 'Binocular Mine – Prototyp',
  subtitle: 'Prototyp eines dichoptischen Binokulartrainings mit Anaglyphenbrille',
  safetyTitle: 'Wichtiger Hinweis',
  safetyNotice: SAFETY_NOTICE,
  complaintsAdvice: 'Bei Doppelbildern, Kopfschmerzen, Übelkeit oder deutlichen Augenbeschwerden die Session sofort beenden.',
  glassesHint: 'Bitte die Rot-Cyan- bzw. Rot-Grün-Brille aufsetzen. Raum abdunkeln, Bildschirmhelligkeit wie bei der Kalibrierung.',
  rotate: 'Bitte das Gerät quer halten.',
  back: 'Zurück',
  close: 'Schließen',
  save: 'Speichern',
  cancel: 'Abbrechen',
  yes: 'Ja',
  no: 'Nein',
  // Start
  startTraining: 'Training starten',
  calibrate: 'Kalibrierung',
  history: 'Verlauf',
  therapist: 'Therapeutenbereich',
  lastCalibration: (d: string) => `Letzte Kalibrierung: ${d}`,
  notCalibrated: 'Noch nicht kalibriert – beim Spielstart öffnet sich die Kalibrierung (dort geht es auch mit Startwerten weiter).',
  howTitle: 'So geht das Spiel',
  how: [
    'Kleine Roboter graben in einer Mine nach Kristallen und bringen sie zur Basis.',
    'Roboter antippen, dann ein Ziel antippen: Der Roboter läuft hin. Erde antippen: graben. Gegenstände, Schalter und Türen antippen: benutzen.',
    'Manche Dinge sieht nur ein Auge: Erst beide Augen zusammen zeigen den ganzen Weg.',
    'Keine Eile: Es zählt genaues Hinschauen, nicht Tempo.',
  ],
  // Kalibrierung
  calTitle: 'Kalibrierung',
  calIntro:
    'Hier werden Rot, Zweitfarbe und Hintergrund passend zu deiner Brille und deinem Bildschirm eingestellt. Das Ergebnis wird als Profil gespeichert und beim Spielstart ausgewählt.',
  calPlayDefaults: 'Mit Startwerten spielen',
  calPlayDefaultsHint: 'Die Startwerte passen nicht zu jeder Brille. Für ein gutes Ergebnis bitte die Feinabstimmung (Schritt 5) machen.',
  calProfiles: 'Farbprofile',
  calProfileActive: 'Aktives Profil',
  calProfileNew: 'Neue Kalibrierung',
  calProfileRename: 'Umbenennen',
  calProfileRenamePrompt: 'Neuer Name des Profils:',
  calProfileDelete: 'Löschen',
  calProfileDeleteConfirm: (name: string) => `Profil „${name}“ löschen?`,
  calProfileExport: 'Profile exportieren (JSON)',
  calProfileImport: 'Profile importieren (JSON)',
  calProfileImported: (n: number) => (n === 1 ? '1 Profil importiert.' : `${n} Profile importiert.`),
  calProfileImportError: {
    json: 'Die Datei ist kein gültiges JSON.',
    format: 'Die Datei enthält keine Farbprofile dieses Programms.',
    version: 'Die Version der Datei wird nicht unterstützt.',
    empty: 'Die Datei enthält keine gültigen eigenen Profile.',
  } as Record<string, string>,
  calProfileStartNote: 'Startwerte (fest, nicht löschbar)',
  calProfileSaved: (name: string) => `Profil „${name}“ gespeichert und aktiviert.`,
  calProfileDeleted: 'Profil gelöscht.',
  calProfileRenamed: 'Profil umbenannt.',
  calGlasses: 'Brillentyp',
  calMapping: 'Glas vor dem linken Auge',
  calSwap: 'Zuordnung tauschen',
  calStepNames: ['Vorbereitung', 'Messbild', 'Foto rotes Glas', 'Foto zweites Glas', 'Berechnung', 'Feinabstimmung', 'Kontrolle'],
  calNext: 'Weiter',
  calSkipPhotos: 'Ohne Fotos direkt zur Feinabstimmung',
  calPrepTitle: 'Schritt 0: Vorbereitung',
  calPrep: [
    'Nachtmodus, Blaulichtfilter (z. B. „Nachtlicht“, „Night Shift“), f.lux und HDR ausschalten.',
    'Bildschirmhelligkeit fest einstellen (keine automatische Helligkeit) und danach nicht mehr ändern.',
    'Raum abdunkeln, Spiegelungen auf dem Bildschirm vermeiden.',
    'Browser im Vollbild verwenden.',
    'Ein Profil gilt für eine Brille an einem Bildschirm. Für andere Geräte oder Brillen ein eigenes Profil anlegen.',
  ],
  calFullscreen: 'Vollbild',
  calPatternTitle: 'Schritt 1: Messbild fotografieren',
  calPattern: [
    'Messbild öffnen: fünf große Felder Weiß, Rot, Grün, Blau, Schwarz auf Schwarz.',
    'Mit dem Handy zweimal fotografieren: einmal durch das rote Glas, einmal durch das zweite Glas. Das Glas jeweils direkt vor die Kameralinse halten.',
    'Kamera im Pro- bzw. manuellen Modus: Weißabgleich, ISO und Belichtung fest einstellen und zwischen den beiden Fotos nicht ändern.',
    'Belichtung so niedrig wählen, dass kein Feld ausfrisst (auch Weiß muss deutlich unter der vollen Helligkeit bleiben).',
    'Als JPG speichern, nicht als HEIC (iPhone: Einstellungen › Kamera › Formate › „Maximale Kompatibilität“).',
  ],
  calPatternOpen: 'Messbild öffnen',
  calPatternClose: 'Antippen oder Esc schließt das Messbild',
  calFieldNames: { white: 'Weiß', red: 'Rot', green: 'Grün', blue: 'Blau', black: 'Schwarz' } as Record<string, string>,
  calPhotoTitleRed: 'Schritt 2: Foto durch das rote Glas',
  calPhotoTitleSecond: (glass: string) => `Schritt 3: Foto durch das ${glass} Glas`,
  calGlassAdj: { CYAN: 'cyane', GREEN: 'grüne' } as Record<string, string>,
  calPhotoPick: 'Foto wählen (JPG oder PNG)',
  calPhotoHint: 'Dann im Foto der Reihe nach auf die Felder tippen: Weiß, Rot, Grün, Blau, Schwarz. Je Feld wird eine kleine Fläche in voller Bildauflösung ausgewertet.',
  calPhotoNextField: (field: string) => `Als Nächstes antippen: ${field}`,
  calPhotoAllDone: 'Alle fünf Felder markiert.',
  calPhotoReset: 'Zurücksetzen',
  calPhotoHeic:
    'Dieses Bildformat (HEIC) kann der Browser nicht öffnen. Bitte als JPG speichern (iPhone: Einstellungen › Kamera › Formate › „Maximale Kompatibilität“) oder das Foto als JPG exportieren.',
  calPhotoError: 'Das Bild konnte nicht geöffnet werden. Bitte ein JPG- oder PNG-Foto wählen.',
  calPhotoOver: (fields: string) => `Überbelichtet: ${fields}. Bitte mit niedrigerer Belichtung neu fotografieren.`,
  calPhotoField: 'Feld',
  calPhotoRaw: 'Rohwert R / G / B',
  calPhotoY: 'Y (linear)',
  calPhotoResult: (sym: string, r: string, g: string, b: string) => `Ergebnis: ${sym}_R = ${r}, ${sym}_G = ${g}, ${sym}_B = ${b} (Schwarz abgezogen)`,
  calComputeTitle: 'Schritt 4: Berechnung',
  calComputeMissing: 'Für die Berechnung werden beide Fotos gebraucht (Schritte 2 und 3). Ohne Fotos geht es direkt mit der Feinabstimmung weiter.',
  calMeasured: 'Messwerte (Leuchtdichte Y, Schwarz abgezogen)',
  calGlassRed: 'rotes Glas (a)',
  calGlassSecond: 'zweites Glas (c)',
  calCandidates: 'Kandidaten für die Zweitfarbe (linear)',
  calChosen: 'gewählt',
  calChoiceRule: 'Gewählt wird unter allen Kandidaten mit mindestens 85 % des besten Verhältnisses C/L der mit dem größten C.',
  calGreenG: 'Grünwert g (linear)',
  calResult: 'Ergebnis',
  calColorRed: 'Rot',
  calColorSecond: 'Zweitfarbe',
  calColorBackground: 'Hintergrund',
  calFallback: 'Der Hintergrund ließ sich aus diesen Messwerten nicht berechnen – es gilt der Startwert. Bitte die Fotos prüfen.',
  calClamped: 'Hinweis: Ein Wert lag außerhalb des möglichen Bereichs und wurde begrenzt.',
  calCrosstalk: 'Übersprechen',
  calCrosstalkItems: {
    redGlassGreen: 'Rotes Glas lässt Grün durch (a_G / a_R)',
    redGlassBlue: 'Rotes Glas lässt Blau durch (a_B / a_R)',
    secondGlassRed: 'Zweites Glas lässt Rot durch (c_R / max(c_G, c_B))',
  } as Record<string, string>,
  calRating: { good: 'sehr gut', ok: 'brauchbar', hard: 'schwierig' } as Record<string, string>,
  calCrosstalkHint: 'Unter ca. 1 % sehr gut, über 5 % schwierig (ein Rest bleibt sichtbar; die Feinabstimmung hilft).',
  calApply: 'Werte übernehmen',
  calFineTitle: 'Schritt 5: Feinabstimmung nach Auge',
  calFineIntro: 'Dieser Schritt ist entscheidend. Brille aufsetzen und abwechselnd ein Auge mit der Hand zuhalten.',
  calFineSteps: [
    'Durch das zweite Glas schauen: Ist Rot noch sichtbar, „Hintergrund Zweitfarbe“ erhöhen.',
    'Durch das rote Glas schauen: Ist die Zweitfarbe noch sichtbar, erst deren Helligkeit etwas senken, dann „Hintergrund rot“ erhöhen.',
    'Werden Objekte zu dunklen Löchern, ist der Hintergrund zu hell: zurücknehmen.',
    'Schritte 1–2 abwechselnd 2–3 Mal wiederholen.',
  ],
  calSliderBgRed: 'Hintergrund rot',
  calSliderBgSecond: 'Hintergrund Zweitfarbe',
  calSliderSecond: 'Helligkeit der Zweitfarbe (%)',
  calSliderRed: 'Rotwert',
  calStartValues: 'Startwerte',
  calStartValuesHint: (fromCalc: boolean) => (fromCalc ? '„Startwerte“ setzt auf das Ergebnis der Berechnung zurück.' : '„Startwerte“ setzt auf die Startwerte des Brillentyps zurück.'),
  calPreviewRed: 'rotes Quadrat',
  calPreviewSecond: 'Kreis in Zweitfarbe',
  calPreviewGame: 'Ausschnitt aus dem Spielfeld',
  calProfileName: 'Name des Profils',
  calProfileDefaultName: (glasses: string, date: string) => `${glasses} ${date}`,
  calSaveProfile: 'Als Profil speichern',
  calCheckTitle: 'Kontrolle der Zuordnung (optional)',
  calCheckIntro: 'Mit Brille, abwechselnd ein Auge mit der Hand zuhalten. Es gibt kein Richtig oder Falsch für dich – nur die Einstellung wird geprüft.',
  calCheckStep: (n: number, of: number) => `Objekt ${n} von ${of}`,
  calQ: {
    leftEye: 'Dieses Objekt ist nur für das linke Auge gedacht. Halte abwechselnd ein Auge zu: Mit welchem Auge siehst du es?',
    rightEye: 'Dieses Objekt ist nur für das rechte Auge gedacht. Mit welchem Auge siehst du es?',
    commonObject: 'Dieses Objekt ist für beide Augen. Mit welchem Auge siehst du es?',
  } as Record<string, string>,
  calEyeLeft: 'Linkes Auge',
  calEyeRight: 'Rechtes Auge',
  calEyeBoth: 'Beide Augen',
  calEyeNone: 'Keines',
  calDone: 'Kontrolle abgeschlossen',
  calAdvice: {
    ok: 'Die Antworten passen zur eingestellten Zuordnung.',
    swapLenses: 'Links und rechts scheinen vertauscht. Bitte „Zuordnung tauschen“ antippen oder die Brille prüfen.',
    crosstalk: 'Ein Objekt für ein Auge war mit beiden Augen sichtbar (Übersprechen). Bitte die Feinabstimmung wiederholen.',
    notVisible: 'Etwas war nicht sichtbar. Bitte die Bildschirmhelligkeit und die Feinabstimmung prüfen.',
  } as Record<string, string>,
  calRepeat: 'Wiederholen',
  calContinue: 'Weiter zum Spiel',
  // Setup
  setupTitle: 'Augen und Farben',
  setupProfile: 'Farbprofil (Brille + Bildschirm)',
  setupProfileHint: 'Eigene Profile entstehen in der Kalibrierung.',
  profileSwatches: (red: string, second: string, bg: string) => `Rot ${red}, Zweitfarbe ${second}, Hintergrund ${bg}`,
  activeProfile: (name: string) => `Farbprofil: ${name}`,
  setupAmblyopic: 'Amblyopes (schwächeres) Auge',
  left: 'links',
  right: 'rechts',
  leftCap: 'Links',
  rightCap: 'Rechts',
  glassesRedCyan: 'Rot / Cyan',
  glassesRedGreen: 'Rot / Grün',
  lensLeftRed: (other: string) => `links Rot, rechts ${other}`,
  lensLeftOther: (other: string) => `links ${other}, rechts Rot`,
  setupSummary: (amb: string, ambColor: string, fel: string, felColor: string) => `Das amblyope Auge (${amb}) sieht die ${ambColor} Objekte, das dominante Auge (${fel}) die ${felColor}.`,
  /** Farbadjektiv der tatsächlich gezeichneten Farbe (Rot bzw. Zweitfarbe des Profils) */
  colorAdj: { RED: 'roten', BLUE: 'blauen', GREEN: 'grünen', CYAN: 'blaugrünen' } as Record<string, string>,
  setupContrast: (a: string, f: string) => `Kontrast: amblyopes Auge ${a} %, dominantes Auge ${f} %`,
  play: 'Spiel starten',
  // Spiel
  session: 'Session',
  level: 'Level',
  crystals: 'Kristalle',
  failures: 'Fehlversuche',
  time: 'Zeit',
  pause: 'Pause',
  drop: 'Ablegen',
  complaints: 'Beschwerden – Session beenden',
  endSession: 'Session beenden',
  restartLevel: 'Level neu starten',
  resume: 'Weiterspielen',
  pausedTitle: 'Pause',
  pausedText: 'Brille kurz abnehmen, in die Ferne schauen, blinzeln.',
  pauseOfferTitle: 'Kurze Pause?',
  pauseOfferText: 'Du spielst schon eine Weile. Eine kurze Pause tut den Augen gut.',
  takePause: 'Pause machen',
  levelDoneTitle: 'Geschafft!',
  levelTimeoutTitle: 'Zeit ist um',
  levelTimeoutText: 'Kein Problem – beim nächsten Mal klappt es.',
  nextLevel: 'Nächstes Level',
  playAgain: 'Level nochmal spielen',
  allLevelsDone: 'Alle 10 Level geschafft – super! Du kannst jedes Level noch einmal spielen.',
  chooseLevel: 'Level wählen',
  // Levelauswahl
  levelSelectTitle: 'Level wählen',
  levelSelectHint: 'Ein Level wird frei, wenn das vorherige geschafft ist. Sterne zeigen das beste Ergebnis.',
  levelLocked: 'gesperrt',
  levelCard: (n: number, name: string) => `Level ${n}: ${name}`,
  levelStars: (n: number) => (n === 0 ? 'noch keine Sterne' : `${n} von 3 Sternen`),
  playLevel: (n: number) => `Level ${n} spielen`,
  // Ton
  sound: 'Ton',
  soundOn: 'Ton an',
  soundOff: 'Ton aus',
  volume: 'Lautstärke',
  volumes: { LOW: 'leise', MEDIUM: 'mittel', HIGH: 'laut' } as Record<string, string>,
  soundHud: (on: boolean, vol: string) => (on ? `Ton: ${vol}` : 'Ton: aus'),
  soundHint: 'Leise, kurze Töne zu jeder Aktion. Startet erst nach dem ersten Antippen.',
  starsLabel: (n: number) => `${n} von 3 Sternen`,
  contrastNow: (v: string) => `Kontrast dominantes Auge: ${v} %`,
  contrastChange: (a: string, b: string) => `Kontrast dominantes Auge: ${a} % → ${b} %`,
  checkQuestion: 'Welches Zeichen hast du gesehen?',
  checkNotSeen: 'Nicht gesehen',
  shapes: { circle: 'Kreis', triangle: 'Dreieck', square: 'Quadrat', star: 'Stern' } as Record<string, string>,
  autoplay: 'Automatik läuft',
  debugTitle: 'Debug',
  debugViews: { AMBLYOPIC_ONLY: '1 Amblyop', FELLOW_ONLY: '2 Dominant', BINOCULAR: '3 Gesamt', ANAGLYPH_SIM: '4 Filter-Simulation', CLASSES: '5 Klassen' } as Record<string, string>,
  simLeft: (f: string) => `Linkes Auge (Filter ${f})`,
  simRight: (f: string) => `Rechtes Auge (Filter ${f})`,
  filterName: { RED: 'Rot', CYAN: 'Cyan', GREEN: 'Grün' } as Record<string, string>,
  levelNames: {
    level01: 'Der erste Schacht',
    level02: 'Zwei Schlüssel',
    level03: 'Unsichtbare Leitern',
    level04: 'Teamarbeit',
    level05: 'Glitzernde Wände',
    level06: 'Wandernde Glut',
    level07: 'Die Wippe',
    level08: 'Blasse Kristalle',
    level09: 'Die große Mine',
    level10: 'Meisterprüfung',
  } as Record<string, string>,
  /** kurzer Hinweis zu Beginn eines Levels (was ist neu?) */
  levelIntro: {
    level01: 'Tippe zuerst einen Roboter an.',
    level02: 'Neu: zwei Schlüssel. Kerben am Schlüssel und Punkte an der Tür gehören zusammen.',
    level03: 'Neu: Die Leitern sieht nur ein Auge – die Kristalle nur das andere.',
    level04: 'Neu: zwei Roboter. Einer stellt sich auf die Druckplatte, der andere läuft über die Brücke. Roboter antippen zum Wechseln.',
    level05: 'Kleinere Dinge, mehr Steine: Genau hinschauen, nicht alles Glitzernde ist ein Kristall.',
    level06: 'Neu: Eine Glut wandert langsam auf ihrer Bahn. Warten, bis sie weit weg ist – dann gehen.',
    level07: 'Neu: Der Schalter bewegt zwei Brücken gegenläufig. Überlege die Reihenfolge.',
    level08: 'Die Kristalle sind blass. In Ruhe suchen.',
    level09: 'Eine große Mine. Zum Umsehen das Bild mit dem Finger ziehen.',
    level10: 'Alles zusammen: zwei Roboter, Druckplatte, Wippe, wandernde Glut. Viel Erfolg!',
  } as Record<string, string>,
  messages: {
    selectRobot: 'Tippe zuerst einen Roboter an.',
    robotSelected: 'Roboter ausgewählt. Jetzt ein Ziel antippen.',
    noPath: 'Dorthin gibt es (noch) keinen Weg.',
    needKey: 'Die Tür ist verschlossen – du brauchst einen Schlüssel.',
    doorOpened: 'Die Tür ist offen.',
    switchOn: 'Schalter umgelegt – irgendwo hat sich etwas bewegt.',
    switchOff: 'Schalter zurückgelegt.',
    dug: 'Gegraben.',
    pickedKey: 'Schlüssel aufgenommen.',
    pickedCrystal: 'Kristall aufgenommen – ab zur Basis!',
    handsFull: 'Der Roboter trägt schon etwas.',
    dropped: 'Abgelegt.',
    nothingHere: 'Hier gibt es nichts zu tun.',
    delivered: 'Kristall abgeliefert!',
    needCrystal: 'Bring einen Kristall zur Basis.',
    hazard: 'Autsch – Glut berührt! Der Roboter ist zurück am letzten sicheren Punkt.',
    won: 'Alle Kristalle sind in der Basis!',
    // nur Ton, kein Text (die vorige Meldung bleibt stehen)
    moveStart: '',
    platformMoved: '',
    plateOn: 'Druckplatte gedrückt – irgendwo hat sich etwas bewegt.',
    plateOff: 'Druckplatte losgelassen.',
  } satisfies Record<GameMessage, string>,
  // Session-Ende
  endTitle: 'Session beendet',
  endComplaints: 'Session wegen Beschwerden beendet. Bitte Brille abnehmen und eine Pause machen. Wenn die Beschwerden anhalten, bitte die betreuende Augenärztin, den Augenarzt oder die Optometristin bzw. den Optometristen ansprechen.',
  endPlayTime: 'Spielzeit',
  endLevels: 'Level',
  endLevelsValue: (played: number, done: number, highest: number) => `${played} gespielt, ${done} geschafft (höchstes: ${highest})`,
  endSuccess: 'Erfolgsrate',
  endContrast: 'Aktueller Kontrast des dominanten Auges',
  toHistory: 'Zum Verlauf',
  toStart: 'Zum Start',
  // Verlauf
  historyTitle: 'Verlauf',
  historyEmpty: 'Noch keine Sessions gespeichert.',
  chartContrast: 'Kontrast des dominanten Auges (Ende jeder Session, %)',
  chartSuccess: 'Erfolgsrate je Session (%)',
  chartMinutes: 'Aktive Trainingszeit pro Tag (Minuten)',
  chartSuppression: 'Kontrollaufgaben richtig erkannt (% je Session)',
  chartNoData: 'Noch keine Daten.',
  historyNote: 'Die Diagramme zeigen nur protokollierte Werte. Sie sind keine Diagnose und keine Bewertung.',
  tableTitle: 'Sessions',
  thDate: 'Datum',
  thStart: 'Start',
  thActive: 'Spielzeit',
  thLevels: 'Level',
  thLevelNos: 'Level (Sterne)',
  thStars: 'Sterne',
  thSuccess: 'Erfolg',
  thErrors: 'Fehler',
  thContrast: 'Kontrast dom.',
  thChecks: 'Kontrollen',
  thNote: 'Hinweis',
  thEnd: 'Ende',
  endReason: { time: 'Zeit', user: 'beendet', complaints: 'Beschwerden', interrupted: 'unterbrochen' } as Record<string, string>,
  exportCsv: 'Sessions als CSV exportieren',
  // Therapeut
  pinTitle: 'Therapeutenbereich',
  pinLabel: 'PIN',
  pinWrong: 'PIN falsch.',
  pinEnter: 'Öffnen',
  pinHint: 'Leichter Schutz gegen versehentliches Verstellen (nur auf diesem Gerät).',
  therapistTitle: 'Therapeutenbereich',
  secPatient: 'Patient (nur Pseudonym)',
  patientId: 'Patient-ID (Pseudonym)',
  patientIdHint: 'Bitte keine Klarnamen eintragen. Daten bleiben auf diesem Gerät.',
  age: 'Alter (Jahre)',
  secVision: 'Augen und Brille',
  amblyopicEye: 'Amblyopes Auge',
  glasses: 'Brillentyp',
  mapping: 'Anaglyphen-Zuordnung',
  secContrast: 'Kontrast',
  amblyopicContrast: 'amblyopicContrast – Kontrast amblyopes Auge (%)',
  fellowEyeContrast: 'fellowEyeContrast – aktueller Kontrast dominantes Auge (%)',
  startFellowEyeContrast: 'startFellowEyeContrast – Startwert dominantes Auge (%)',
  adaptiveContrast: 'Adaptive Kontraststeuerung',
  contrastMode: 'Modus',
  modes: { PERCENTUAL: 'PERCENTUAL (+10 % / −5 % des Werts)', LINEAR: 'LINEAR (+5 / −5 Prozentpunkte)', MANUAL: 'MANUAL (keine automatische Änderung)' } as Record<string, string>,
  adaptiveHint: 'Erfolg = Level mit mindestens 2 Sternen abgeschlossen. Wiederholter Misserfolg = 2 Level in Folge nicht geschafft (Zeit abgelaufen, neu gestartet) oder nur 1 Stern.',
  secSession: 'Session und Spiel',
  sessionMinutes: 'Sessiondauer (Minuten)',
  maxLevelMinutes: 'Maximale Leveldauer (Minuten)',
  objectSize: 'Objektgröße (% der Levelvorgabe)',
  difficulty: 'Schwierigkeitsgrad',
  difficulties: { EASY: 'leicht', MEDIUM: 'mittel', HARD: 'schwer' } as Record<string, string>,
  difficultyHint: 'Wirkt auf Richtzeit, Ablenkung, Objektgröße und (nur „schwer“) etwas auf das Tempo.',
  pauseOffer: 'Alle 10 Minuten eine Pause anbieten',
  suppressionChecks: 'Kontrollaufgaben (Symbol nur für das amblyope Auge)',
  reduceFellow: 'Nach „Stimulus möglicherweise nicht wahrgenommen“ Kontrast des dominanten Auges senken',
  debugMode: 'Entwicklermodus (Debug-Ansichten, Tasten 1–5)',
  secSound: 'Ton (Voreinstellung)',
  soundPreset: 'Ton an',
  soundPresetHint: 'Voreinstellung für die Person. Ändert sie den Ton im Startbildschirm oder im Spiel, gilt ihre Wahl, bis hier wieder etwas eingestellt wird.',
  secLevels: 'Level',
  startLevel: 'Startlevel (nächstes Spiel beginnt hier)',
  unlockAll: 'Alle Level freischalten',
  unlockedInfo: (n: number, total: number) => `Freigeschaltet: Level 1–${n} von ${total}.`,
  allUnlocked: 'Alle Level freigeschaltet.',
  secPin: 'PIN ändern',
  newPin: 'Neue PIN (3–8 Ziffern)',
  repeatPin: 'PIN wiederholen',
  pinChanged: 'PIN geändert.',
  pinInvalid: 'Die PIN muss aus 3 bis 8 Ziffern bestehen.',
  pinMismatch: 'Die beiden Eingaben stimmen nicht überein.',
  changePin: 'PIN ändern',
  secData: 'Daten',
  exportJson: 'Einstellungen als JSON exportieren',
  importJson: 'Einstellungen importieren (JSON)',
  profileInfo: (name: string) => `Aktives Farbprofil: ${name}. Profile anlegen und verwalten: Kalibrierung.`,
  imported: 'Einstellungen importiert.',
  importError: { json: 'Die Datei ist kein gültiges JSON.', format: 'Die Datei enthält keine Einstellungen dieses Programms.', version: 'Die Version der Datei wird nicht unterstützt.' } as Record<string, string>,
  resetTraining: 'Training zurücksetzen',
  resetConfirm: 'Alle Sessions löschen und den Kontrast des dominanten Auges auf den Startwert setzen?',
  resetDone: 'Training zurückgesetzt.',
  saved: 'Gespeichert.',
  sessionsStored: (n: number) => `${n} Sessions gespeichert.`,
  on: 'an',
  off: 'aus',
};

export type Texts = typeof de;

export const t: Texts = de;
