/**
 * Alle Texte der Oberfläche an einer Stelle (Deutsch). Für Italienisch später ein zweites Objekt `it` mit
 * demselben Typ anlegen und in `t` auswählen.
 */
import type { GameMessage } from './game/types';

/** Pflichthinweis (Wortlaut der Spezifikation, Abschnitt Sicherheit) */
export const SAFETY_NOTICE =
  'Diese Software ist ein Forschungs-/Trainingsprototyp. Sie ersetzt keine augenärztliche oder optometrische Untersuchung und ist nicht als eigenständige Behandlung von Amblyopie validiert.';

const de = {
  appName: 'Binocular Mine',
  pageTitle: 'Binocular Mine – Prototyp',
  subtitle: 'Prototyp eines dichoptischen Binokulartrainings mit Anaglyphenbrille',
  safetyTitle: 'Wichtiger Hinweis',
  safetyNotice: SAFETY_NOTICE,
  complaintsAdvice: 'Bei Doppelbildern, Kopfschmerzen, Übelkeit oder deutlichen Augenbeschwerden die Session sofort beenden.',
  glassesHint: 'Bitte die Rot-Cyan- bzw. Rot-Grün-Brille aufsetzen. Raum nicht zu hell, Bildschirm auf mittlere Helligkeit.',
  rotate: 'Bitte das Gerät quer halten.',
  back: 'Zurück',
  close: 'Schließen',
  save: 'Speichern',
  cancel: 'Abbrechen',
  yes: 'Ja',
  no: 'Nein',
  // Start
  startTraining: 'Training starten',
  calibrate: 'Kalibrierung',
  history: 'Verlauf',
  therapist: 'Therapeutenbereich',
  lastCalibration: (d: string) => `Letzte Kalibrierung: ${d}`,
  notCalibrated: 'Noch nicht kalibriert – die Kalibrierung startet automatisch.',
  howTitle: 'So geht das Spiel',
  how: [
    'Kleine Roboter graben in einer Mine nach Kristallen und bringen sie zur Basis.',
    'Roboter antippen, dann ein Ziel antippen: Der Roboter läuft hin. Erde antippen: graben. Gegenstände, Schalter und Türen antippen: benutzen.',
    'Manche Dinge sieht nur ein Auge: Erst beide Augen zusammen zeigen den ganzen Weg.',
    'Keine Eile: Es zählt genaues Hinschauen, nicht Tempo.',
  ],
  // Kalibrierung
  calTitle: 'Kalibrierung',
  calIntro: 'Brille aufsetzen. Bei jedem Schritt die passende Antwort antippen. Es gibt kein Richtig oder Falsch für dich – nur die Einstellung wird geprüft.',
  calGlasses: 'Brillentyp',
  calMapping: 'Filter vor dem linken Auge',
  calSwap: 'Zuordnung tauschen',
  calPart1: 'Teil 1: Farben',
  calPart2: 'Teil 2: Augen (abwechselnd ein Auge mit der Hand zuhalten)',
  calStep: (n: number, of: number) => `Schritt ${n} von ${of}`,
  calQ: {
    objectA: 'Siehst du Objekt A (Kreis)?',
    objectB: 'Siehst du Objekt B (Quadrat)?',
    objectsBoth: 'Jetzt sind A und B gleichzeitig da (mit beiden Augen offen). Was siehst du?',
    leftEye: 'Dieses Objekt ist nur für das linke Auge gedacht. Halte abwechselnd ein Auge zu: Mit welchem Auge siehst du es?',
    rightEye: 'Dieses Objekt ist nur für das rechte Auge gedacht. Mit welchem Auge siehst du es?',
    commonObject: 'Dieses Objekt ist für beide Augen. Mit welchem Auge siehst du es?',
  },
  calSeeA: 'Ich sehe Objekt A',
  calSeeB: 'Ich sehe Objekt B',
  calSeeBoth: 'Ich sehe beide',
  calSeeOne: 'Ich sehe nur eins',
  calSeeNothing: 'Ich sehe nichts',
  calEyeLeft: 'Linkes Auge',
  calEyeRight: 'Rechtes Auge',
  calEyeBoth: 'Beide Augen',
  calEyeNone: 'Keines',
  calDone: 'Kalibrierung abgeschlossen',
  calAdvice: {
    ok: 'Die Antworten passen zur eingestellten Zuordnung.',
    swapLenses: 'Links und rechts scheinen vertauscht. Bitte „Zuordnung tauschen“ antippen oder die Brille prüfen.',
    crosstalk: 'Ein Objekt für ein Auge war mit beiden Augen sichtbar (Übersprechen). Bitte die Farben unten fein einstellen.',
    notVisible: 'Etwas war nicht sichtbar. Bitte Helligkeit des Bildschirms und die Farbwerte prüfen.',
  },
  calRepeat: 'Wiederholen',
  calContinue: 'Weiter',
  calFine: 'Feineinstellung der Farben (für Therapeuten)',
  calFineHint: 'Ziel: Durch das rote Glas verschwindet die zweite Farbe fast ganz, durch das Cyan- bzw. Grünglas die rote. Statt Reglern wählst du aus Kästen – wie beim Augenoptiker „so oder so?“. Raum abdunkeln, Bildschirm auf mittlere Helligkeit.',
  fineProgress: (color: string, n: number, round: number) => `Farbe ${n} von 2: ${color} · Runde ${round} von 2 (${round === 1 ? 'grob' : 'fein'})`,
  fineVanish: (color: string, own: 'LEFT' | 'RIGHT', other: 'LEFT' | 'RIGHT') =>
    `Schritt 1: ${EYE_ACC[own]} zuhalten und nur mit dem ${EYE_DAT[other]} schauen. Tippe alle ${color}-Kästen an, die du nicht oder kaum siehst (mehrere möglich).`,
  fineClear: (color: string, other: 'LEFT' | 'RIGHT', own: 'LEFT' | 'RIGHT') =>
    `Schritt 2: Jetzt ${EYE_ACC[other]} zuhalten und mit dem ${EYE_DAT[own]} schauen. Welcher der markierten ${color}-Kästen ist am deutlichsten? Antippen.`,
  fineNext: (n: number) => (n === 0 ? 'Weiter (erst Kästen antippen)' : `Weiter mit ${n} ${n === 1 ? 'Kasten' : 'Kästen'}`),
  fineNone: 'Keiner verschwindet',
  fineNoneHint: 'Kein Kasten markiert.',
  fineBack: 'Zurück zu Schritt 1',
  fineRestart: 'Von vorn',
  fineTip: 'Verschwindet keiner: Raum dunkler machen, Bildschirmhelligkeit etwas senken oder Spiegelungen vermeiden. „Keiner verschwindet“ nimmt den dunkelsten mittleren Kasten.',
  fineDone: 'Feinkalibrierung abgeschlossen. Diese Farben werden jetzt verwendet:',
  fineAgain: 'Feinkalibrierung wiederholen',
  fineExpert: 'Experte: RGB-Werte direkt eingeben',
  calColorRed: 'Rot',
  calColorCyan: 'Cyan',
  calColorGreen: 'Grün',
  calReset: 'Werkseinstellung',
  calFormRed: 'rote Form',
  calFormOther: 'zweite Form',
  // Setup
  setupTitle: 'Augen und Farben',
  setupAmblyopic: 'Amblyopes (schwächeres) Auge',
  left: 'links',
  right: 'rechts',
  leftCap: 'Links',
  rightCap: 'Rechts',
  glassesRedCyan: 'Rot / Cyan',
  glassesRedGreen: 'Rot / Grün',
  lensLeftRed: (other: string) => `links Rot, rechts ${other}`,
  lensLeftOther: (other: string) => `links ${other}, rechts Rot`,
  setupSummary: (amb: string, ambColor: string, fel: string, felColor: string) => `Das amblyope Auge (${amb}) sieht die ${ambColor} Objekte, das dominante Auge (${fel}) die ${felColor}.`,
  colorAdj: { RED: 'roten', CYAN: 'cyanfarbenen', GREEN: 'grünen' } as Record<string, string>,
  setupContrast: (a: string, f: string) => `Kontrast: amblyopes Auge ${a} %, dominantes Auge ${f} %`,
  play: 'Spiel starten',
  // Spiel
  session: 'Session',
  level: 'Level',
  crystals: 'Kristalle',
  failures: 'Fehlversuche',
  time: 'Zeit',
  pause: 'Pause',
  drop: 'Ablegen',
  complaints: 'Beschwerden – Session beenden',
  endSession: 'Session beenden',
  restartLevel: 'Level neu starten',
  resume: 'Weiterspielen',
  pausedTitle: 'Pause',
  pausedText: 'Brille kurz abnehmen, in die Ferne schauen, blinzeln.',
  pauseOfferTitle: 'Kurze Pause?',
  pauseOfferText: 'Du spielst schon eine Weile. Eine kurze Pause tut den Augen gut.',
  takePause: 'Pause machen',
  levelDoneTitle: 'Geschafft!',
  levelTimeoutTitle: 'Zeit ist um',
  levelTimeoutText: 'Kein Problem – beim nächsten Mal klappt es.',
  nextLevel: 'Nächstes Level',
  playAgain: 'Level nochmal spielen',
  allLevelsDone: 'Alle 10 Level geschafft – super! Du kannst jedes Level noch einmal spielen.',
  chooseLevel: 'Level wählen',
  // Levelauswahl
  levelSelectTitle: 'Level wählen',
  levelSelectHint: 'Ein Level wird frei, wenn das vorherige geschafft ist. Sterne zeigen das beste Ergebnis.',
  levelLocked: 'gesperrt',
  levelCard: (n: number, name: string) => `Level ${n}: ${name}`,
  levelStars: (n: number) => (n === 0 ? 'noch keine Sterne' : `${n} von 3 Sternen`),
  playLevel: (n: number) => `Level ${n} spielen`,
  // Ton
  sound: 'Ton',
  soundOn: 'Ton an',
  soundOff: 'Ton aus',
  volume: 'Lautstärke',
  volumes: { LOW: 'leise', MEDIUM: 'mittel', HIGH: 'laut' } as Record<string, string>,
  soundHud: (on: boolean, vol: string) => (on ? `Ton: ${vol}` : 'Ton: aus'),
  soundHint: 'Leise, kurze Töne zu jeder Aktion. Startet erst nach dem ersten Antippen.',
  starsLabel: (n: number) => `${n} von 3 Sternen`,
  contrastNow: (v: string) => `Kontrast dominantes Auge: ${v} %`,
  contrastChange: (a: string, b: string) => `Kontrast dominantes Auge: ${a} % → ${b} %`,
  checkQuestion: 'Welches Zeichen hast du gesehen?',
  checkNotSeen: 'Nicht gesehen',
  shapes: { circle: 'Kreis', triangle: 'Dreieck', square: 'Quadrat', star: 'Stern' } as Record<string, string>,
  autoplay: 'Automatik läuft',
  debugTitle: 'Debug',
  debugViews: { AMBLYOPIC_ONLY: '1 Amblyop', FELLOW_ONLY: '2 Dominant', BINOCULAR: '3 Gesamt', ANAGLYPH_SIM: '4 Filter-Simulation', CLASSES: '5 Klassen' } as Record<string, string>,
  simLeft: (f: string) => `Linkes Auge (Filter ${f})`,
  simRight: (f: string) => `Rechtes Auge (Filter ${f})`,
  filterName: { RED: 'Rot', CYAN: 'Cyan', GREEN: 'Grün' } as Record<string, string>,
  levelNames: {
    level01: 'Der erste Schacht',
    level02: 'Zwei Schlüssel',
    level03: 'Unsichtbare Leitern',
    level04: 'Teamarbeit',
    level05: 'Glitzernde Wände',
    level06: 'Wandernde Glut',
    level07: 'Die Wippe',
    level08: 'Blasse Kristalle',
    level09: 'Die große Mine',
    level10: 'Meisterprüfung',
  } as Record<string, string>,
  /** kurzer Hinweis zu Beginn eines Levels (was ist neu?) */
  levelIntro: {
    level01: 'Tippe zuerst einen Roboter an.',
    level02: 'Neu: zwei Schlüssel. Kerben am Schlüssel und Punkte an der Tür gehören zusammen.',
    level03: 'Neu: Die Leitern sieht nur ein Auge – die Kristalle nur das andere.',
    level04: 'Neu: zwei Roboter. Einer stellt sich auf die Druckplatte, der andere läuft über die Brücke. Roboter antippen zum Wechseln.',
    level05: 'Kleinere Dinge, mehr Steine: Genau hinschauen, nicht alles Glitzernde ist ein Kristall.',
    level06: 'Neu: Eine Glut wandert langsam auf ihrer Bahn. Warten, bis sie weit weg ist – dann gehen.',
    level07: 'Neu: Der Schalter bewegt zwei Brücken gegenläufig. Überlege die Reihenfolge.',
    level08: 'Die Kristalle sind blass. In Ruhe suchen.',
    level09: 'Eine große Mine. Zum Umsehen das Bild mit dem Finger ziehen.',
    level10: 'Alles zusammen: zwei Roboter, Druckplatte, Wippe, wandernde Glut. Viel Erfolg!',
  } as Record<string, string>,
  messages: {
    selectRobot: 'Tippe zuerst einen Roboter an.',
    robotSelected: 'Roboter ausgewählt. Jetzt ein Ziel antippen.',
    noPath: 'Dorthin gibt es (noch) keinen Weg.',
    needKey: 'Die Tür ist verschlossen – du brauchst einen Schlüssel.',
    doorOpened: 'Die Tür ist offen.',
    switchOn: 'Schalter umgelegt – irgendwo hat sich etwas bewegt.',
    switchOff: 'Schalter zurückgelegt.',
    dug: 'Gegraben.',
    pickedKey: 'Schlüssel aufgenommen.',
    pickedCrystal: 'Kristall aufgenommen – ab zur Basis!',
    handsFull: 'Der Roboter trägt schon etwas.',
    dropped: 'Abgelegt.',
    nothingHere: 'Hier gibt es nichts zu tun.',
    delivered: 'Kristall abgeliefert!',
    needCrystal: 'Bring einen Kristall zur Basis.',
    hazard: 'Autsch – Glut berührt! Der Roboter ist zurück am letzten sicheren Punkt.',
    won: 'Alle Kristalle sind in der Basis!',
    // nur Ton, kein Text (die vorige Meldung bleibt stehen)
    moveStart: '',
    platformMoved: '',
    plateOn: 'Druckplatte gedrückt – irgendwo hat sich etwas bewegt.',
    plateOff: 'Druckplatte losgelassen.',
  } satisfies Record<GameMessage, string>,
  // Session-Ende
  endTitle: 'Session beendet',
  endComplaints: 'Session wegen Beschwerden beendet. Bitte Brille abnehmen und eine Pause machen. Wenn die Beschwerden anhalten, bitte die betreuende Augenärztin, den Augenarzt oder die Optometristin bzw. den Optometristen ansprechen.',
  endPlayTime: 'Spielzeit',
  endLevels: 'Level',
  endLevelsValue: (played: number, done: number, highest: number) => `${played} gespielt, ${done} geschafft (höchstes: ${highest})`,
  endSuccess: 'Erfolgsrate',
  endContrast: 'Aktueller Kontrast des dominanten Auges',
  toHistory: 'Zum Verlauf',
  toStart: 'Zum Start',
  // Verlauf
  historyTitle: 'Verlauf',
  historyEmpty: 'Noch keine Sessions gespeichert.',
  chartContrast: 'Kontrast des dominanten Auges (Ende jeder Session, %)',
  chartSuccess: 'Erfolgsrate je Session (%)',
  chartMinutes: 'Aktive Trainingszeit pro Tag (Minuten)',
  chartSuppression: 'Kontrollaufgaben richtig erkannt (% je Session)',
  chartNoData: 'Noch keine Daten.',
  historyNote: 'Die Diagramme zeigen nur protokollierte Werte. Sie sind keine Diagnose und keine Bewertung.',
  tableTitle: 'Sessions',
  thDate: 'Datum',
  thStart: 'Start',
  thActive: 'Spielzeit',
  thLevels: 'Level',
  thLevelNos: 'Level (Sterne)',
  thStars: 'Sterne',
  thSuccess: 'Erfolg',
  thErrors: 'Fehler',
  thContrast: 'Kontrast dom.',
  thChecks: 'Kontrollen',
  thNote: 'Hinweis',
  thEnd: 'Ende',
  endReason: { time: 'Zeit', user: 'beendet', complaints: 'Beschwerden', interrupted: 'unterbrochen' } as Record<string, string>,
  exportCsv: 'Sessions als CSV exportieren',
  // Therapeut
  pinTitle: 'Therapeutenbereich',
  pinLabel: 'PIN',
  pinWrong: 'PIN falsch.',
  pinEnter: 'Öffnen',
  pinHint: 'Leichter Schutz gegen versehentliches Verstellen (nur auf diesem Gerät).',
  therapistTitle: 'Therapeutenbereich',
  secPatient: 'Patient (nur Pseudonym)',
  patientId: 'Patient-ID (Pseudonym)',
  patientIdHint: 'Bitte keine Klarnamen eintragen. Daten bleiben auf diesem Gerät.',
  age: 'Alter (Jahre)',
  secVision: 'Augen und Brille',
  amblyopicEye: 'Amblyopes Auge',
  glasses: 'Brillentyp',
  mapping: 'Anaglyphen-Zuordnung',
  secContrast: 'Kontrast',
  amblyopicContrast: 'amblyopicContrast – Kontrast amblyopes Auge (%)',
  fellowEyeContrast: 'fellowEyeContrast – aktueller Kontrast dominantes Auge (%)',
  startFellowEyeContrast: 'startFellowEyeContrast – Startwert dominantes Auge (%)',
  adaptiveContrast: 'Adaptive Kontraststeuerung',
  contrastMode: 'Modus',
  modes: { PERCENTUAL: 'PERCENTUAL (+10 % / −5 % des Werts)', LINEAR: 'LINEAR (+5 / −5 Prozentpunkte)', MANUAL: 'MANUAL (keine automatische Änderung)' } as Record<string, string>,
  adaptiveHint: 'Erfolg = Level mit mindestens 2 Sternen abgeschlossen. Wiederholter Misserfolg = 2 Level in Folge nicht geschafft (Zeit abgelaufen, neu gestartet) oder nur 1 Stern.',
  secSession: 'Session und Spiel',
  sessionMinutes: 'Sessiondauer (Minuten)',
  maxLevelMinutes: 'Maximale Leveldauer (Minuten)',
  objectSize: 'Objektgröße (% der Levelvorgabe)',
  difficulty: 'Schwierigkeitsgrad',
  difficulties: { EASY: 'leicht', MEDIUM: 'mittel', HARD: 'schwer' } as Record<string, string>,
  difficultyHint: 'Wirkt auf Richtzeit, Ablenkung, Objektgröße und (nur „schwer“) etwas auf das Tempo.',
  pauseOffer: 'Alle 10 Minuten eine Pause anbieten',
  suppressionChecks: 'Kontrollaufgaben (Symbol nur für das amblyope Auge)',
  reduceFellow: 'Nach „Stimulus möglicherweise nicht wahrgenommen“ Kontrast des dominanten Auges senken',
  debugMode: 'Entwicklermodus (Debug-Ansichten, Tasten 1–5)',
  secSound: 'Ton (Voreinstellung)',
  soundPreset: 'Ton an',
  soundPresetHint: 'Voreinstellung für die Person. Ändert sie den Ton im Startbildschirm oder im Spiel, gilt ihre Wahl, bis hier wieder etwas eingestellt wird.',
  secLevels: 'Level',
  startLevel: 'Startlevel (nächstes Spiel beginnt hier)',
  unlockAll: 'Alle Level freischalten',
  unlockedInfo: (n: number, total: number) => `Freigeschaltet: Level 1–${n} von ${total}.`,
  allUnlocked: 'Alle Level freigeschaltet.',
  secPin: 'PIN ändern',
  newPin: 'Neue PIN (3–8 Ziffern)',
  repeatPin: 'PIN wiederholen',
  pinChanged: 'PIN geändert.',
  pinInvalid: 'Die PIN muss aus 3 bis 8 Ziffern bestehen.',
  pinMismatch: 'Die beiden Eingaben stimmen nicht überein.',
  changePin: 'PIN ändern',
  secData: 'Daten',
  exportJson: 'Einstellungen als JSON exportieren',
  importJson: 'Einstellungen importieren (JSON)',
  imported: 'Einstellungen importiert.',
  importError: { json: 'Die Datei ist kein gültiges JSON.', format: 'Die Datei enthält keine Einstellungen dieses Programms.', version: 'Die Version der Datei wird nicht unterstützt.' } as Record<string, string>,
  resetTraining: 'Training zurücksetzen',
  resetConfirm: 'Alle Sessions löschen und den Kontrast des dominanten Auges auf den Startwert setzen?',
  resetDone: 'Training zurückgesetzt.',
  saved: 'Gespeichert.',
  sessionsStored: (n: number) => `${n} Sessions gespeichert.`,
  on: 'an',
  off: 'aus',
};

export type Texts = typeof de;
const EYE_ACC = { LEFT: 'das linke Auge', RIGHT: 'das rechte Auge' } as const;
const EYE_DAT = { LEFT: 'linken Auge', RIGHT: 'rechten Auge' } as const;

export const t: Texts = de;
