import type { ScienceEntry } from '../../content/science';

const src = (label: string, url: string) => ({ label, url });

// Quellen: DOI per Crossref geprüft (Titel, Zeitschrift, Jahr, Autoren). Für die Pendelball-Form selbst gibt es keine Studie
// und deshalb keine Quelle; die Quellen belegen nur die Grundlagen (Augenfolgebewegung, bewegte Zeichen).
export const science: ScienceEntry = {
  id: 'pendelball',
  evidence: 'weak',
  texts: {
    de: {
      trains: 'Einer gleichmäßig pendelnden Kugel mit den Augen folgen – waagrecht, senkrecht, schräg und im Kreis – und dabei einen Buchstaben auf ihr erkennen, bei möglichst ruhigem Kopf.',
      daily: 'Gleichmäßig Bewegtes im Blick behalten, ohne den Kopf mitzudrehen, etwa einen pendelnden Gegenstand oder einen rollenden Ball. Ob die Übung dabei hilft, ist nicht belegt.',
      research:
        'Die Pendelball-Form mit Buchstaben bei ruhigem Kopf ist eine Praxisform der funktionellen Optometrie – nicht durch Studien belegt. Aus der Forschung zu Augenfolgebewegungen ist bekannt: Gleichmäßige, vorhersagbare Bewegungen werden genauer verfolgt als unvorhersagbare (Collewijn & Tamminga, 1984; Barnes, 2008; Kowler et al., 2019). Die Obergrenze, bis zu der das Auge einem gleichmäßig bewegten Ziel glatt folgen kann, liegt weit über dem Tempo dieser Übung und unterscheidet sich zwischen Personen (Meyer et al., 1985); waagrechte, senkrechte und schräge Folgebewegungen gelingen nicht gleich gut (Rottach et al., 1996; Ke et al., 2013). Wie gut man ein Zeichen auf einem bewegten Ziel erkennt, wird als dynamische Sehschärfe seit den 1950er-Jahren untersucht (Ludvigh & Miller, 1958). Nach kurzem Training blieb im Labor ein Effekt bei der Augenfolge einige Tage bestehen (Eibenberger et al., 2012); diese Studie arbeitete mit Blickmessung, nicht mit dieser Übung. Für Lesen, Lernschwierigkeiten oder den Alltag ist ein Nutzen nicht belegt; Übungen zur Blickfolge gelten bei Lernschwierigkeiten ausdrücklich nicht als wirksam (Handler et al., 2011). Klinisch wird die Folgebewegung der Augen geprüft, indem sie einem nahen Ziel folgen, das in einem H geführt wird (Muchnick, 2008, S. 32–35); diese Übung ist keine solche Prüfung.',
      improved:
        'Eine Sitzung besteht aus sechs Bahnen – waagrecht, senkrecht, zweimal schräg und zwei Kreise –, je etwa 12 bis 15 Sekunden lang, dazwischen eine ruhige Pause mit dem Namen der nächsten Bahn. Das Pendeln folgt einer gleichmäßigen Sinusbewegung nach der Uhr, bei den Kreisen mit gleichmäßiger Drehung; die Spitzengeschwindigkeit liegt bei etwa 25 Grad pro Sekunde oder darunter (bei 40 cm Abstand), und die Bahn ist höchstens etwa 60 % der Bildschirmbreite breit. Der Buchstabe wird weich ein- und ausgeblendet und erscheint nur im geraden, gleichmäßigen Teil eines Schlags, nie in der Umkehr; du antwortest mit einem von vier großen Buttons. Die Stufen ändern je Schritt genau ein Merkmal (Tempo, Weite, Buchstabengröße, Anzeigedauer, ähnliche Buchstaben, gemischte Reihenfolge, Kugelgröße) und passen sich nach jeder Bahn an: ab 85 % richtig geht es eine Stufe höher, unter 65 % eine tiefer. Ob dein Blick wirklich folgt und ob dein Kopf ruhig bleibt, wird nicht gemessen, nur ob du den Buchstaben erkennst.',
    },
    it: {
      trains: 'Seguire con gli occhi una sfera che oscilla in modo regolare – in orizzontale, in verticale, in diagonale e in cerchio – e riconoscere una lettera su di essa, tenendo la testa il più possibile ferma.',
      daily: 'Tenere d’occhio ciò che si muove in modo regolare senza girare la testa, per esempio un oggetto che oscilla o una palla che rotola. Se l’esercizio aiuti in questo non è dimostrato.',
      research:
        'La forma con la palla pendolo e le lettere a testa ferma è una pratica dell’optometria funzionale – non dimostrata da studi. Dalla ricerca sui movimenti di inseguimento degli occhi è noto: i movimenti regolari e prevedibili vengono seguiti con più precisione di quelli imprevedibili (Collewijn & Tamminga, 1984; Barnes, 2008; Kowler et al., 2019). Il limite fino al quale l’occhio può seguire in modo fluido un bersaglio che si muove in modo regolare è molto superiore alla velocità di questo esercizio e varia da persona a persona (Meyer et al., 1985); i movimenti di inseguimento orizzontali, verticali e diagonali non riescono ugualmente bene (Rottach et al., 1996; Ke et al., 2013). Quanto bene si riconosce un segno su un bersaglio in movimento viene studiato dagli anni Cinquanta come acuità visiva dinamica (Ludvigh & Miller, 1958). Dopo un breve allenamento, in laboratorio un effetto sull’inseguimento oculare è rimasto per alcuni giorni (Eibenberger et al., 2012); questo studio usava la misurazione dello sguardo, non questo esercizio. Un beneficio per la lettura, per le difficoltà di apprendimento o per la vita quotidiana non è dimostrato; gli esercizi di inseguimento oculare non sono considerati efficaci nelle difficoltà di apprendimento (Handler et al., 2011). Dal punto di vista clinico, l’inseguimento oculare si valuta facendo seguire agli occhi un bersaglio vicino, mosso a forma di H (Muchnick, 2008, pp. 32–35); questo esercizio non è una valutazione di questo tipo.',
      improved:
        'Una sessione consiste in sei tragitti – orizzontale, verticale, due diagonali e due cerchi –, ciascuno di circa 12–15 secondi, con in mezzo una pausa tranquilla che mostra il nome del tragitto successivo. L’oscillazione segue un movimento sinusoidale regolare basato sull’orologio, nei cerchi con rotazione uniforme; la velocità massima è di circa 25 gradi al secondo o meno (a 40 cm di distanza) e il tragitto è largo al massimo circa il 60 % della larghezza dello schermo. La lettera compare e scompare dolcemente e appare solo nel tratto rettilineo e regolare di un’oscillazione, mai nell’inversione; rispondi con uno dei quattro grandi pulsanti. I livelli cambiano a ogni passo una sola caratteristica (velocità, ampiezza, dimensione delle lettere, durata, lettere simili, ordine misto, dimensione della sfera) e si adattano dopo ogni tragitto: da 85 % di risposte giuste si sale di un livello, sotto il 65 % si scende di uno. Se il tuo sguardo segue davvero e se la testa resta ferma non viene misurato, ma solo se riconosci la lettera.',
    },
  },
  sources: [
    src('Collewijn & Tamminga (1984). Human smooth and saccadic eye movements during voluntary pursuit of different target motions on different backgrounds. The Journal of Physiology', 'https://doi.org/10.1113/jphysiol.1984.sp015242'),
    src('Barnes (2008). Cognitive processes involved in smooth pursuit eye movements. Brain and Cognition', 'https://doi.org/10.1016/j.bandc.2008.08.020'),
    src('Kowler, Rubinstein, Santos & Wang (2019). Predictive smooth pursuit eye movements. Annual Review of Vision Science', 'https://doi.org/10.1146/annurev-vision-091718-014901'),
    src('Meyer, Lasker & Robinson (1985). The upper limit of human smooth pursuit velocity. Vision Research', 'https://doi.org/10.1016/0042-6989(85)90160-9'),
    src('Rottach, Zivotofsky, Das, Averbuch-Heller, Discenna, Poonyathalang & Leigh (1996). Comparison of horizontal, vertical and diagonal smooth pursuit eye movements in normal human subjects. Vision Research', 'https://doi.org/10.1016/0042-6989(95)00302-9'),
    src('Ke, Lam, Pai & Spering (2013). Directional asymmetries in human smooth pursuit eye movements. Investigative Ophthalmology & Visual Science', 'https://doi.org/10.1167/iovs.12-11369'),
    src('Ludvigh & Miller (1958). Study of visual acuity during the ocular pursuit of moving test objects. I. Introduction. Journal of the Optical Society of America', 'https://doi.org/10.1364/josa.48.000799'),
    src('Eibenberger, Ring & Haslwanter (2012). Sustained effects for training of smooth pursuit plasticity. Experimental Brain Research', 'https://doi.org/10.1007/s00221-012-3009-8'),
    src('Handler, Fierson et al. (2011). Learning disabilities, dyslexia, and vision. Pediatrics', 'https://doi.org/10.1542/peds.2010-3670'),
    src('Muchnick (2008). Clinical Medicine in Optometric Practice. 2nd ed. Mosby/Elsevier. S. 6, 28, 32–35', 'https://openlibrary.org/isbn/9780323029612'),
  ],
};
