// Quellen: jede Angabe einzeln per Crossref (Autoren, Jahr, Titel, Zeitschrift, Band, Seiten) und PubMed (Abstract) geprüft
// (03.10.2026); die Aussagen im Text wurden mit dem Abstract abgeglichen:
// - Woollacott & Shumway-Cook (2002), Gait Posture 16(1), 1–14; Abstract bestätigt: Übersicht; Doppelaufgaben zeigten, dass der
//   Aufmerksamkeitsbedarf der Gleichgewichtskontrolle bei gesunden und gleichgewichtsgestörten Älteren zur Instabilität beiträgt;
//   der Bedarf hängt von der Schwierigkeit der Haltungsaufgabe und der Art der zweiten Aufgabe ab.
// - Silsupadol et al. (2009), Arch Phys Med Rehabil 90(3), 381–387; Abstract bestätigt: randomisierte Studie, 23 Ältere (mittleres
//   Alter 74,8 Jahre) mit Gleichgewichtsstörung, 4 Wochen, 3 × 45 min; alle Gruppen besserten sich im Berg-Balance-Wert und gingen
//   schneller; unter Doppelaufgabe nur nach Doppelaufgaben-Training; Gleichgewichtstraining mit nur einer Aufgabe überträgt sich
//   eventuell nicht auf Doppelaufgaben („may not generalize“).
// - Gallou-Guyot et al. (2020), Ageing Res Rev 63, 101135; Abstract bestätigt: Überblick über 18 Übersichten bei kognitiv gesunden
//   Älteren; insgesamt positive Effekte kognitiv-motorischer Doppelaufgaben-Programme, Exergames nur auf kognitive Funktionen,
//   Wirkung auf körperliche Funktionen umstritten, auf Doppelaufgaben nicht untersucht; Machbarkeit, Sicherheit, Übertragung und
//   Erhalt unklar.
// - Sherrington et al. (2019), Cochrane Database Syst Rev 2019(1), CD012424; Abstract bestätigt: 108 randomisierte Studien mit
//   23.407 Menschen ab 60 Jahren, die zu Hause leben; Bewegungsprogramme senken die Sturzrate (Rate Ratio 0,77), Gleichgewichts-
//   und Funktionsübungen allein 0,76 (hohe Sicherheit der Evidenz).
// - Fitts (1954) und MacKenzie (1992): wie in Spot-Touch geprüft (Crossref; Inhalt über MacKenzie).
// - Pronk et al. (2020) und Guo et al. (2025): wie in den übrigen Labor-Übungen geprüft (Behav Res Methods 52, 1371–1382;
//   Front Physiol 16).
// - Muchnick (2008), Lehrbuch (ISBN 9780323029612), S. 6 und 28: Warnzeichen mit Abklärungsbedarf (Doppelbilder, Schwindel, Kopf-
//   und Augenschmerz); Seitenangaben wie in den übrigen Übungen der App.
// Nicht aufgenommen (nicht belegt oder Wirkversprechen): jede Aussage, dass diese Bildschirm-Übung das Gleichgewicht verbessert oder
// Stürze verhindert, dass die gezählten Verluste ein Maß für das Gleichgewicht sind, oder dass sich das Üben auf Alltag, Sport oder
// Verkehr überträgt; Normwerte für Verluste oder Zeiten. Nicht bestätigt werden konnte: nichts Aufgenommenes; für genau diese Übung
// gibt es keine Studie.
import type { ScienceEntry } from '../../content/science';

const src = (label: string, url: string) => ({ label, url });

export const science: ScienceEntry = {
  id: 'labor-balance-touch',
  evidence: 'weak',
  texts: {
    de: {
      trains:
        'Im Stand (beidbeinig, einbeinig, im Tandemstand oder auf einer wackligen Fläche) erscheinende Punkte antippen – Haltung und Sehen zugleich, eine Doppelaufgabe. Eine Hilfsperson tippt auf dem Bildschirm jeden Verlust des Gleichgewichts. Standposition, Dauer, Punktgröße, Sichtbarkeit, Pause, Bereich und das Kreuz in der Mitte stellst du selbst ein.',
      daily:
        'Überall, wo man beim Stehen oder Gehen zugleich auf etwas achten und danach greifen muss, zum Beispiel beim Tippen auf dem Handy in der Bahn. Ob die Übung dabei hilft, ist nicht belegt.',
      research:
        'Gleichgewicht halten braucht Aufmerksamkeit: Eine Übersicht fand bei gesunden und bei gleichgewichtsgestörten älteren Menschen, dass dieser Bedarf zur Unsicherheit beiträgt; wie groß er ist, hängt von der Schwierigkeit der Haltungsaufgabe und von der Art der zweiten Aufgabe ab (Woollacott & Shumway-Cook, 2002). Die Zeit bis zum Antippen eines Punktes wächst mit dem Weg und sinkt mit der Größe des Ziels (Fitts, 1954; MacKenzie, 1992). Bei älteren Menschen wird Doppelaufgaben-Training im Stand und beim Gehen untersucht: In einer randomisierten Studie mit 23 älteren Menschen mit Gleichgewichtsstörung (mittleres Alter 74,8 Jahre; vier Wochen, dreimal 45 Minuten) besserten sich in allen Gruppen der Gleichgewichtswert und das Gehtempo; unter einer zusätzlichen Denkaufgabe gingen aber nur die Gruppen mit Doppelaufgaben-Training schneller, und reines Gleichgewichtstraining übertrug sich möglicherweise nicht auf Doppelaufgaben (Silsupadol et al., 2009). Ein Überblick über 18 Übersichten bei kognitiv gesunden älteren Menschen fand insgesamt positive Effekte von Doppelaufgaben-Programmen mit Bewegung; bei Bildschirmspielen mit Bewegung (Exergames) nur auf die Denkleistung, die Wirkung auf körperliche Funktionen ist umstritten, und Sicherheit, Übertragung in den Alltag und Erhalt sind unklar (Gallou-Guyot et al., 2020). Eine Cochrane-Übersicht mit 108 Studien an 23.407 Menschen ab 60 Jahren, die zu Hause leben, fand, dass Bewegungsprogramme die Sturzrate senken, am deutlichsten Gleichgewichts- und Funktionsübungen (Rate Ratio 0,76; hohe Sicherheit der Evidenz) (Sherrington et al., 2019). Das waren betreute Programme mit echten Bewegungen, keine Bildschirmübung wie diese; die App misst weder Gleichgewicht noch Haltung, und für gesunde Menschen ist ein Nutzen dieser Übung nicht belegt. Die gezählten Verluste sind Zählwerte der Hilfsperson: Was als Verlust gilt, legt ihr vorher fest, und der Wert hängt von ihrer Aufmerksamkeit ab. In Studien zu Bildschirmübungen fallen Verbesserungen deutlich größer aus, wenn die Prüfung der geübten Aufgabe ähnelt – ein großer Teil ist Gewöhnung an Aufgabe und Gerät (Guo et al., 2025); Touchscreens messen die Reaktionszeit durchweg etwas zu lang, je nach Gerät unterschiedlich (Pronk et al., 2020; Tablets wurden dort nicht untersucht). Darum zählt nur der Vergleich mit dir selbst, mit derselben Standposition, derselben Hilfsperson und denselben Einstellungen. Das Kreuz in der Mitte ist eine Bitte, keine Kontrolle: Die App kann den Blick nicht messen. Schwindel, Doppelbilder, Kopf- oder Augenschmerz gehören abgeklärt (Lehrbuchwissen: Muchnick, 2008). Für genau diese Übung gibt es keine Studie; ein Nutzen für Alltag, Sport oder Verkehr ist nicht belegt.',
      improved:
        'Die Größen werden in Zentimetern eingestellt (nach Kalibrierung des Bildschirms); die Punkte sind auf kleinen Bildschirmen nie größer als ein Teil des Felds, die Trefferfläche ist mindestens so groß wie eine Fingerkuppe. Ein Punkt kann erst getroffen werden, wenn er zu sehen war, die Punkte blenden weich ein, und ein zweiter Tipp direkt nach einem Treffer wird nicht als Fehltipp gezählt. Für die Hilfsperson gibt es eine große Taste „Gleichgewicht verloren“ (mindestens 56 Pixel, mit Text und Zeichen) und die Taste B; ein zweiter Tipp binnen einer halben Sekunde zählt nicht doppelt. Die Rückmeldung ist ruhig: ✓ und ✗ als Zeichen, ein gezählter Verlust wird nur kurz bestätigt – kein Flackern, kein Rotblitz. Gezeigt werden getroffene und verpasste Punkte, Fehltipps, Trefferquote, Reaktionszeit (Mittel, Median, Streuung), die gezählten Verluste und die Verluste pro Minute – nur Zählwerte, keine Messung von Gleichgewicht oder Haltung, ohne Noten, Normwerte und Ranglisten. Verlauf, Bestwert und „Letztes Mal“ vergleichen nur Durchläufe mit gleichen Einstellungen und gleicher Standposition.',
    },
    it: {
      trains:
        'Toccare i punti che compaiono in piedi (su due piedi, su un piede, in tandem o su una superficie instabile) – postura e vista insieme, un doppio compito. Una persona di aiuto tocca sullo schermo ogni perdita di equilibrio. Posizione, durata, dimensione dei punti, visibilità, pausa, zona e croce al centro li imposti tu.',
      daily:
        'Ovunque in piedi o camminando si debba badare a qualcosa e allo stesso tempo afferrarlo, per esempio toccare lo schermo del cellulare sul treno. Che l’esercizio aiuti non è dimostrato.',
      research:
        'Mantenere l’equilibrio richiede attenzione: una rassegna ha trovato, negli anziani sani e in quelli con disturbi dell’equilibrio, che questo fabbisogno contribuisce all’insicurezza; quanto sia grande dipende dalla difficoltà del compito posturale e dal tipo di secondo compito (Woollacott & Shumway-Cook, 2002). Il tempo per toccare un punto cresce con la distanza e diminuisce con la grandezza del bersaglio (Fitts, 1954; MacKenzie, 1992). Negli anziani si studia l’allenamento del doppio compito in piedi e camminando: in uno studio randomizzato con 23 anziani con disturbi dell’equilibrio (età media 74,8 anni; quattro settimane, tre volte 45 minuti) in tutti i gruppi sono migliorati il punteggio di equilibrio e la velocità del passo; sotto un compito mentale aggiuntivo si camminava però più veloce solo dopo l’allenamento del doppio compito, e il solo allenamento dell’equilibrio forse non si trasferiva ai doppi compiti (Silsupadol et al., 2009). Una panoramica di 18 rassegne su anziani cognitivamente sani ha trovato nel complesso effetti positivi dei programmi di doppio compito con movimento; per i videogiochi con movimento (exergames) solo sulla prestazione mentale, l’effetto sulle funzioni fisiche è controverso e sicurezza, trasferimento alla vita quotidiana e durata non sono chiari (Gallou-Guyot et al., 2020). Una rassegna Cochrane con 108 studi su 23.407 persone dai 60 anni in su che vivono a casa ha trovato che i programmi di movimento riducono il tasso di cadute, nel modo più netto gli esercizi di equilibrio e funzionali (rapporto di tassi 0,76; certezza delle prove alta) (Sherrington et al., 2019). Erano programmi seguiti da specialisti con movimenti reali, non un esercizio sullo schermo come questo; l’app non misura né l’equilibrio né la postura e per le persone sane un’utilità di questo esercizio non è dimostrata. Le perdite contate sono valori di conteggio della persona di aiuto: che cosa conta come perdita lo stabilite prima e il valore dipende dalla sua attenzione. Negli studi sugli esercizi sullo schermo i miglioramenti risultano nettamente maggiori quando la verifica somiglia al compito allenato – gran parte è abitudine al compito e al dispositivo (Guo et al., 2025); i touchscreen misurano il tempo di reazione sistematicamente un po’ in eccesso, in modo diverso a seconda del dispositivo (Pronk et al., 2020; i tablet non erano stati studiati). Per questo conta solo il confronto con te stesso, con la stessa posizione, la stessa persona di aiuto e le stesse impostazioni. La croce al centro è una richiesta, non un controllo: l’app non può misurare lo sguardo. Vertigini, visione doppia, mal di testa o dolore agli occhi vanno chiariti (manuale: Muchnick, 2008). Per questo esercizio non esiste uno studio; un’utilità per vita quotidiana, sport o traffico non è dimostrata.',
      improved:
        'Le dimensioni si impostano in centimetri (dopo la calibrazione dello schermo); sugli schermi piccoli i punti non sono mai più grandi di una parte del campo, l’area di tocco è almeno grande quanto la punta di un dito. Un punto può essere colpito solo dopo essere stato visibile, i punti compaiono dolcemente e un secondo tocco subito dopo un colpo a segno non viene contato come tocco a vuoto. Per la persona di aiuto c’è un grande tasto «Equilibrio perso» (almeno 56 pixel, con testo e simbolo) e il tasto B; un secondo tocco entro mezzo secondo non conta due volte. Il riscontro è sobrio: ✓ e ✗ come segni, una perdita contata viene solo brevemente confermata – nessuno sfarfallio, nessun lampo rosso. Vengono mostrati punti colpiti e mancati, tocchi a vuoto, percentuale di colpi, tempo di reazione (media, mediana, variazione), le perdite contate e le perdite al minuto – solo valori di conteggio, nessuna misurazione di equilibrio o postura, senza voti, valori di riferimento e classifiche. Andamento, record e «ultima volta» confrontano solo giri con le stesse impostazioni e la stessa posizione.',
    },
  },
  sources: [
    src('Woollacott & Shumway-Cook (2002). Attention and the control of posture and gait: a review of an emerging area of research. Gait & Posture', 'https://doi.org/10.1016/S0966-6362(01)00156-4'),
    src('Silsupadol, Shumway-Cook, Lugade, van Donkelaar, Chou, Mayr & Woollacott (2009). Effects of single-task versus dual-task training on balance performance in older adults: A double-blind, randomized controlled trial. Archives of Physical Medicine and Rehabilitation', 'https://doi.org/10.1016/j.apmr.2008.09.559'),
    src('Gallou-Guyot, Mandigout, Bherer & Perrochon (2020). Effects of exergames and cognitive-motor dual-task training on cognitive, physical and dual-task functions in cognitively healthy older adults: An overview. Ageing Research Reviews', 'https://doi.org/10.1016/j.arr.2020.101135'),
    src('Sherrington, Fairhall, Wallbank, Tiedemann, Michaleff, Howard et al. (2019). Exercise for preventing falls in older people living in the community. Cochrane Database of Systematic Reviews', 'https://doi.org/10.1002/14651858.CD012424.pub2'),
    src('Fitts (1954). The information capacity of the human motor system in controlling the amplitude of movement. Journal of Experimental Psychology', 'https://doi.org/10.1037/h0055392'),
    src('MacKenzie (1992). Fitts’ law as a research and design tool in human-computer interaction. Human-Computer Interaction', 'https://doi.org/10.1207/s15327051hci0701_3'),
    src('Pronk, Wiers, Molenkamp & Murre (2020). Mental chronometry in the pocket? Timing accuracy of web applications on touchscreen and keyboard devices. Behavior Research Methods', 'https://doi.org/10.3758/s13428-019-01321-2'),
    src('Guo, Yuan, Yang & Qiu (2025). Does the "learning effect" caused by digital devices exaggerate sports visual training outcomes? A systematic review and meta-analysis. Frontiers in Physiology', 'https://doi.org/10.3389/fphys.2025.1664572'),
    src('Muchnick (2008). Clinical Medicine in Optometric Practice, 2nd ed. Mosby/Elsevier, S. 6 und 28 (Warnzeichen mit Abklärungsbedarf)', 'https://openlibrary.org/isbn/9780323029612'),
  ],
};
