import type { ExerciseTexts } from '../../core/types';
import { ANA_FEEDBACK, ANA_PARAM_TEXTS, COMMON } from '../_shared/pruefung-texte';

// Funktionsübung der Marke „Labor“ nach dem Prinzip des klassischen Hess-Schirms (Rot-Grün-Brille), Texte in du-Form und
// einfacher Sprache. Regeln: kein Ersatz für die Untersuchung, keine Befunddeutung, keine Richtwerte, kein Wirkversprechen;
// gezeigt werden Übungswerte (Abstand zum Ziel in Grad, Fläche des Umrisses). Sicherheitshinweise siehe `_shared/pruefung-texte.ts`.

export const de: ExerciseTexts = {
  title: 'Hess-Schirm',
  tagline: 'Ein Auge sieht das Ziel, das andere den Zeiger: lege ihn aufs Ziel.',
  steps: ['Rot-Grün-Brille auf, Abstand wie kalibriert.', 'Fixiere das Ziel, lege den Zeiger darauf.', 'Mit „OK“ bestätigen, Punkt für Punkt.'],
  why:
    'Der Hess-Schirm ist ein klassisches Verfahren, mit dem Fachleute die Stellung der Augen in verschiedenen Blickrichtungen darstellen: Mit einer Rot-Grün-Brille sieht ein Auge nur das Ziel, das andere nur den Zeiger. Hier machst du eine digitale Näherung als Funktionsübung nach diesem Prinzip. Ein Auge sieht nur einen Zielpunkt des Rasters, das andere nur einen Zeiger, und du legst den Zeiger dorthin, wo er auf dem Ziel zu liegen scheint; danach tauschen die Augen die Rollen. Die App zeigt, wie weit dein Zeiger vom Ziel lag (Übungswerte in Grad), und deutet das nicht. Sie ersetzt keine Untersuchung, und die Werte sind nicht mit denen des klassischen Verfahrens austauschbar. Ob die Übung für Alltag oder Sehen etwas bringt, ist nicht belegt.',
  goodFor: ['Blickrichtungen', 'Zusammenspiel der Augen', 'Ruhiges Zielen'],
  captions: {
    look: 'Ein Auge sieht das Ziel, eins den Zeiger',
    place: 'Lege den Zeiger auf das Ziel.',
    ok: 'Bestätige mit „OK“.',
    chart: 'Zum Schluss siehst du alle Punkte.',
    done: 'Dann geht es zu den Werten.',
  },
  metrics: { placed: 'Gesetzte Punkte', ms_mean: 'Zeit je Punkt' },
  metricHints: {
    placed: 'Wie viele Punkte du gesetzt hast (Punkte je Durchgang mal Durchgänge). Das ist nur die Zahl deiner Eingaben, keine Leistung und kein Befund.',
    ms_mean: 'Mittlere Zeit vom Erscheinen eines Ziels bis zu „OK“. Sie enthält die Verzögerung des Touch-Sensors; vergleiche nur auf demselben Gerät.',
  },
  tips: {
    fixTarget: 'Schaue auf das Ziel, nicht auf den Zeiger. Den Zeiger nimmst du nur mit dem anderen Auge wahr; lege ihn zügig nach dem ersten Eindruck.',
    pause: 'Das volle Raster mit zwei Durchgängen dauert mehrere Minuten und ist anstrengend. Mache zwischen den Durchgängen eine Pause.',
    smallScreen: 'Der Bildschirm war zu klein für den eingestellten Winkel, das Raster wurde verkleinert. Der tatsächliche Winkel steht in den Werten.',
  },
  feedback: {
    ...ANA_FEEDBACK.de,
    progress: 'Punkt {n}/{total} · {pass}',
    hintPlace: 'Durchgang {pass}: Fixiere das Ziel. Lege den Zeiger dorthin, wo er auf dem Ziel zu liegen scheint (ziehen oder tippen), dann „OK“.',
    ok: 'OK',
    next: 'Weiter zu den Werten',
    chartHint: 'Soll grau · Durchgang A durchgezogen · Durchgang B gestrichelt',
    valuesTitle: 'Übungswerte (keine Deutung)',
    rowDev: 'Durchgang {pass}: mittlerer Abstand zum Ziel',
    devValue: '{v} °',
    devText: 'Fixiert hat das {eye} (Glas: {lens}), {n} Punkte',
    eyeLeft: 'linke Auge',
    eyeRight: 'rechte Auge',
    rowArea: 'Durchgang {pass}: Fläche des Umrisses',
    areaValue: '{v} % des Sollumrisses',
    areaText: 'Umriss der gesetzten äußeren Punkte',
    rowRatio: 'Flächen A im Verhältnis zu B',
    ratioValue: '{v}',
    gridTitle: 'Raster',
    rowEff: 'Größter Blickwinkel des Rasters',
    effValue: '{v} °',
    effText: 'bei {d} cm Abstand, projiziert auf eine ebene Fläche',
    clamped: 'wegen der Bildschirmgröße verkleinert (eingestellt: {set} °)',
    notCalibrated: 'nicht kalibriert: nur eine Schätzung',
    pointsRow: 'Punkte je Durchgang',
    pointsValue: '{n} (Durchgänge: {k})',
    valuesNote: `${COMMON.de.values} Der Umriss der gesetzten Punkte wird nur beschrieben.`,
    fewNote: COMMON.de.fewValues,
  },
  progression: [
    'Leichter: nur das innere Raster (9 Punkte), ein Durchgang, kleinerer Winkel (10 bis 15 Grad) und größere Ziele.',
    'Umfangreicher: volles Raster mit beiden Durchgängen und 30 Grad (braucht einen breiten Bildschirm); auf kleinen Bildschirmen wird das Raster verkleinert.',
    'Zum Vergleichen mit dir selbst: immer dieselben Einstellungen, derselbe Abstand und dieselbe Kopfhaltung.',
    'Die App zählt nur, was du eingibst; sie misst nicht, ob du wirklich auf das Ziel schaust.',
  ],
  cautions: [
    COMMON.de.principle,
    'Das ist eine Näherung: Zeigen mit Finger oder Maus statt mit einem Lichtzeiger, Rot-Grün-Farben auf einem Bildschirm, Projektion auf eine ebene Fläche. Die Werte sind nicht mit denen des klassischen Verfahrens austauschbar.',
    'Stelle den Bildschirm kalibriert und senkrecht auf Augenhöhe auf, halte den Kopf ruhig und mittig vor dem Raster (nur die Augen bewegen sich) und dunkle den Raum eher ab. Eine Maus oder ein Stift ist genauer als der Finger, der den Zeiger verdeckt.',
    COMMON.de.warn,
    COMMON.de.epilepsy,
    COMMON.de.colorBlind,
    COMMON.de.calm,
  ],
  params: {
    maxDeg: {
      label: 'Größter Blickwinkel',
      hint: 'Winkel des äußeren Rings in Grad. Der innere Ring liegt bei der Hälfte. Ist der Bildschirm zu klein, wird das Raster verkleinert (auf Tablets und Handys ist der erreichbare Winkel meist deutlich kleiner); im Ergebnis steht der tatsächliche Winkel.',
      short: '{v} °',
    },
    grid: {
      label: 'Raster',
      hint: 'Voll: 25 Punkte (9 innen, 16 außen). Nur innen: die 9 inneren Punkte, kürzer und für kleine Bildschirme geeignet.',
      options: { both: 'Voll (25 Punkte)', inner: 'Nur innen (9 Punkte)' },
    },
    passes: {
      label: 'Durchgänge',
      hint: 'Beide: Im zweiten Durchgang tauschen die Augen die Rollen (anderes Auge fixiert). Ein Durchgang: nur das Auge hinter dem roten Glas fixiert.',
      options: { both: 'Beide Augen als Fixierauge', one: 'Nur ein Durchgang' },
    },
    targetCm: { label: 'Größe des Zielpunkts', hint: 'Durchmesser des Zielpunkts in Zentimetern (nach Kalibrierung). Kleine Ziele erlauben ein genaueres Setzen.', short: '{v} cm' },
    markerCm: { label: 'Größe des Zeigers', hint: 'Durchmesser des Zeigers in Zentimetern.', short: '{v} cm' },
    ...ANA_PARAM_TEXTS.de,
  },
};

export const it: ExerciseTexts = {
  title: 'Schermo di Hess',
  tagline: 'Un occhio vede il bersaglio, l’altro il cursore: posalo sul bersaglio.',
  steps: ['Occhiali rosso-verdi, distanza come calibrata.', 'Fissa il bersaglio, posa il cursore sopra.', 'Conferma con «OK», punto dopo punto.'],
  why:
    'Lo schermo di Hess è un metodo classico con cui gli specialisti rappresentano la posizione degli occhi nelle diverse direzioni dello sguardo: con gli occhiali rosso-verdi un occhio vede solo il bersaglio, l’altro solo il cursore. Qui fai un’approssimazione digitale come esercizio funzionale secondo questo principio. Un occhio vede solo un punto bersaglio della griglia, l’altro solo un cursore, e tu posi il cursore dove ti sembra che sia sul bersaglio; poi gli occhi si scambiano i ruoli. L’app mostra quanto il tuo cursore era lontano dal bersaglio (valori dell’esercizio in gradi) e non lo interpreta. Non sostituisce una visita e i valori non sono intercambiabili con quelli del metodo classico. Che l’esercizio serva alla vita quotidiana o alla vista non è dimostrato.',
  goodFor: ['Direzioni dello sguardo', 'Lavoro di squadra degli occhi', 'Puntare con calma'],
  captions: {
    look: 'Un occhio il bersaglio, l’altro il cursore',
    place: 'Posa il cursore sul bersaglio.',
    ok: 'Conferma con «OK».',
    chart: 'Alla fine vedi tutti i punti.',
    done: 'Poi si passa ai valori.',
  },
  metrics: { placed: 'Punti posizionati', ms_mean: 'Tempo per punto' },
  metricHints: {
    placed: 'Quanti punti hai posizionato (punti per giro per numero di giri). È solo il numero delle tue immissioni, non una prestazione e non un referto.',
    ms_mean: 'Tempo medio da quando compare un bersaglio fino a «OK». Comprende il ritardo del sensore touch; confronta solo sullo stesso dispositivo.',
  },
  tips: {
    fixTarget: 'Guarda il bersaglio, non il cursore. Il cursore lo percepisci solo con l’altro occhio; posalo in fretta, secondo la prima impressione.',
    pause: 'La griglia completa con due giri dura diversi minuti ed è faticosa. Fai una pausa tra i giri.',
    smallScreen: 'Lo schermo era troppo piccolo per l’angolo impostato, la griglia è stata rimpicciolita. L’angolo effettivo è indicato nei valori.',
  },
  feedback: {
    ...ANA_FEEDBACK.it,
    progress: 'Punto {n}/{total} · {pass}',
    hintPlace: 'Giro {pass}: fissa il bersaglio. Posa il cursore dove ti sembra che sia sul bersaglio (trascina o tocca), poi «OK».',
    ok: 'OK',
    next: 'Avanti ai valori',
    chartHint: 'Obiettivo grigio · giro A linea continua · giro B tratteggiato',
    valuesTitle: 'Valori dell’esercizio (nessuna interpretazione)',
    rowDev: 'Giro {pass}: distanza media dal bersaglio',
    devValue: '{v} °',
    devText: 'Ha fissato l’{eye} (lente: {lens}), {n} punti',
    eyeLeft: 'occhio sinistro',
    eyeRight: 'occhio destro',
    rowArea: 'Giro {pass}: area del contorno',
    areaValue: '{v} % del contorno ideale',
    areaText: 'Contorno dei punti esterni posizionati',
    rowRatio: 'Area A rispetto a B',
    ratioValue: '{v}',
    gridTitle: 'Griglia',
    rowEff: 'Angolo massimo della griglia',
    effValue: '{v} °',
    effText: 'a {d} cm di distanza, proiettato su una superficie piana',
    clamped: 'rimpicciolita per le dimensioni dello schermo (impostato: {set} °)',
    notCalibrated: 'non calibrato: solo una stima',
    pointsRow: 'Punti per giro',
    pointsValue: '{n} (giri: {k})',
    valuesNote: `${COMMON.it.values} Il contorno dei punti posizionati viene solo descritto.`,
    fewNote: COMMON.it.fewValues,
  },
  progression: [
    'Più facile: solo la griglia interna (9 punti), un giro, angolo più piccolo (da 10 a 15 gradi) e bersagli più grandi.',
    'Più completo: griglia piena con entrambi i giri e 30 gradi (serve uno schermo largo); sugli schermi piccoli la griglia viene rimpicciolita.',
    'Per confrontarti con te stesso: sempre le stesse impostazioni, la stessa distanza e la stessa posizione della testa.',
    'L’app conta solo ciò che inserisci; non misura se guardi davvero il bersaglio.',
  ],
  cautions: [
    COMMON.it.principle,
    'È un’approssimazione: puntare con il dito o il mouse invece che con un puntatore luminoso, colori rosso-verdi su uno schermo, proiezione su una superficie piana. I valori non sono intercambiabili con quelli del metodo classico.',
    'Posiziona lo schermo calibrato e verticale all’altezza degli occhi, tieni la testa ferma e al centro davanti alla griglia (si muovono solo gli occhi) e oscura piuttosto la stanza. Un mouse o una penna sono più precisi del dito, che copre il cursore.',
    COMMON.it.warn,
    COMMON.it.epilepsy,
    COMMON.it.colorBlind,
    COMMON.it.calm,
  ],
  params: {
    maxDeg: {
      label: 'Angolo massimo dello sguardo',
      hint: 'Angolo dell’anello esterno in gradi. L’anello interno è a metà. Se lo schermo è troppo piccolo la griglia viene rimpicciolita (su tablet e cellulari l’angolo raggiungibile è di solito molto più piccolo); nel risultato è indicato l’angolo effettivo.',
      short: '{v} °',
    },
    grid: {
      label: 'Griglia',
      hint: 'Piena: 25 punti (9 interni, 16 esterni). Solo interna: i 9 punti interni, più breve e adatta agli schermi piccoli.',
      options: { both: 'Piena (25 punti)', inner: 'Solo interna (9 punti)' },
    },
    passes: {
      label: 'Giri',
      hint: 'Entrambi: nel secondo giro gli occhi si scambiano i ruoli (fissa l’altro occhio). Un giro: fissa solo l’occhio dietro la lente rossa.',
      options: { both: 'Entrambi gli occhi come occhio fissante', one: 'Un solo giro' },
    },
    targetCm: { label: 'Dimensione del punto bersaglio', hint: 'Diametro del punto bersaglio in centimetri (dopo la calibrazione). Bersagli piccoli permettono di posizionare con più precisione.', short: '{v} cm' },
    markerCm: { label: 'Dimensione del cursore', hint: 'Diametro del cursore in centimetri.', short: '{v} cm' },
    ...ANA_PARAM_TEXTS.it,
  },
};
