// Quellen: jede Angabe einzeln per Crossref (Autoren, Jahr, Titel, Zeitschrift, Band, Seiten) und PubMed (Abstract) geprüft
// (03.10.2026); die Aussagen im Text wurden mit dem Abstract abgeglichen:
// - Hess, Mansouri & Thompson (2010): Optom Vis Sci 87(9), 697–704; Abstract bestätigt: Fallserie mit drei Erwachsenen mit
//   Schielamblyopie, Kombination der Informationen beider Augen bei unterschiedlich kontrastreichen Reizen, später auch
//   unter natürlichen Bedingungen. Nur als erste kleine Fallserie wiedergegeben.
// - Li et al. (2013): Curr Biol 23(8), R308–R309; Abstract bestätigt: dichoptische Darbietung führte bei Erwachsenen mit
//   Amblyopie zu mehr Lernen als erzwungener Gebrauch des amblyopen Auges allein.
// - Holmes et al. (2016): JAMA Ophthalmol 134(12), 1391–1400; Abstract bestätigt: 385 Kinder (5 bis unter 13 Jahre), binokulares
//   Tablet-Spiel gegen Abkleben; die Nichtunterlegenheit ließ sich nicht zeigen, beide Gruppen verbesserten sich; nur 22 % der
//   Spielgruppe mit Protokolldaten erfüllten mehr als 75 % der verordneten Zeit.
// - Tsirlin et al. (2015): Invest Ophthalmol Vis Sci 56(6), 4061–4075; Abstract bestätigt: Metaanalyse von 24 Studien an
//   Erwachsenen; im Mittel Verbesserung der Sehschärfe bei einem Teil der Teilnehmenden, klinische Studien nötig.
// - Levi, Knill & Bavelier (2015): Vision Res 114, 17–30; Abstract bestätigt: bei Schielamblyopie schneidet dichoptisches
//   Training besser ab als einäugiges.
// - Birch (2012): J Opt Soc Am A 29(3), 313–320; Abstract bestätigt: bei Menschen europäischer Herkunft etwa 8 % der Männer und
//   etwa 0,4 % der Frauen.
// - Muchnick (2008), Lehrbuch (ISBN 9780323029612), S. 6 und 28: Warnzeichen mit Abklärungsbedarf (Doppelbilder, Schwindel,
//   Kopf- und Augenschmerz); Seitenangaben wie in den übrigen Übungen der App.
// Nicht aufgenommen (nicht belegt oder Wirkversprechen): jede Aussage zu Erfolgsquoten oder zu einem Nutzen für Menschen
// mit gesunder Binokularfunktion; dass die Übung eine Behandlung ersetzt; dass sie Unterdrückung abbaut. Als Erfahrungswissen
// der Praxis der funktionellen Optometrie ohne Quelle gekennzeichnet (nicht durch Studien belegt): Rot-Grün-Brillen für
// Aufgaben, bei denen beide Augen beteiligt bleiben müssen; gemeinsame Zeichen wie ein Rahmen halten die Bilder zusammen;
// aufhören, bevor Doppelbilder oder Beschwerden auftreten.
// Nicht bestätigt werden konnte: nichts Aufgenommenes; für genau diese Übung gibt es keine Studie.
import type { ScienceEntry } from '../../content/science';

const src = (label: string, url: string) => ({ label, url });

export const science: ScienceEntry = {
  id: 'labor-rot-gruen-lesen',
  evidence: 'weak',
  texts: {
    de: {
      trains:
        'Eine Folge aus Ziffern oder Buchstaben lesen, die teils rot, teils grün auf Schwarz steht, und sie der Reihe nach eintippen. Mit einer Rot-Grün-Brille sieht jedes Auge nur die Zeichen seiner Farbe hell; die ganze Folge liest nur, wer beide Augen zusammen nutzt. Länge, Zeichenart, Größe, Farbverteilung, Anzeigedauer, Farbtöne und Helligkeit stellst du selbst ein.',
      daily:
        'Beim Lesen, Schreiben und im Straßenverkehr nutzt man beide Augen zusammen. Ob diese Übung dabei hilft, ist nicht belegt.',
      research:
        'Aufgaben, bei denen jedem Auge ein anderes Bild gezeigt wird (dichoptisch), werden in der Forschung bei Amblyopie („Schwachsichtigkeit“) untersucht. In einer ersten kleinen Fallserie mit drei Erwachsenen mit Schielamblyopie ließen sich die Informationen beider Augen kombinieren, wenn die Reize für beide Augen unterschiedlich kontrastreich gezeigt wurden (Hess et al., 2010). Bei Erwachsenen mit Amblyopie führte dichoptisches Training im Labor zu mehr Lernen als der erzwungene Gebrauch des amblyopen Auges allein (Li et al., 2013). Eine Übersicht über 24 Studien an Erwachsenen (dichoptisches Training, Wahrnehmungslernen, Videospiele) fand im Mittel eine Verbesserung der Sehschärfe, aber nur bei einem Teil der Teilnehmenden, und verlangt klinische Studien (Tsirlin et al., 2015). Bei Schielamblyopie schnitt dichoptisches Training in einer Übersicht besser ab als einäugiges Training (Levi et al., 2015). Die Ergebnisse sind gemischt: In einer großen Studie mit 385 Kindern von 5 bis 12 Jahren ließ sich nicht zeigen, dass ein binokulares Tablet-Spiel dem Abkleben des besseren Auges mindestens gleichwertig ist; beide Gruppen verbesserten sich, und nur etwa jedes fünfte Kind spielte mehr als drei Viertel der verordneten Zeit (Holmes et al., 2016). Für Menschen mit gesunder Binokularfunktion gibt es keinen belegten Nutzen dieser Übung, und sie ist keine Behandlung und ersetzt keine. Die Rot-Grün-Brille trennt nur die beiden Bilder; die Zeichen liegen für beide Augen an derselben Stelle, auf einem flachen Bildschirm entsteht keine räumliche Tiefe, und Stereosehen wird hier nicht geübt. In der Praxis der funktionellen Optometrie werden Rot-Grün-Brillen für Aufgaben genutzt, bei denen beide Augen beteiligt bleiben müssen; gemeinsame Zeichen wie ein Rahmen halten die Bilder zusammen, und man hört auf, bevor Doppelbilder oder Beschwerden auftreten – als Erfahrungswissen beschrieben, nicht durch Studien belegt. Eine Rot-Grün-Farbsehschwäche haben bei Menschen europäischer Herkunft etwa 8 % der Männer und etwa 0,4 % der Frauen (Birch, 2012); für sie passt die Übung nicht. Doppelbilder, Schielen, Schwindel, Kopfschmerz oder Augenschmerz gehören abgeklärt (Lehrbuchwissen: Muchnick, 2008). Für genau diese Übung gibt es keine Studie; ein Nutzen für Alltag, Sport oder Verkehr ist nicht belegt.',
      improved:
        'Auf Schwarz stehen reines Rot (255, 0, 0) und reines Grün (0, 255, 0) – oder Cyan (0, 255, 255) –, wahlweise mit 80 bis 100 % Helligkeit; ein neutral hellgrauer Rahmen mit einem kleinen Kreuz wird von beiden Augen gesehen und hält die Bilder zusammen. Im Intro gibt es ein Prüfbild mit zwei Farbflächen, mit dem du die Brille prüfen kannst, ohne Wertung. Jede Folge enthält beide Farben (abwechselnd oder zufällig, mit mindestens einem Drittel je Farbe), und dieselbe Folge kommt nie zweimal hintereinander. Mit „?“ meldest du ein nicht gesehenes Zeichen; so bleibt die Stelle erhalten, und die Auswertung kann nach Farbe zählen, welche Zeichen fehlten oder verwechselt wurden. Ein Farbvergleich wird erst ab 20 Zeichen je Farbe gezeigt; die Zuordnung nach Auge hängt davon ab, dass du das linke Glas richtig einstellst, und ist nur ein Hinweis, kein Befund. Die App sagt nie, welches Auge schwächer ist, und misst nicht, ob die Brille getragen wird oder wohin du schaust. Die Zeichengröße wird in Zentimetern eingestellt (nach Kalibrierung des Bildschirms) und im Ergebnis mit dem Sehwinkel angegeben. Die Bedienung kommt ohne Farbe aus, die Rückmeldung bleibt ruhig: ✓ und ✗ als Zeichen, kein Flackern, kein Rotblitz. Weil das Ergebnis von den Einstellungen abhängt, vergleichen Verlauf, Bestwert und „Letztes Mal“ nur Durchläufe mit gleichen Einstellungen; gezeigt werden ganz richtige Folgen, richtige Zeichen und Eingabezeit – ohne Noten, Normwerte und Ranglisten.',
    },
    it: {
      trains:
        'Leggere una sequenza di cifre o lettere in parte rossa e in parte verde su nero e digitarla in ordine. Con gli occhiali rosso-verdi ogni occhio vede chiari solo i simboli del proprio colore; la sequenza intera la legge solo chi usa i due occhi insieme. Lunghezza, tipo di simboli, dimensione, distribuzione dei colori, durata di visualizzazione, tonalità e luminosità le imposti tu.',
      daily:
        'Nella lettura, nella scrittura e nel traffico si usano i due occhi insieme. Che l’esercizio aiuti in questo non è dimostrato.',
      research:
        'I compiti in cui a ogni occhio viene mostrata un’immagine diversa (dicoptici) sono studiati nella ricerca sull’ambliopia («occhio pigro»). In una prima piccola serie di casi con tre adulti con ambliopia strabica le informazioni dei due occhi potevano essere combinate quando gli stimoli per i due occhi venivano mostrati con contrasto diverso (Hess et al., 2010). Negli adulti con ambliopia l’allenamento dicoptico in laboratorio ha portato a più apprendimento rispetto all’uso forzato del solo occhio ambliope (Li et al., 2013). Una rassegna di 24 studi su adulti (allenamento dicoptico, apprendimento percettivo, videogiochi) ha trovato in media un miglioramento dell’acuità visiva, ma solo in una parte dei partecipanti, e richiede studi clinici (Tsirlin et al., 2015). Nell’ambliopia strabica l’allenamento dicoptico ha fatto meglio dell’allenamento monoculare in una rassegna (Levi et al., 2015). I risultati sono contrastanti: in un grande studio su 385 bambini da 5 a 12 anni non si è potuto dimostrare che un gioco binoculare su tablet sia almeno equivalente al bendaggio dell’occhio migliore; entrambi i gruppi sono migliorati e solo circa un bambino su cinque ha giocato più di tre quarti del tempo prescritto (Holmes et al., 2016). Per le persone con funzione binoculare sana non esiste un’utilità dimostrata di questo esercizio, ed esso non è un trattamento e non ne sostituisce nessuno. Gli occhiali rosso-verdi separano soltanto le due immagini; i simboli si trovano per i due occhi nello stesso punto, su uno schermo piatto non nasce profondità spaziale e qui non si esercita la visione stereoscopica. Nella pratica dell’optometria funzionale gli occhiali rosso-verdi si usano per compiti in cui devono restare coinvolti entrambi gli occhi; segni comuni come una cornice tengono insieme le immagini e ci si ferma prima che compaiano visione doppia o disturbi – descritto come sapere empirico, non dimostrato da studi. Un’alterazione della visione dei colori rosso-verde ce l’hanno, nelle persone di origine europea, circa l’8 % degli uomini e circa lo 0,4 % delle donne (Birch, 2012); per loro l’esercizio non è adatto. Visione doppia, strabismo, vertigini, mal di testa o dolore agli occhi vanno chiariti (manuale: Muchnick, 2008). Per questo esercizio non esiste uno studio; un’utilità per vita quotidiana, sport o traffico non è dimostrata.',
      improved:
        'Su nero ci sono rosso puro (255, 0, 0) e verde puro (0, 255, 0) – oppure ciano (0, 255, 255) –, a scelta con luminosità dall’80 al 100 %; una cornice grigio chiaro neutra con una piccola croce è vista da entrambi gli occhi e tiene insieme le immagini. Nell’introduzione c’è un’immagine di controllo con due superfici colorate con cui puoi controllare gli occhiali, senza valutazione. Ogni sequenza contiene entrambi i colori (alternati o a caso, con almeno un terzo per colore) e la stessa sequenza non compare mai due volte di seguito. Con “?” segnali un simbolo non visto; così il posto resta e la valutazione può contare per colore quali simboli mancavano o sono stati scambiati. Un confronto dei colori viene mostrato solo da 20 simboli per colore; l’assegnazione per occhio dipende dal fatto che tu imposti correttamente la lente sinistra ed è solo un’indicazione, non un referto. L’app non dice mai quale occhio è più debole e non misura se porti gli occhiali o dove guardi. La dimensione dei simboli si imposta in centimetri (dopo la calibrazione dello schermo) e nel risultato è indicata con l’angolo visivo. L’uso non dipende dal colore e la risposta resta sobria: ✓ e ✗ come segni, nessuno sfarfallio, nessun lampo rosso. Poiché il risultato dipende dalle impostazioni, andamento, record e “ultima volta” confrontano solo giri con le stesse impostazioni; si mostrano sequenze completamente giuste, simboli giusti e tempo di digitazione – senza voti, valori di riferimento e classifiche.',
    },
  },
  sources: [
    src('Hess, Mansouri & Thompson (2010). A binocular approach to treating amblyopia: antisuppression therapy. Optometry and Vision Science', 'https://doi.org/10.1097/OPX.0b013e3181ea18e9'),
    src('Li, Thompson, Deng, Chan, Yu & Hess (2013). Dichoptic training enables the adult amblyopic brain to learn. Current Biology', 'https://doi.org/10.1016/j.cub.2013.01.059'),
    src('Holmes, Manh, Lazar, Beck, Birch, Kraker et al. (2016). Effect of a binocular iPad game vs part-time patching in children aged 5 to 12 years with amblyopia: A randomized clinical trial. JAMA Ophthalmology', 'https://doi.org/10.1001/jamaophthalmol.2016.4262'),
    src('Tsirlin, Colpa, Goltz & Wong (2015). Behavioral training as new treatment for adult amblyopia: A meta-analysis and systematic review. Investigative Ophthalmology & Visual Science', 'https://doi.org/10.1167/iovs.15-16583'),
    src('Levi, Knill & Bavelier (2015). Stereopsis and amblyopia: A mini-review. Vision Research', 'https://doi.org/10.1016/j.visres.2015.01.002'),
    src('Birch (2012). Worldwide prevalence of red-green color deficiency. Journal of the Optical Society of America A', 'https://doi.org/10.1364/JOSAA.29.000313'),
    src('Muchnick (2008). Clinical Medicine in Optometric Practice, 2nd ed. Mosby/Elsevier, S. 6 und 28 (Warnzeichen mit Abklärungsbedarf)', 'https://openlibrary.org/isbn/9780323029612'),
  ],
};
