/** Deutsche Bezeichnungen für die Schlüssel des Übungskatalogs (docs/uebungskatalog/README.md) */
export const PROFIL_LABEL: Record<string, string> = {
  sehschaerfe_detail: 'Sehschärfe / feine Details',
  kontrast: 'Kontrast',
  farbunterscheidung: 'Farbunterscheidung',
  stereosehen: 'Stereosehen',
  peripheres_sehen: 'Peripheres Sehen',
  nutzbares_sehfeld: 'Nutzbares Sehfeld',
  blickfolge: 'Blickfolge',
  sakkaden: 'Blicksprünge (Sakkaden)',
  fixation: 'Fixation',
  bewegungswahrnehmung: 'Bewegungswahrnehmung',
  visuelle_suche: 'Visuelle Suche',
  visuelle_verarbeitungsgeschwindigkeit: 'Visuelles Verarbeitungstempo',
  zeitliche_aufloesung: 'Zeitliche Auflösung / Zeitgefühl',
  naharbeit_dauer: 'Naharbeit / Dauer',
  daueraufmerksamkeit: 'Daueraufmerksamkeit',
  selektive_aufmerksamkeit: 'Selektive Aufmerksamkeit',
  inhibition: 'Impulskontrolle (Hemmung)',
  geteilte_aufmerksamkeit: 'Geteilte Aufmerksamkeit',
  kognitive_flexibilitaet: 'Kognitive Flexibilität',
  arbeitsgedaechtnis: 'Arbeitsgedächtnis',
  kurzzeitgedaechtnis_verbal: 'Kurzzeitgedächtnis (verbal)',
  kurzzeitgedaechtnis_visuell_raeumlich: 'Kurzzeitgedächtnis (visuell-räumlich)',
  verarbeitungsgeschwindigkeit: 'Verarbeitungsgeschwindigkeit',
  antizipation: 'Antizipation',
  entscheidung_wahlreaktion: 'Entscheidung / Wahlreaktion',
  lesen_sprache: 'Lesen / Sprache',
  schlussfolgern: 'Schlussfolgern',
  einfache_reaktion: 'Einfache Reaktion',
  auge_hand_koordination: 'Auge-Hand-Koordination',
  zielbewegung_tempo: 'Zielbewegung (Tempo)',
  zielbewegung_praezision: 'Zielbewegung (Präzision)',
  kontinuierliche_steuerung: 'Kontinuierliches Nachführen',
  ruhige_hand: 'Ruhige Hand',
  fingergeschwindigkeit: 'Fingergeschwindigkeit',
  fingersequenz_bimanual: 'Fingerfolgen / beide Hände',
  ganzkoerper: 'Ganzkörperbewegung',
  gleichgewicht: 'Gleichgewicht',
  ausdauer_belastung: 'Ausdauer / Belastung',
};

export const BELASTUNG_LABEL: Record<string, string> = {
  zeitdruck: 'Zeitdruck',
  flimmern_lichtreize: 'Flimmern / Lichtreize',
  bewegungsreize_schwindel: 'Bewegungsreize (Schwindel)',
  koerperliche_belastung: 'Körperliche Belastung',
  sturzrisiko: 'Sturzrisiko',
  sprachabhaengigkeit: 'Sprachabhängigkeit',
};

export const VORSICHT_LABEL: Record<string, string> = {
  photosensitive_epilepsie: 'Photosensitive Epilepsie',
  migraene_lichtempfindlich: 'Migräne / Lichtempfindlichkeit',
  schwindel_vestibulaer: 'Schwindel (Gleichgewichtsorgan)',
  reisekrankheit: 'Reisekrankheit',
  nystagmus: 'Nystagmus',
  schielen_binokular: 'Schielen / Binokularsehen',
  amblyopie: 'Amblyopie',
  gesichtsfeldausfall: 'Gesichtsfeldausfall',
  sehbehinderung_niedriger_visus: 'Sehbehinderung / niedriger Visus',
  farbsehschwaeche: 'Farbsehschwäche',
  presbyopie_gleitsicht: 'Alterssichtigkeit / Gleitsicht',
  trockenes_auge_bildschirm: 'Trockenes Auge am Bildschirm',
  kopfschmerz_asthenopie: 'Kopfschmerz / Asthenopie',
  tremor_parkinson: 'Tremor / Parkinson',
  hand_arm_beschwerden: 'Hand-/Arm-Beschwerden',
  sturzgefahr: 'Sturzgefahr',
  herz_kreislauf: 'Herz-Kreislauf',
  gelenk_ruecken: 'Gelenke / Rücken',
  kognitive_einschraenkung: 'Kognitive Einschränkung',
  kinder_unter_6: 'Kinder unter 6',
  lese_rechtschreib_schwaeche: 'Lese-Rechtschreib-Schwäche',
  aufmerksamkeitsprobleme: 'Aufmerksamkeitsprobleme',
};

export const TABLET_LABEL: Record<string, string> = {
  ja: 'Tablet: geeignet',
  mit_anpassung: 'Tablet: mit Anpassung',
  nein: 'Tablet: nicht geeignet',
};

export const EINGABE_LABEL: Record<string, string> = {
  maus: 'Maus',
  touch: 'Touch',
  tastatur: 'Tastatur',
  touchpad: 'Touchpad',
  gamepad: 'Gamepad',
  kamera: 'Kamera',
  koerper_ohne_geraet: 'Körper (ohne Gerät)',
};

export const EVIDENZ_LABEL: Record<string, string> = {
  stark: 'stark',
  mittel: 'mittel',
  schwach: 'schwach',
  fehlend: 'fehlend',
  unklar: 'unklar',
};
