// Quellen: jede Angabe einzeln per Crossref (Autoren, Jahr, Titel, Zeitschrift, Band, Seiten) und, wo es ein Abstract gibt,
// über PubMed geprüft (03.10.2026); die Aussagen im Text wurden mit dem Abstract abgeglichen:
// - Fitts & Seeger (1953), J Exp Psychol 46(3), 199–210, und Simon (1969), J Exp Psychol 81(1), 174–176: Crossref bestätigt Titel,
//   Zeitschrift, Band, Seiten (PubMed ohne Abstract). Der Inhalt („passende räumliche Lage von Reiz und Antwort ist schneller“)
//   ist allgemein bekanntes Wissen der Reaktionsforschung und stützt sich hier auf Titel und Lehrbuchstand, nicht auf ein Abstract.
// - Okubo, Schoene & Lord (2017), Br J Sports Med 51(7), 586–593; Abstract bestätigt: sieben randomisierte Studien (n = 660) mit
//   Schritt-Training bei Älteren (ab 60), Rate Ratio der Stürze 0,48 (95 %-KI 0,36–0,65); verbessert waren einfache und
//   Wahl-Schrittreaktionszeit, Einbeinstand und Timed Up and Go, nicht die Kraft.
// - Lord & Fitzpatrick (2001), J Gerontol A 56(10), M627–M632; Abstract bestätigt: 477 Bewohner von Seniorenwohnanlagen (62–95 Jahre),
//   Wahl-Schrittaufgabe auf vier aufleuchtende Felder; Personen mit Stürzen in der Vorgeschichte brauchten im Mittel länger
//   (1322 ± 331 ms gegenüber 1168 ± 203 ms); die Zeit sagte Stürze unabhängig von anderen Maßen voraus.
// - Sherrington et al. (2019), Cochrane Database Syst Rev 2019(1), CD012424; Abstract bestätigt: 108 randomisierte Studien mit
//   23.407 Menschen ab 60 Jahren, die zu Hause leben; Bewegungsprogramme senken die Sturzrate (Rate Ratio 0,77), Gleichgewichts-
//   und Funktionsübungen allein 0,76 (hohe Sicherheit der Evidenz).
// - Pronk et al. (2020) und Guo et al. (2025): wie in den übrigen Labor-Übungen geprüft (Behav Res Methods 52, 1371–1382;
//   Front Physiol 16).
// - Muchnick (2008), Lehrbuch (ISBN 9780323029612), S. 6 und 28: Warnzeichen mit Abklärungsbedarf (Doppelbilder, Schwindel, Kopf-
//   und Augenschmerz); Seitenangaben wie in den übrigen Übungen der App.
// Nicht aufgenommen (nicht belegt oder Wirkversprechen): jede Aussage, dass diese Bildschirm-Übung Stürze verhindert, das Gleich-
// gewicht verbessert oder sich auf Alltag, Sport oder Verkehr überträgt; dass die Hilfsperson-Eingabe eine Messung der Bewegung ist;
// Normwerte für Reaktions- oder Schrittzeiten. Nicht bestätigt werden konnte: nichts Aufgenommenes; für genau diese Übung gibt es
// keine Studie.
import type { ScienceEntry } from '../../content/science';

const src = (label: string, url: string) => ({ label, url });

export const science: ScienceEntry = {
  id: 'labor-richtungen',
  evidence: 'weak',
  texts: {
    de: {
      trains:
        'Einen Pfeil schnell einer von vier oder acht Richtungen zuordnen und diese Richtung (oder die Gegenrichtung) angeben – per Berührung auf einem Richtungsfeld oder mit dem Körper, während eine Hilfsperson „Richtig“ oder „Falsch“ tippt. Anzahl, Richtungen, Aufgabe, Eingabe, Antwortzeit, Wartezeit und Pfeilgröße stellst du selbst ein.',
      daily:
        'Überall, wo man auf ein Zeichen hin schnell in eine bestimmte Richtung reagieren muss, zum Beispiel beim Ausweichen oder im Schrittwechsel. Ob die Übung dabei hilft, ist nicht belegt.',
      research:
        'Wie schnell man einen Reiz einer Antwort zuordnet, hängt davon ab, wie Reiz und Antwort räumlich zueinander liegen (Reiz-Reaktions-Kompatibilität; Fitts & Seeger, 1953; Simon, 1969). Passt die Lage zusammen, geht es schneller; bei der Gegenrichtung ist die Zuordnung umgekehrt, das kostet Zeit und führt öfter zu Fehlern. Das ist ein seit Langem beschriebenes Ergebnis der Reaktionsforschung (Lehrbuchwissen; zu den beiden Arbeiten liegt kein Abstract vor, bestätigt sind Titel und Zeitschrift). Bei älteren Menschen wird Schritt-Training untersucht, bei dem man auf Reize hin Schritte in eine Richtung macht: In einer Übersicht von sieben randomisierten Studien mit 660 Personen ab 60 Jahren gab es danach deutlich weniger Stürze (Rate Ratio 0,48), und einfache und Wahl-Schrittreaktionszeit, Einbeinstand und „Timed Up and Go“ waren verbessert (Okubo et al., 2017). In einer Studie mit 477 Bewohnern von Seniorenwohnanlagen (62 bis 95 Jahre) wurde eine Wahl-Schrittaufgabe – auf eines von vier aufleuchtenden Feldern treten – als Marker für das Sturzrisiko untersucht: Wer schon gestürzt war, brauchte im Mittel länger (1.322 gegenüber 1.168 ms), und die Zeit sagte Stürze unabhängig von anderen Maßen voraus (Lord & Fitzpatrick, 2001). Eine Cochrane-Übersicht mit 108 Studien an 23.407 Menschen ab 60 Jahren, die zu Hause leben, fand, dass Bewegungsprogramme die Sturzrate senken, am deutlichsten Gleichgewichts- und Funktionsübungen (Rate Ratio 0,76; hohe Sicherheit der Evidenz) (Sherrington et al., 2019). Das waren betreute Programme mit echten Schritten und Bewegungen, keine Bildschirmübung; diese Übung misst keine Schrittzeit und kein Sturzrisiko, und für gesunde Menschen ist ein Nutzen dieser Übung nicht belegt. Mit Hilfsperson zählt die App nur, was die Hilfsperson tippt; ob die Körperbewegung richtig war, kann sie nicht beurteilen, und die Zeit enthält deren Reaktion. In Studien zu Bildschirmübungen fallen Verbesserungen deutlich größer aus, wenn die Prüfung der geübten Aufgabe ähnelt – ein großer Teil ist Gewöhnung an Aufgabe und Gerät (Guo et al., 2025); Touchscreens messen die Reaktionszeit durchweg etwas zu lang, je nach Gerät unterschiedlich (Pronk et al., 2020; Tablets wurden dort nicht untersucht). Darum zählt nur der Vergleich mit dir selbst auf demselben Gerät, mit denselben Einstellungen und – bei Hilfsperson – derselben Person. Schwindel, Doppelbilder, Kopf- oder Augenschmerz gehören abgeklärt (Lehrbuchwissen: Muchnick, 2008). Für genau diese Übung gibt es keine Studie; ein Nutzen für Alltag, Sport oder Verkehr ist nicht belegt.',
      improved:
        'Der Pfeil kommt nach einer zufälligen Wartezeit; Tippen davor oder in den ersten 0,1 s danach zählt als „zu früh“ und nicht in der Wertung, ein zweiter Tipp direkt nach einer Antwort wird ignoriert, die Richtungen sind gleichmäßig verteilt. Das Richtungsfeld hat vier oder acht Tasten von mindestens 56 Pixeln, die sich nie überlappen; mit Hilfsperson gibt es große Tasten „Richtig“ und „Falsch“ (mit Text und Zeichen, nicht nur Farbe) und die Tastatur (Leertaste, X); dann gelten mindestens 1,5 s Antwortzeit. Die Pfeilgröße wird in Zentimetern eingestellt (nach Kalibrierung des Bildschirms) und auf kleinen Bildschirmen begrenzt. Die Rückmeldung ist ruhig: ✓ und ✗ als Zeichen, bei einem Fehler ein gestrichelter Ring um die richtige Taste, kein Flackern, kein Rotblitz. Gezeigt werden Genauigkeit, Reaktionszeit (Mittel, Median, Streuung), falsche, fehlende und zu frühe Antworten und die Zeit je Richtung – nur Zählwerte, keine Messung von Gleichgewicht oder Haltung, ohne Noten, Normwerte und Ranglisten. Verlauf, Bestwert und „Letztes Mal“ vergleichen nur Durchläufe mit gleichen Einstellungen.',
    },
    it: {
      trains:
        'Assegnare in fretta una freccia a una di quattro o otto direzioni e indicare quella direzione (o la direzione opposta) – con il tocco su un campo di direzioni oppure con il corpo, mentre una persona di aiuto tocca «Giusto» o «Sbagliato». Numero, direzioni, compito, input, tempo di risposta, attesa e dimensione della freccia le imposti tu.',
      daily:
        'Ovunque si debba reagire in fretta in una certa direzione a un segnale, per esempio nello schivare o nel cambio di passo. Che l’esercizio aiuti non è dimostrato.',
      research:
        'La rapidità con cui si assegna una risposta a uno stimolo dipende da come stimolo e risposta si trovano nello spazio l’uno rispetto all’altra (compatibilità stimolo-risposta; Fitts & Seeger, 1953; Simon, 1969). Se la posizione corrisponde si è più veloci; con la direzione opposta l’assegnazione è invertita, costa tempo e porta più spesso a errori. È un risultato descritto da tempo dalla ricerca sulla reazione (conoscenza da manuale; per i due lavori non esiste un abstract, sono confermati titolo e rivista). Negli anziani si studia l’allenamento al passo, in cui si fanno passi in una direzione in risposta a stimoli: in una rassegna di sette studi randomizzati con 660 persone dai 60 anni in su dopo ci sono state nettamente meno cadute (rapporto di tassi 0,48) e il tempo di reazione al passo semplice e a scelta, l’appoggio su una gamba e il «Timed Up and Go» erano migliorati (Okubo et al., 2017). In uno studio su 477 residenti in residenze per anziani (da 62 a 95 anni) si è studiato come indicatore del rischio di caduta un compito di passo a scelta – posare il piede su uno di quattro campi che si illuminano: chi era già caduto impiegava in media più tempo (1.322 contro 1.168 ms) e il tempo prediceva le cadute indipendentemente da altre misure (Lord & Fitzpatrick, 2001). Una rassegna Cochrane con 108 studi su 23.407 persone dai 60 anni in su che vivono a casa ha trovato che i programmi di movimento riducono il tasso di cadute, nel modo più netto gli esercizi di equilibrio e funzionali (rapporto di tassi 0,76; certezza delle prove alta) (Sherrington et al., 2019). Erano programmi seguiti da specialisti con passi e movimenti reali, non un esercizio sullo schermo; questo esercizio non misura i tempi di passo né il rischio di caduta e per le persone sane un’utilità di questo esercizio non è dimostrata. Con la persona di aiuto l’app conta solo ciò che questa tocca; se il movimento del corpo era giusto non può valutarlo e il tempo comprende la sua reazione. Negli studi sugli esercizi sullo schermo i miglioramenti risultano nettamente maggiori quando la verifica somiglia al compito allenato – gran parte è abitudine al compito e al dispositivo (Guo et al., 2025); i touchscreen misurano il tempo di reazione sistematicamente un po’ in eccesso, in modo diverso a seconda del dispositivo (Pronk et al., 2020; i tablet non erano stati studiati). Per questo conta solo il confronto con te stesso sullo stesso dispositivo, con le stesse impostazioni e – con la persona di aiuto – con la stessa persona. Vertigini, visione doppia, mal di testa o dolore agli occhi vanno chiariti (manuale: Muchnick, 2008). Per questo esercizio non esiste uno studio; un’utilità per vita quotidiana, sport o traffico non è dimostrata.',
      improved:
        'La freccia arriva dopo un’attesa casuale; toccare prima o nei primi 0,1 s dopo conta come «troppo presto» e non entra nella valutazione, un secondo tocco subito dopo una risposta viene ignorato, le direzioni sono distribuite in modo uniforme. Il campo delle direzioni ha quattro o otto tasti di almeno 56 pixel che non si sovrappongono mai; con la persona di aiuto ci sono grandi tasti «Giusto» e «Sbagliato» (con testo e simbolo, non solo colore) e la tastiera (barra spaziatrice, X); allora valgono almeno 1,5 s di tempo di risposta. La dimensione della freccia si imposta in centimetri (dopo la calibrazione dello schermo) e sugli schermi piccoli viene limitata. Il riscontro è sobrio: ✓ e ✗ come segni, in caso di errore un anello tratteggiato attorno al tasto giusto, nessuno sfarfallio, nessun lampo rosso. Vengono mostrati precisione, tempo di reazione (media, mediana, variazione), risposte sbagliate, mancanti e troppo precoci e il tempo per direzione – solo valori di conteggio, nessuna misurazione di equilibrio o postura, senza voti, valori di riferimento e classifiche. Andamento, record e «ultima volta» confrontano solo giri con le stesse impostazioni.',
    },
  },
  sources: [
    src('Fitts & Seeger (1953). S-R compatibility: Spatial characteristics of stimulus and response codes. Journal of Experimental Psychology', 'https://doi.org/10.1037/h0062827'),
    src('Simon (1969). Reactions toward the source of stimulation. Journal of Experimental Psychology', 'https://doi.org/10.1037/h0027448'),
    src('Okubo, Schoene & Lord (2017). Step training improves reaction time, gait and balance and reduces falls in older people: a systematic review and meta-analysis. British Journal of Sports Medicine', 'https://doi.org/10.1136/bjsports-2015-095452'),
    src('Lord & Fitzpatrick (2001). Choice stepping reaction time: A composite measure of falls risk in older people. The Journals of Gerontology Series A: Biological Sciences and Medical Sciences', 'https://doi.org/10.1093/gerona/56.10.m627'),
    src('Sherrington, Fairhall, Wallbank, Tiedemann, Michaleff, Howard et al. (2019). Exercise for preventing falls in older people living in the community. Cochrane Database of Systematic Reviews', 'https://doi.org/10.1002/14651858.CD012424.pub2'),
    src('Pronk, Wiers, Molenkamp & Murre (2020). Mental chronometry in the pocket? Timing accuracy of web applications on touchscreen and keyboard devices. Behavior Research Methods', 'https://doi.org/10.3758/s13428-019-01321-2'),
    src('Guo, Yuan, Yang & Qiu (2025). Does the "learning effect" caused by digital devices exaggerate sports visual training outcomes? A systematic review and meta-analysis. Frontiers in Physiology', 'https://doi.org/10.3389/fphys.2025.1664572'),
    src('Muchnick (2008). Clinical Medicine in Optometric Practice, 2nd ed. Mosby/Elsevier, S. 6 und 28 (Warnzeichen mit Abklärungsbedarf)', 'https://openlibrary.org/isbn/9780323029612'),
  ],
};
