import type { ExerciseTexts } from '../../core/types';
import { ANA_FEEDBACK, ANA_PARAM_TEXTS, COMMON } from '../_shared/pruefung-texte';

// Funktionsübung der Marke „Labor“ nach dem Prinzip einer Karte der Blickrichtungen (Rot-Grün-Brille), Texte in du-Form und
// einfacher Sprache. Regeln: kein Ersatz für die Untersuchung, keine Befunddeutung, keine Richtwerte, kein Wirkversprechen;
// gezeigt werden Übungswerte (gemeldete Richtungen, Verschiebung des zweiten Bildes in Δ). Hinweis: Die Brille trennt die Bilder,
// dabei können kurz Doppelbilder auftreten; neu aufgetretene Doppelbilder im Alltag gehören ärztlich abgeklärt.

export const de: ExerciseTexts = {
  title: 'Diplopie-Karte',
  tagline: 'Neun Blickrichtungen: ein Bild oder zwei? Dann gleiche aus.',
  steps: ['Rot-Grün-Brille auf, Kopf ruhig und mittig.', 'Schaue auf das Ziel: ein Bild oder zwei?', 'Bei zwei: schiebe das zweite auf das erste.'],
  why:
    'Eine Karte der Blickrichtungen hält fest, in welchen Richtungen zwei Bilder gesehen werden und wie weit sie auseinanderliegen. Hier machst du eine digitale Näherung als Funktionsübung nach diesem Prinzip: In neun Blickrichtungen (Mitte und acht Randpunkte) sieht ein Auge ein rotes Ziel, das andere ein Ziel in der zweiten Farbe. Du sagst, ob du ein Bild oder zwei siehst, und schiebst bei zwei Bildern das zweite auf das erste. Die App rechnet die Verschiebung in Prismendioptrien Δ um (1 Δ = 1 cm auf 1 m), zeigt sie als Übungswert samt einer Karte und deutet sie nicht. Sie ersetzt keine Untersuchung. Ob die Übung für Alltag oder Sehen etwas bringt, ist nicht belegt.',
  goodFor: ['Blickrichtungen', 'Ein Bild oder zwei', 'Genaues Hinschauen'],
  captions: {
    look: 'Ein Ziel: ein Bild oder zwei?',
    double: 'Bei zwei Bildern: zweites auf erstes.',
    align: 'Schiebe, bis du nur eines siehst.',
    chart: 'Die Karte zeigt alle Richtungen.',
    done: 'Danach siehst du die Werte.',
  },
  metrics: { positions: 'Geprüfte Blickrichtungen', double: 'Richtungen mit gemeldeten Doppelbildern', ms_mean: 'Zeit je Richtung' },
  metricHints: {
    positions: 'In wie vielen Blickrichtungen du geantwortet hast (höchstens neun). Das ist nur die Zahl deiner Eingaben, keine Leistung und kein Befund.',
    double: 'In wie vielen Richtungen du zwei Bilder gemeldet hast. Die App deutet das nicht.',
    ms_mean: 'Mittlere Zeit von der Anzeige eines Ziels bis zur Antwort. Sie enthält die Verzögerung des Touch-Sensors; vergleiche nur auf demselben Gerät.',
  },
  tips: {
    calm: 'Richte den Blick wirklich auf das Ziel, nicht auf das zweite Bild, und halte den Kopf ruhig. Ein kleiner Versatz wird leicht übersehen: schaue genau hin.',
    smallScreen: 'Der Bildschirm war zu klein für den eingestellten Winkel, die Richtungen wurden verkleinert. Der tatsächliche Winkel steht in den Werten.',
  },
  feedback: {
    ...ANA_FEEDBACK.de,
    progress: 'Richtung {n} / {total}',
    ask: 'Schaue auf das Ziel. Siehst du ein Bild oder zwei?',
    single: 'Ein Bild',
    double: 'Zwei Bilder',
    alignHint: 'Schiebe das zweite Bild (ziehen oder tippen) auf das erste, bis du nur noch eines siehst, dann „Deckungsgleich“.',
    matched: 'Deckungsgleich',
    chartHint: 'Karte: Kreis = ein Bild gemeldet, Quadrat = zwei Bilder (Linie zeigt den Versatz)',
    next: 'Weiter zu den Werten',
    valuesTitle: 'Übungswerte (keine Deutung)',
    rowDouble: 'Richtungen mit gemeldeten Doppelbildern',
    doubleValue: '{k} von {n}',
    rowPct: 'Anteil der Richtungen mit gemeldeten Doppelbildern',
    pctValue: '{v} %',
    rowMean: 'Mittlerer Versatz bei gemeldeten Doppelbildern',
    rowMax: 'Größter Versatz in einer Richtung',
    deltaValue: '{v} Δ',
    rowCenter: 'Mitte',
    centerYes: 'zwei Bilder gemeldet',
    centerNo: 'ein Bild gemeldet',
    centerNone: 'nicht geprüft',
    mapTitle: 'Karte der geprüften Richtungen',
    mapSingle: 'ein Bild',
    mapDouble: 'zwei Bilder: waagerecht {h} Δ, senkrecht {v} Δ',
    mapNote:
      'Waagerecht + heißt: Das zweite Bild wurde nach rechts geschoben, senkrecht +: nach oben. Das ist nur eine Beschreibung der Verschiebung, keine Deutung. 1 Δ ist 1 cm Ablenkung auf 1 m Entfernung; die Umrechnung nutzt den Abstand aus der Kalibrierung.',
    dirCenter: 'Mitte',
    dirUp: 'oben',
    dirDown: 'unten',
    dirLeft: 'links',
    dirRight: 'rechts',
    gridTitle: 'Blickwinkel',
    rowEff: 'Größter Blickwinkel der Randpunkte',
    effValue: '{v} °',
    effText: 'bei {d} cm Abstand, projiziert auf eine ebene Fläche',
    clamped: 'wegen der Bildschirmgröße verkleinert (eingestellt: {set} °)',
    notCalibrated: 'nicht kalibriert: nur eine Schätzung',
    valuesNote: COMMON.de.values,
    fewNote: COMMON.de.fewValues,
  },
  progression: [
    'Leichter: ein kleinerer Blickwinkel (10 Grad) und größere Ziele.',
    'Umfangreicher: ein größerer Blickwinkel (25 bis 30 Grad, braucht einen breiten Bildschirm) und kleinere Ziele; auf kleinen Bildschirmen wird der Winkel verkleinert.',
    'Zum Vergleichen mit dir selbst: dieselben Einstellungen, derselbe Abstand und dieselbe Kopfhaltung.',
    'Die App kann nicht prüfen, ob du wirklich in die jeweilige Richtung schaust.',
  ],
  cautions: [
    COMMON.de.principle,
    'Die Brille trennt die Bilder der beiden Augen; dabei können kurz Doppelbilder auftreten, das gehört zur Übung. Wenn das unangenehm ist, mache eine Pause oder höre auf. Doppelbilder, die im Alltag ohne Brille neu auftreten, gehören ärztlich abgeklärt.',
    'Das ist eine Näherung: Rot-Grün-Trennung auf einem Bildschirm, Projektion auf eine ebene Fläche, Einstellen per Finger oder Maus. Die Werte sind nicht mit denen anderer Verfahren austauschbar.',
    'Halte den Kopf ruhig und mittig vor dem Bildschirm (nur die Augen bewegen sich), kalibriere ihn und gib den echten Abstand an. Eine Maus oder ein Stift ist genauer als der Finger.',
    COMMON.de.warn,
    COMMON.de.epilepsy,
    COMMON.de.colorBlind,
    COMMON.de.calm,
  ],
  params: {
    gazeDeg: {
      label: 'Blickwinkel der Randpunkte',
      hint: 'Winkel der acht Randpunkte in Grad; die Mitte hat 0 Grad. Auf kleinen Bildschirmen wird er verkleinert (auf Tablets und Handys meist deutlich); im Ergebnis steht der tatsächliche Winkel.',
      short: '{v} °',
    },
    targetCm: { label: 'Größe des Ziels', hint: 'Durchmesser des Ziels in Zentimetern (nach Kalibrierung).', short: '{v} cm' },
    ...ANA_PARAM_TEXTS.de,
  },
};

export const it: ExerciseTexts = {
  title: 'Mappa della visione doppia',
  tagline: 'Nove direzioni dello sguardo: una immagine o due? Poi compensa.',
  steps: ['Occhiali rosso-verdi, testa ferma e al centro.', 'Guarda il bersaglio: una immagine o due?', 'Se due: sposta la seconda sulla prima.'],
  why:
    'Una mappa delle direzioni dello sguardo registra in quali direzioni si vedono due immagini e quanto sono distanti. Qui fai un’approssimazione digitale come esercizio funzionale secondo questo principio: in nove direzioni dello sguardo (centro e otto punti periferici) un occhio vede un bersaglio rosso, l’altro un bersaglio nel secondo colore. Dici se vedi una immagine o due e, con due immagini, sposti la seconda sulla prima. L’app converte lo spostamento in diottrie prismatiche Δ (1 Δ = 1 cm a 1 m), lo mostra come valore dell’esercizio insieme a una mappa e non lo interpreta. Non sostituisce una visita. Che l’esercizio serva alla vita quotidiana o alla vista non è dimostrato.',
  goodFor: ['Direzioni dello sguardo', 'Una immagine o due', 'Guardare con precisione'],
  captions: {
    look: 'Un bersaglio: una immagine o due?',
    double: 'Con due immagini: la seconda sulla prima.',
    align: 'Sposta finché ne vedi una sola.',
    chart: 'La mappa mostra tutte le direzioni.',
    done: 'Poi vedi i valori.',
  },
  metrics: { positions: 'Direzioni esaminate', double: 'Direzioni con visione doppia segnalata', ms_mean: 'Tempo per direzione' },
  metricHints: {
    positions: 'In quante direzioni dello sguardo hai risposto (al massimo nove). È solo il numero delle tue immissioni, non una prestazione e non un referto.',
    double: 'In quante direzioni hai segnalato due immagini. L’app non lo interpreta.',
    ms_mean: 'Tempo medio dalla visualizzazione di un bersaglio alla risposta. Comprende il ritardo del sensore touch; confronta solo sullo stesso dispositivo.',
  },
  tips: {
    calm: 'Dirigi davvero lo sguardo sul bersaglio, non sulla seconda immagine, e tieni ferma la testa. Un piccolo spostamento si trascura facilmente: guarda con attenzione.',
    smallScreen: 'Lo schermo era troppo piccolo per l’angolo impostato, le direzioni sono state rimpicciolite. L’angolo effettivo è indicato nei valori.',
  },
  feedback: {
    ...ANA_FEEDBACK.it,
    progress: 'Direzione {n} / {total}',
    ask: 'Guarda il bersaglio. Vedi una immagine o due?',
    single: 'Una immagine',
    double: 'Due immagini',
    alignHint: 'Sposta la seconda immagine (trascina o tocca) sulla prima finché ne vedi una sola, poi «Sovrapposte».',
    matched: 'Sovrapposte',
    chartHint: 'Mappa: cerchio = una immagine segnalata, quadrato = due immagini (la linea mostra lo spostamento)',
    next: 'Avanti ai valori',
    valuesTitle: 'Valori dell’esercizio (nessuna interpretazione)',
    rowDouble: 'Direzioni con visione doppia segnalata',
    doubleValue: '{k} su {n}',
    rowPct: 'Quota di direzioni con visione doppia segnalata',
    pctValue: '{v} %',
    rowMean: 'Spostamento medio con visione doppia segnalata',
    rowMax: 'Spostamento massimo in una direzione',
    deltaValue: '{v} Δ',
    rowCenter: 'Centro',
    centerYes: 'due immagini segnalate',
    centerNo: 'una immagine segnalata',
    centerNone: 'non esaminato',
    mapTitle: 'Mappa delle direzioni esaminate',
    mapSingle: 'una immagine',
    mapDouble: 'due immagini: orizzontale {h} Δ, verticale {v} Δ',
    mapNote:
      'Orizzontale + significa: la seconda immagine è stata spostata verso destra, verticale +: verso l’alto. È solo una descrizione dello spostamento, non un’interpretazione. 1 Δ è 1 cm di deviazione a 1 m di distanza; la conversione usa la distanza della calibrazione.',
    dirCenter: 'centro',
    dirUp: 'in alto',
    dirDown: 'in basso',
    dirLeft: 'a sinistra',
    dirRight: 'a destra',
    gridTitle: 'Angolo dello sguardo',
    rowEff: 'Angolo massimo dei punti periferici',
    effValue: '{v} °',
    effText: 'a {d} cm di distanza, proiettato su una superficie piana',
    clamped: 'rimpicciolito per le dimensioni dello schermo (impostato: {set} °)',
    notCalibrated: 'non calibrato: solo una stima',
    valuesNote: COMMON.it.values,
    fewNote: COMMON.it.fewValues,
  },
  progression: [
    'Più facile: un angolo più piccolo (10 gradi) e bersagli più grandi.',
    'Più completo: un angolo più grande (da 25 a 30 gradi, serve uno schermo largo) e bersagli più piccoli; sugli schermi piccoli l’angolo viene rimpicciolito.',
    'Per confrontarti con te stesso: le stesse impostazioni, la stessa distanza e la stessa posizione della testa.',
    'L’app non può verificare se guardi davvero nella rispettiva direzione.',
  ],
  cautions: [
    COMMON.it.principle,
    'Gli occhiali separano le immagini dei due occhi; per questo può comparire per breve tempo visione doppia, fa parte dell’esercizio. Se è sgradevole fai una pausa o smetti. La visione doppia che compare da poco nella vita quotidiana senza occhiali va chiarita dal medico.',
    'È un’approssimazione: separazione rosso-verde su uno schermo, proiezione su una superficie piana, regolazione con dito o mouse. I valori non sono intercambiabili con quelli di altri metodi.',
    'Tieni la testa ferma e al centro davanti allo schermo (si muovono solo gli occhi), calibralo e indica la distanza reale. Un mouse o una penna sono più precisi del dito.',
    COMMON.it.warn,
    COMMON.it.epilepsy,
    COMMON.it.colorBlind,
    COMMON.it.calm,
  ],
  params: {
    gazeDeg: {
      label: 'Angolo dei punti periferici',
      hint: 'Angolo degli otto punti periferici in gradi; il centro ha 0 gradi. Sugli schermi piccoli viene rimpicciolito (su tablet e cellulari di solito molto); nel risultato è indicato l’angolo effettivo.',
      short: '{v} °',
    },
    targetCm: { label: 'Dimensione del bersaglio', hint: 'Diametro del bersaglio in centimetri (dopo la calibrazione).', short: '{v} cm' },
    ...ANA_PARAM_TEXTS.it,
  },
};
