// Quellen: jede Angabe einzeln per Crossref (Autoren, Jahr, Titel, Zeitschrift, Band, Seiten) und PubMed (Abstract) geprüft
// (03.10.2026); die Aussagen im Text wurden mit dem Abstract abgeglichen. Es wurden nur Quellen aufgenommen, die schon für
// „Rot-Grün-Lesen“ geprüft sind und zum Thema Vergenz passen:
// - Convergence Insufficiency Treatment Trial Study Group (2008): Arch Ophthalmol 126(10), 1336–1349 (Crossref und PubMed;
//   Titel „Randomized clinical trial of treatments for symptomatic convergence insufficiency in children“); Abstract bestätigt:
//   221 Kinder (9 bis 17 Jahre) mit Beschwerden bei Konvergenzinsuffizienz, 12 Wochen, vier Behandlungen; Beschwerdewert, Nahpunkt
//   der Konvergenz und positive fusionale Vergenz besserten sich im Praxisprogramm mit Übungen zu Hause (OBVAT) am meisten;
//   „erfolgreich oder gebessert“: 73 % (OBVAT), 43 % (Bleistiftübungen zu Hause), 33 % (Computerprogramm zu Hause), 35 %
//   (Placebo-Programm in der Praxis).
// - Scheiman et al. (2005): Optom Vis Sci 82(7), 583–595 (Crossref und PubMed; Titel „A randomized clinical trial of vision
//   therapy/orthoptics versus pencil pushups for the treatment of convergence insufficiency in young adults“); Abstract
//   bestätigt: 46 Erwachsene (19 bis 30 Jahre), nur im Praxisprogramm deutliche Änderungen von Nahpunkt der Konvergenz und
//   positiver fusionaler Vergenz; die Beschwerden besserten sich in allen drei Gruppen, 58 % der Gruppe mit Praxisprogramm
//   hatten am Ende noch Beschwerden.
// - Birch (2012): J Opt Soc Am A 29(3), 313–320; Abstract bestätigt: bei Menschen europäischer Herkunft etwa 8 % der Männer und
//   etwa 0,4 % der Frauen.
// - Muchnick (2008), Lehrbuch (ISBN 9780323029612), S. 6 und 28: Warnzeichen mit Abklärungsbedarf (Doppelbilder, Schwindel,
//   Kopf- und Augenschmerz); Seitenangaben wie in den übrigen Übungen der App.
// Nicht aufgenommen (nicht belegt oder nicht geprüft): jede Aussage zu einer „Fusionsbreite“, zu Normwerten für Bruch- und
// Erholungspunkt, zu einem Nutzen für Menschen ohne Befund, zum Ersatz einer Untersuchung; Quellenangaben aus Unterlagen
// ohne Prüfung. Als Erfahrungswissen der Praxis der funktionellen Optometrie ohne Quelle gekennzeichnet (nicht durch
// Studien belegt): klein anfangen, entspannt schauen, beim ersten Anzeichen von Doppelbildern melden und aufhören, Pausen.
// Nicht bestätigt werden konnte: nichts Aufgenommenes; für genau diese Übung gibt es keine Studie.
import type { ScienceEntry } from '../../content/science';

const src = (label: string, url: string) => ({ label, url });

export const science: ScienceEntry = {
  id: 'labor-fusion',
  evidence: 'weak',
  texts: {
    de: {
      trains:
        'Mit einer Rot-Grün-Brille ein Ziel aus Kreisen ansehen, dessen zwei Bilder (je eines pro Auge) gegeneinander verschoben werden, und melden, wann es doppelt wird und wann es wieder einfach ist. Du stellst Richtung (Konvergenz oder Divergenz), Steuerung des Versatzes, Obergrenze, Wiederholungen, Zielgröße und Farben selbst ein; die Trainerin oder der Trainer kann den Versatz während der Übung verändern.',
      daily:
        'Beim Lesen, Schreiben, am Bildschirm und im Straßenverkehr arbeiten beide Augen zusammen. Ob diese Übung dabei hilft, ist nicht belegt.',
      research:
        'Das Zusammenspiel der Augen nach innen und außen (Vergenz) wird in Studien bei Konvergenzinsuffizienz untersucht, einer Schwäche, beim Nahsehen die Augen nach innen zu drehen. In einer Studie mit 221 Kindern von 9 bis 17 Jahren mit Beschwerden besserten sich nach 12 Wochen Beschwerden, Nahpunkt der Konvergenz und fusionale Vergenz im Programm in der Praxis mit Übungen zu Hause am meisten; erfolgreich oder gebessert waren 73 % in diesem Programm, 43 % bei Bleistiftübungen zu Hause, 33 % bei einem Computerprogramm zu Hause und 35 % bei einem Placebo-Programm in der Praxis (Convergence Insufficiency Treatment Trial Study Group, 2008). Bei 46 jungen Erwachsenen von 19 bis 30 Jahren änderten sich Nahpunkt und fusionale Vergenz nur im Programm in der Praxis deutlich; die Beschwerden besserten sich in allen drei Gruppen, und mehr als die Hälfte der Gruppe mit dem Praxisprogramm hatte am Ende noch Beschwerden (Scheiman et al., 2005). Das waren betreute Programme mit mehreren Aufgaben bei Menschen mit Beschwerden, keine Aufgabe wie diese am Bildschirm. Für Menschen ohne Befund ist für diese Übung kein Nutzen belegt, und sie ist keine Behandlung und keine Prismenmessung und ersetzt keine Untersuchung. Die Rot-Grün-Brille trennt nur die beiden Bilder; beide liegen auf dem Bildschirm in gleicher Entfernung, beim Scharfstellen bleiben die Augen auf der Entfernung des Bildschirms, und die Zeichnung ist flach. Der Versatz in Prismendioptrien wird mit der Sehentfernung aus der Kalibrierung berechnet; er ist so genau wie diese Eingabe und so fein einstellbar, wie der Bildschirm Pixel hat. In der Praxis der funktionellen Optometrie wird klein angefangen, entspannt geschaut, beim ersten Anzeichen von Doppelbildern gemeldet und aufgehört, bevor Beschwerden auftreten, und es werden Pausen gemacht – als Erfahrungswissen beschrieben, nicht durch Studien belegt. Eine Rot-Grün-Farbsehschwäche haben bei Menschen europäischer Herkunft etwa 8 % der Männer und etwa 0,4 % der Frauen (Birch, 2012); für sie passt die Übung nicht. Schielen, Doppelbilder, Schwindel, Kopfschmerz oder Augenschmerz gehören abgeklärt (Lehrbuchwissen: Muchnick, 2008); bei Schielen oder Doppelbildern wird deshalb nur nach Absprache mit der behandelnden Fachperson geübt. Für genau diese Übung gibt es keine Studie; ein Nutzen für Alltag, Sport oder Verkehr ist nicht belegt.',
      improved:
        'Auf Schwarz stehen reines Rot (255, 0, 0) und reines Grün (0, 255, 0) – wahlweise Cyan oder Blau (0, 160, 255; Rot-Cyan-Brillen funktionieren mit dem Farbpaar Rot–Blau) –, die Helligkeit jeder Farbe stellst du getrennt ein (30 bis 100 %, Schritte von 10 %). Im Intro gibt es ein Prüfbild Schritt für Schritt (Brille aufsetzen, je ein Auge zuhalten, Glas wählen, Helligkeit einstellen, ein Hinweis zu Geisterbildern); es bewertet nichts. Das Ziel besteht aus zwei Ringen und einem Mittelpunkt, jedes Auge sieht sein Bild in seiner Farbe; dazu je ein kurzer Kontrollstrich (rot oben, zweite Farbe unten), und mit den Tasten „Strich fehlt“ meldest du, welcher fehlte – ein Hinweis, kein Befund. Der Versatz der beiden Bilder wird in Prismendioptrien (Δ) geführt (1 Δ lenkt auf 1 m Entfernung um 1 cm ab), mit der Sehentfernung aus der Kalibrierung in Zentimeter und Pixel umgerechnet, und wächst je nach Einstellung mit Δ pro Sekunde, bis du „Doppelt“ meldest; danach schrumpft er, bis du „Wieder einfach“ meldest. Gespeichert wird immer der Wert, der in dem Moment angezeigt wird. Konvergenz (Bild rückt scheinbar näher) und Divergenz (rückt scheinbar weg) laufen im Wechsel oder einzeln; die Obergrenze liegt bei höchstens 40 Δ, auf kleinen Bildschirmen wird sie begrenzt, damit beide Bilder passen. In der Trainer- und Entwickler-Ansicht gibt es eine schmale Leiste am Rand außerhalb des Zielfelds, mit der der Versatz während der Übung verändert werden kann (höchstens 2 Δ je Tastendruck, die Anzeige gleitet weich, jede Änderung wird mit Zeitpunkt festgehalten und im Ergebnis ausgewiesen); bei „automatisch“ wird ein Zusatz daraufgelegt, bei „Trainer“ bestimmt allein der Regler den Versatz. Die Werte sind Übungswerte: keine Prismenmessung, kein Ersatz für eine Untersuchung, keine Normwerte, und ein höherer Wert ist nicht „besser“. Bei Schielen, Doppelbildern, Schwindel oder Kopfschmerz nur nach Absprache mit der behandelnden Fachperson oder gar nicht, bei Beschwerden sofort aufhören. Weil das Ergebnis von den Einstellungen abhängt, vergleichen Verlauf, Bestwert und „Letztes Mal“ nur Durchläufe mit gleichen Einstellungen (auch gleicher Steuerung und gleichem Startversatz); die Änderungen am Regler teilen den Verlauf nicht.',
    },
    it: {
      trains:
        'Guardare con gli occhiali rosso-verdi un bersaglio fatto di cerchi, le cui due immagini (una per occhio) vengono spostate l’una rispetto all’altra, e segnalare quando diventa doppio e quando torna singolo. Direzione (convergenza o divergenza), guida dello spostamento, limite, ripetizioni, dimensione del bersaglio e colori li imposti tu; il trainer può modificare lo spostamento durante l’esercizio.',
      daily:
        'Nella lettura, nella scrittura, davanti allo schermo e nel traffico i due occhi lavorano insieme. Che l’esercizio aiuti in questo non è dimostrato.',
      research:
        'La collaborazione degli occhi verso l’interno e verso l’esterno (vergenza) è studiata nell’insufficienza di convergenza, una debolezza nel ruotare gli occhi verso l’interno nella visione da vicino. In uno studio su 221 bambini da 9 a 17 anni con disturbi, dopo 12 settimane disturbi, punto prossimo di convergenza e vergenza fusionale sono migliorati di più con il programma in studio con esercizi a casa; successo o miglioramento nel 73 % con questo programma, nel 43 % con gli esercizi con la matita a casa, nel 33 % con un programma al computer a casa e nel 35 % con un programma placebo in studio (Convergence Insufficiency Treatment Trial Study Group, 2008). In 46 giovani adulti da 19 a 30 anni punto prossimo e vergenza fusionale sono cambiati in modo netto solo con il programma in studio; i disturbi sono migliorati in tutti e tre i gruppi e più della metà del gruppo con il programma in studio aveva ancora disturbi alla fine (Scheiman et al., 2005). Erano programmi seguiti da specialisti con più compiti, in persone con disturbi, non un compito come questo sullo schermo. Per le persone senza disturbi non è dimostrata alcuna utilità di questo esercizio, che non è un trattamento né una misurazione prismatica e non sostituisce una visita. Gli occhiali rosso-verdi separano soltanto le due immagini; entrambe si trovano sullo schermo alla stessa distanza, nella messa a fuoco gli occhi restano alla distanza dello schermo e il disegno è piatto. Lo spostamento in diottrie prismatiche viene calcolato con la distanza visiva della calibrazione; è preciso quanto questa indicazione e regolabile tanto finemente quanto lo schermo ha pixel. Nella pratica dell’optometria funzionale si inizia in piccolo, si guarda con calma, si segnala al primo segno di immagini doppie e ci si ferma prima che compaiano disturbi, e si fanno pause – descritto come sapere empirico, non dimostrato da studi. Un’alterazione della visione dei colori rosso-verde ce l’hanno, nelle persone di origine europea, circa l’8 % degli uomini e circa lo 0,4 % delle donne (Birch, 2012); per loro l’esercizio non è adatto. Strabismo, visione doppia, vertigini, mal di testa o dolore agli occhi vanno chiariti (manuale: Muchnick, 2008); in caso di strabismo o visione doppia ci si esercita perciò solo dopo accordo con lo specialista che segue la persona. Per questo esercizio non esiste uno studio; un’utilità per vita quotidiana, sport o traffico non è dimostrata.',
      improved:
        'Su nero ci sono rosso puro (255, 0, 0) e verde puro (0, 255, 0) – a scelta ciano o blu (0, 160, 255; gli occhiali rosso-ciano funzionano con la coppia rosso–blu) –, la luminosità di ogni colore la imposti separatamente (dal 30 al 100 %, a passi del 10 %). Nell’introduzione c’è un’immagine di controllo passo dopo passo (mettere gli occhiali, coprire un occhio alla volta, scegliere la lente, regolare la luminosità, un’indicazione sulle immagini fantasma); non valuta nulla. Il bersaglio è fatto di due anelli e un punto centrale, ogni occhio vede la propria immagine nel proprio colore; in più un breve trattino di controllo ciascuno (rosso sopra, secondo colore sotto), e con i tasti “Manca il trattino” segnali quale mancava – un’indicazione, non un referto. Lo spostamento delle due immagini è guidato in diottrie prismatiche (Δ) (1 Δ devia di 1 cm a 1 m di distanza), convertito in centimetri e pixel con la distanza visiva della calibrazione, e cresce a seconda dell’impostazione con Δ al secondo finché segnali “Doppia”; poi diminuisce finché segnali “Di nuovo singola”. Si salva sempre il valore mostrato in quel momento. Convergenza (l’immagine sembra avvicinarsi) e divergenza (sembra allontanarsi) si alternano o vanno da sole; il limite è al massimo 40 Δ, sugli schermi piccoli viene ristretto perché entrambe le immagini entrino. Nella vista del trainer e dello sviluppatore c’è una stretta barra al margine, fuori dal campo del bersaglio, con cui lo spostamento può essere cambiato durante l’esercizio (al massimo 2 Δ per tasto, la visualizzazione scorre dolcemente, ogni modifica viene registrata con l’orario e riportata nel risultato); con “automatica” si aggiunge un valore, con “Trainer” decide solo il regolatore. I valori sono valori di esercizio: non una misurazione prismatica, non sostituiscono una visita, nessun valore di riferimento, e un valore più alto non è “migliore”. In caso di strabismo, visione doppia, vertigini o mal di testa solo dopo accordo con lo specialista che ti segue, oppure per niente; in caso di disturbi smetti subito. Poiché il risultato dipende dalle impostazioni, andamento, record e “ultima volta” confrontano solo giri con le stesse impostazioni (anche stessa guida e stesso spostamento iniziale); le modifiche al regolatore non dividono l’andamento.',
    },
  },
  sources: [
    src('Convergence Insufficiency Treatment Trial Study Group (2008). Randomized clinical trial of treatments for symptomatic convergence insufficiency in children. Archives of Ophthalmology', 'https://doi.org/10.1001/archopht.126.10.1336'),
    src('Scheiman, Mitchell, Cotter, Kulp, Cooper, Rouse et al. (2005). A randomized clinical trial of vision therapy/orthoptics versus pencil pushups for the treatment of convergence insufficiency in young adults. Optometry and Vision Science', 'https://doi.org/10.1097/01.opx.0000171331.36871.2f'),
    src('Birch (2012). Worldwide prevalence of red-green color deficiency. Journal of the Optical Society of America A', 'https://doi.org/10.1364/JOSAA.29.000313'),
    src('Muchnick (2008). Clinical Medicine in Optometric Practice, 2nd ed. Mosby/Elsevier, S. 6 und 28 (Warnzeichen mit Abklärungsbedarf)', 'https://openlibrary.org/isbn/9780323029612'),
  ],
};
