import type { ExerciseTexts } from '../../core/types';
import { anaglyphFeedbackDe, anaglyphFeedbackIt, anaglyphParamsDe, anaglyphParamsIt } from '../_shared/anaglyph-texts';

// Eigene Übung der Marke „Labor“ (Fusion mit Rot-Grün-/Rot-Cyan-Brille), Texte in du-Form und einfacher Sprache.
// Formulierungsregeln: nur beschreiben, was man in der Übung tut; die Werte sind Übungswerte („Wert, bei dem du Doppelbilder
// gemeldet hast“): keine Prismenmessung, keine Prüfung, keine Aussage über eine Fusionsbreite, keine Normwerte, kein Wirk-
// oder Heilversprechen, Vergleich nur mit sich selbst auf diesem Gerät. Die App weiß nicht, ob du wirklich doppelt siehst.
// Sicherheitshinweise (Pflicht): Schielen, Doppelbilder, Schwindel, Kopfschmerz nur nach Absprache mit der behandelnden
// Fachperson, sonst aufhören (Muchnick, 2008, S. 6 und 28); Rot-Grün-Farbsehschwäche (Birch, 2012); Raum abdunkeln, Überbrille.
// Erfahrungswissen der funktionellen Optometrie (klein anfangen, entspannt schauen, vor Doppelbildern aufhören, Pausen) steht
// ohne Quelle und ist als „nicht durch Studien belegt“ gekennzeichnet.

export const de: ExerciseTexts = {
  title: 'Fusion – Bilder verschmelzen',
  tagline: 'Halte mit Rot-Grün-Brille ein Bild einfach, während der Versatz wächst.',
  steps: [
    'Rot-Grün-Brille auf, Raum eher dunkel, Abstand etwa 40 cm.',
    'Halte das Bild ruhig. Wird es doppelt: „Doppelt“ tippen.',
    'Wird es wieder einfach: „Wieder einfach“ tippen.',
  ],
  why:
    'Hier siehst du ein Ziel aus Kreisen, das jedem Auge in seiner Farbe gezeigt wird. Der Versatz der beiden Bilder wächst langsam, bis du „Doppelt“ meldest, und schrumpft dann, bis du „Wieder einfach“ meldest. Konvergenz heißt: Das Bild rückt scheinbar näher, die Augen drehen nach innen; Divergenz: Es rückt scheinbar weg, die Augen drehen nach außen. Der Versatz steht in Prismendioptrien (Δ): 1 Δ lenkt auf 1 m Entfernung um 1 cm ab. Die Werte sind Übungswerte, die du nur mit dir selbst vergleichst – keine Prismenmessung und kein Ersatz für eine Untersuchung. Ob das Üben das Zusammenspiel der Augen im Alltag, im Sport oder im Verkehr verbessert, ist nicht belegt.',
  goodFor: ['Zusammenspiel der Augen', 'Ruhiger Blick', 'Aufmerksamkeit'],
  captions: {
    look: 'Ruhig auf das Ziel schauen',
    strokes: 'Fehlt ein Strich? Diese Taste',
    up: 'Wird es doppelt? Tippe „Doppelt“',
    down: 'Wieder einfach? Tippe „Wieder einfach“',
  },
  metrics: {
    break_mean: 'Doppelt gemeldet bei (Mittel)',
    break_conv: 'Konvergenz: doppelt gemeldet bei',
    rec_conv: 'Konvergenz: wieder einfach gemeldet bei',
    break_div: 'Divergenz: doppelt gemeldet bei',
    rec_div: 'Divergenz: wieder einfach gemeldet bei',
    trials: 'Abgeschlossene Durchgänge',
    capped: 'Durchgänge bis zur Obergrenze, ohne „Doppelt“',
    no_recovery: 'Durchgänge ohne „Wieder einfach“',
    control: 'Versatzsteuerung',
    max: 'Obergrenze des Versatzes',
    target: 'Zieldurchmesser',
  },
  metricHints: {
    break_mean:
      'Mittel der Werte (in Prismendioptrien Δ), bei denen du „Doppelt“ gemeldet hast. Durchgänge, die bis zur Obergrenze liefen, ohne dass du etwas gemeldet hast, zählen hier nicht mit. Das ist ein Übungswert zum Vergleich mit dir selbst bei gleichen Einstellungen: ein höherer Wert ist nicht „besser“, und es ist keine Prismenmessung.',
    break_conv: 'Mittel der Werte, bei denen du bei Konvergenz (Bild rückt scheinbar näher) „Doppelt“ gemeldet hast, in Δ.',
    rec_conv: 'Mittel der Werte, bei denen du bei Konvergenz nach dem „Doppelt“ „Wieder einfach“ gemeldet hast, in Δ.',
    break_div: 'Mittel der Werte, bei denen du bei Divergenz (Bild rückt scheinbar weg) „Doppelt“ gemeldet hast, in Δ.',
    rec_div: 'Mittel der Werte, bei denen du bei Divergenz nach dem „Doppelt“ „Wieder einfach“ gemeldet hast, in Δ.',
    trials: 'Wie viele Durchgänge (je ein Anstieg und ein Rückgang des Versatzes) abgeschlossen wurden.',
    capped: 'Durchgänge, in denen der Versatz die Obergrenze erreichte, ohne dass du „Doppelt“ gemeldet hast. Ihr Wert ist nach oben abgeschnitten und zählt deshalb nicht in die Mittelwerte.',
    no_recovery: 'Durchgänge, in denen der Versatz wieder auf 0 kam, ohne dass du „Wieder einfach“ gemeldet hast. Sie zählen nicht in die Mittelwerte der Rückkehr. Auch Brille, Bildschirmfarben, Müdigkeit und Bedienung spielen eine Rolle.',
    control: 'Wie der Versatz geführt wurde: automatisch mit Δ pro Sekunde, oder nur durch den Trainer-Regler.',
    max: 'Höchster Versatz in Δ, in cm und Pixeln, umgerechnet mit dem Abstand aus der Kalibrierung. Auf kleinen Bildschirmen kann er begrenzt sein, damit beide Bilder auf den Bildschirm passen.',
    target: 'Durchmesser des Ziels in Zentimetern. Er ist kleiner als eingestellt, wenn das Ziel sonst nicht auf den Bildschirm passt.',
  },
  tips: {
    few: 'Es wurde kein Durchgang abgeschlossen. Prüfe das Prüfbild für die Brille und starte mit einem großen Ziel und langsamer Änderung.',
    noRecovery:
      'Bei vielen Durchgängen kam das Bild nicht mehr zusammen, bevor der Versatz auf 0 war. Prüfe Brille, Raumlicht und Helligkeit im Prüfbild. Siehst du immer wieder Doppelbilder: nicht allein weiterüben, sondern bei deiner Optikerin, deinem Optiker oder bei einer Augenärztin, einem Augenarzt abklären lassen.',
    capped: 'Bei vielen Durchgängen hast du bis zur Obergrenze nichts gemeldet. Prüfe, ob du „Doppelt“ ehrlich beim ersten Anzeichen tippst, und ob Brille und Prüfbild stimmen. Die Obergrenze stellst du in den Einstellungen ein.',
    strokes: 'Du hast gemeldet, dass ein Strich fehlte. Das ist nur ein Hinweis: Auch Brille, Bildschirmfarben und Helligkeit spielen eine Rolle. Prüfe zuerst das Prüfbild; bleibt es über mehrere Durchläufe so, sprich mit deiner Optikerin oder deinem Optiker.',
    compare: 'Vergleiche diesen Durchlauf nur mit Durchläufen mit denselben Einstellungen – auf diesem Gerät, bei ähnlichem Licht und gleichem Abstand.',
  },
  feedback: {
    ...anaglyphFeedbackDe,
    msgReady: 'Halte das Bild ruhig und einfach …',
    msgUp: 'Sobald das Bild doppelt wird: „Doppelt“ tippen',
    msgDown: 'Sobald das Bild wieder einfach ist: „Wieder einfach“ tippen',
    doubleBtn: 'Doppelt',
    singleBtn: 'Wieder einfach',
    dirConvergence: 'Konvergenz',
    dirDivergence: 'Divergenz',
    hudLabel: '{dir} · {n} / {total}',
    none: '–',
    dirTitle: 'Nach Richtung',
    dirLabel: '{dir} (doppelt · wieder einfach)',
    dirValue: '{b}\u00A0·\u00A0{r}\u00A0Δ',
    dirCount: '{n} Durchgänge, {c} bis zur Obergrenze, {x} ohne „Wieder einfach“',
    dirNote: 'Das sind Mittel der Werte, bei denen du etwas gemeldet hast – Übungswerte, keine Prismenmessung. Eine Zeile ohne Zahl heißt: dazu gab es keine Meldung.',
    runsTitle: 'Durchgänge',
    runsNote: 'Durchgänge bis zur Obergrenze und ohne „Wieder einfach“ zählen nicht in die Mittelwerte.',
    strokeTitle: 'Kontrollstriche (Hinweis, kein Befund)',
    strokeRow: 'Strich in {c} fehlte',
    strokeValue: '{k}-mal gemeldet',
    strokeNote:
      'Gezählt wird nur, wie oft du gemeldet hast, dass ein Strich fehlte. Das ist ein Hinweis, kein Befund: Auch Brille, Bildschirmfarben und Helligkeit spielen eine Rolle. Fehlt immer derselbe Strich, sprich mit deiner Optikerin, deinem Optiker oder bei einer Augenärztin, einem Augenarzt.',
    settingsTitle: 'Einstellungen und Umrechnung',
    controlAuto: '{r} Δ pro Sekunde',
    controlTrainer: 'nur der Trainer-Regler (Start {s} Δ)',
    controlLive: 'automatisch; der Trainer-Regler legt einen Zusatz darauf',
    controlFallback: 'Trainer-Regler nicht verfügbar: Der Versatz lief automatisch',
    pdValue: 'bis {pd} Δ',
    cmValue: '{cm} cm',
    maxDetail: 'etwa {cm} cm (≈ {px} px) zwischen den Bildern bei {d} cm Abstand',
    maxLimited: 'auf diesem Bildschirm auf {pd} Δ begrenzt, damit beide Bilder passen',
    targetLimited: 'Auf diesem Bildschirm begrenzt',
    notCalibrated: 'nicht kalibriert: Schätzung',
    valuesNote:
      'Alle Werte sind Übungswerte: keine Prismenmessung und kein Ersatz für eine Untersuchung. Sie gelten nur für diesen Bildschirm, diese Kalibrierung und diesen Abstand. Vergleiche sie nur mit deinen eigenen Werten.',
    liveTitle: 'Trainer-Regler (während der Übung)',
    liveCount: 'Versatz vom Trainer verändert',
    liveCountValue: '{n}-mal, zuletzt {v} {u} (Versatz danach {t} {u})',
    liveEntry: 'Durchgang {k}, {time}',
    liveEntryValue: '{v} {u} (Versatz danach {t} {u})',
    liveMore: '… und {n} weitere Änderungen',
    liveNote:
      'Der Regler gilt nur für diesen Durchlauf und verändert keine Einstellungen. Bei „automatisch“ ist der Versatz der automatische Wert plus der Zusatz (der Zusatz beginnt in jedem Durchgang bei 0); bei „Trainer“ bestimmt allein der Regler den Versatz. Gemeldet wurde immer der Wert, der in dem Moment angezeigt wurde.',
  },
  progression: [
    'Leichter: langsamere Änderung (0,5 bis 1 Δ pro Sekunde), ein größeres Ziel (8 bis 10 cm), nur eine Richtung, kleine Obergrenze.',
    'Schwerer: schnellere Änderung, kleineres Ziel (3 bis 4 cm), beide Richtungen im Wechsel, mehr Wiederholungen. Ändere immer nur eine Einstellung auf einmal.',
    'Tippe „Doppelt“ ehrlich beim ersten Anzeichen von Doppelbildern, nicht erst, wenn sie weit auseinanderliegen. Das ist Erfahrungswissen der Praxis der funktionellen Optometrie, nicht durch Studien belegt.',
    'Konvergenz und Divergenz fallen oft unterschiedlich aus; vergleiche jede Richtung nur mit sich selbst. Vergleiche nur Durchläufe mit denselben Einstellungen, auf demselben Gerät und bei gleichem Abstand.',
    'Unsere Faustregel (keine Vorgabe aus der Forschung): Fängst du an, beginne mit kleiner Obergrenze und langsamer Änderung, mach Pausen und höre auf, bevor das Bild doppelt bleibt oder Beschwerden auftreten.',
    'Versatzsteuerung „Trainer“: Der Versatz ändert sich nur durch den Trainer-Regler (Trainer- oder Entwickler-Ansicht), beginnend beim Startversatz. Ohne Regler läuft die Übung automatisch.',
  ],
  cautions: [
    'Rot-Grün-Farbsehschwäche: Etwa 8 von 100 Männern und 4 von 1000 Frauen europäischer Herkunft haben sie (Birch, 2012). Dann werden Rot und Grün falsch getrennt, und die Übung ist für dich nicht geeignet. Auch beim Farbpaar Rot–Blau prüfst du im Prüfbild, ob du die Farben trennen kannst.',
    'Bei Schielen, Doppelbildern, Schwindel oder Kopfschmerz: nur nach Absprache mit der behandelnden Fachperson üben, sonst gar nicht. Treten Doppelbilder, Schwindel, Kopf- oder Augenschmerz auf, sofort aufhören und abklären lassen (Muchnick, 2008, S. 6 und 28).',
    'Das „Doppelt“ gehört zur Übung: Du meldest es beim ersten Anzeichen. Bleibt das Bild danach doppelt oder werden Beschwerden stärker, höre auf und mach Pause.',
    'Halte jeden Durchlauf kurz, mach Pausen, blinzle und höre bei Ermüdung auf. Halte den Kopf ruhig und sitze aufrecht etwa 40 cm vom Bildschirm entfernt. Es gibt kein Flackern und keine schnellen Wechsel.',
    'Dunkler Raum und Überbrille: Rot und Grün trennen sich besser bei gedämpftem Raumlicht und ohne Spiegelungen auf dem Bildschirm. Trägst du eine Korrekturbrille, nimm eine Überbrille, die über deiner Brille sitzt. Schalte Nachtmodus und Farbfilter des Geräts aus.',
    'Prüfe vor dem Start das Prüfbild: Mit dem roten Glas vor dem Auge sollte die grüne Fläche dunkel erscheinen und umgekehrt. Siehst du durch ein Auge beide Flächen (Geisterbild), stelle die hellere Farbe dunkler.',
    'Die Werte sind Übungswerte: keine Prismenmessung, kein Ersatz für eine Untersuchung und keine Aussage darüber, wie weit deine Augen verschmelzen können. 1 Δ (Prismendioptrie) lenkt auf 1 m Entfernung um 1 cm ab; der Versatz wird mit der Sehentfernung der Kalibrierung in Zentimeter und Pixel umgerechnet. Stell den Bildschirm einmal ein („Bildschirm kalibrieren“).',
    'Auf kleinen Bildschirmen wird das Ziel verkleinert und die Obergrenze begrenzt, damit beide Bilder passen; im Ergebnis steht, worauf. Bei kleinen Werten ist der Versatz nur so fein einstellbar, wie der Bildschirm Pixel hat.',
    'Die App kann nicht prüfen, ob du die Brille trägst, wohin du schaust oder ob du wirklich doppelt siehst. Gespeichert wird nur, was du meldest.',
    'Kontrollstriche: Ein roter Strich über und ein Strich in der zweiten Farbe unter dem Ziel zeigen, ob beide Bilder ankommen. Fehlt einer, tippst du „Strich fehlt“ (Tastatur: Pfeil hoch oder runter). Gezählt wird nur, wie oft das vorkam – ein Hinweis, kein Befund.',
    'Trainer-Regler: In der Trainer- und Entwickler-Ansicht kann der Versatz während der Übung in kleinen Schritten verändert werden (höchstens 2 Δ je Tastendruck, Anzeige gleitet weich, jede Änderung wird mit Zeitpunkt festgehalten). Bei Doppelbildern, Schwindel oder Kopfschmerz sofort zurücknehmen und Pause machen.',
    'Die Aufgabe selbst beruht auf den Farben Rot und Grün; die Bedienung (Tasten mit Beschriftung) kommt ohne Farbe aus.',
  ],
  liveLabels: { shiftPd: 'Versatz der Bilder' },
  params: {
    ...anaglyphParamsDe,
    direction: {
      label: 'Richtung',
      hint: 'Konvergenz: Das Bild rückt scheinbar näher, die Augen drehen nach innen. Divergenz: Das Bild rückt scheinbar weg, die Augen drehen nach außen. Im Wechsel: erst die eine, dann die andere Richtung.',
      options: { both: 'Im Wechsel', convergence: 'Nur Konvergenz', divergence: 'Nur Divergenz' },
    },
    control: {
      label: 'Versatzsteuerung',
      hint: 'Automatisch: Der Versatz ändert sich mit Δ pro Sekunde; der Trainer-Regler (Trainer- oder Entwickler-Ansicht) legt zusätzlich einen Zusatz darauf. Trainer: Der Versatz ändert sich nur durch den Trainer-Regler, beginnend beim Startversatz; ohne Regler läuft die Übung automatisch.',
      options: { auto: 'Automatisch', trainer: 'Trainer' },
    },
    rampPdPerS: {
      label: 'Änderung pro Sekunde (Δ)',
      hint: 'Wie schnell der Versatz bei „automatisch“ wächst und schrumpft, in Prismendioptrien pro Sekunde (0,5 bis 6). Langsamer ist ruhiger.',
      short: '{v} Δ pro Sekunde',
    },
    startPd: {
      label: 'Startversatz (Δ)',
      hint: 'Versatz zu Beginn jedes Durchgangs (0 bis 10 Δ). Bei „Trainer“ ist das der Startwert des Reglers. Beginne bei 0.',
      short: 'Start {v} Δ',
    },
    maxPd: {
      label: 'Obergrenze des Versatzes (Δ)',
      hint: 'Größter Versatz (5 bis 40 Δ). Wird er erreicht, ohne dass du „Doppelt“ gemeldet hast, geht der Versatz zurück. Auf kleinen Bildschirmen kann die Obergrenze kleiner ausfallen, damit beide Bilder passen.',
      short: 'bis {v} Δ',
    },
    repeats: {
      label: 'Wiederholungen je Richtung',
      hint: 'Wie oft jede Richtung wiederholt wird (1 bis 6). Halte den Durchlauf kurz; bei Ermüdung höre auf.',
      short: '{v} Wiederholung|{v} Wiederholungen',
    },
    targetCm: {
      label: 'Zieldurchmesser',
      hint: 'Durchmesser des Ziels in Zentimetern (nach Kalibrierung des Bildschirms). Auf kleinen Bildschirmen wird er begrenzt, wenn beide Bilder sonst nicht passen.',
      short: '{v} cm',
    },
    leftLens: {
      label: 'Linkes Glas der Brille',
      hint: 'Welches Glas sitzt vor deinem linken Auge? Das bestimmt, welches Bild für Konvergenz nach rechts und welches nach links wandert. Stimmt die Einstellung nicht, sind Konvergenz und Divergenz vertauscht.',
      options: { red: 'Rot', green: 'Grün, Cyan oder Blau' },
    },
    redLevel: {
      label: 'Helligkeit Rot',
      hint: 'Anteil der Helligkeit des roten Bildes, 30 bis 100 Prozent in Schritten von 10. Im Prüfbild („Schritt für Schritt“) stellst du sie mit „Rot dunkler“ und „Rot heller“ ein.',
      short: 'Rot {v} %',
    },
    secondLevel: {
      label: 'Helligkeit zweite Farbe',
      hint: 'Anteil der Helligkeit des grünen, cyanfarbenen oder blauen Bildes, 30 bis 100 Prozent in Schritten von 10. Im Prüfbild („Schritt für Schritt“) stellst du sie mit den Tasten „dunkler“ und „heller“ ein.',
      short: 'Zweite Farbe {v} %',
    },
  },
};

export const it: ExerciseTexts = {
  title: 'Fusione – unire le immagini',
  tagline: 'Con gli occhiali rosso-verdi tieni singola l’immagine mentre si sposta.',
  steps: [
    'Occhiali rosso-verdi, stanza piuttosto buia, circa 40 cm.',
    'Tieni ferma l’immagine. Se diventa doppia: tocca “Doppia”.',
    'Se torna singola: tocca “Di nuovo singola”.',
  ],
  why:
    'Qui vedi un bersaglio fatto di cerchi che viene mostrato a ogni occhio nel proprio colore. Lo spostamento delle due immagini cresce lentamente finché segnali “Doppia”, poi diminuisce finché segnali “Di nuovo singola”. Convergenza significa: l’immagine sembra avvicinarsi, gli occhi ruotano verso l’interno; divergenza: sembra allontanarsi, gli occhi ruotano verso l’esterno. Lo spostamento è in diottrie prismatiche (Δ): 1 Δ devia di 1 cm a 1 m di distanza. I valori sono valori di esercizio che confronti solo con te stesso – non una misurazione prismatica e non sostituiscono una visita. Non è dimostrato che l’esercizio migliori la collaborazione degli occhi nella vita quotidiana, nello sport o nel traffico.',
  goodFor: ['Collaborazione degli occhi', 'Sguardo calmo', 'Attenzione'],
  captions: {
    look: 'Guarda con calma il bersaglio',
    strokes: 'Manca un trattino? Questo tasto',
    up: 'Diventa doppia? Tocca “Doppia”',
    down: 'Singola? Tocca “Di nuovo singola”',
  },
  metrics: {
    break_mean: 'Segnalata doppia a (media)',
    break_conv: 'Convergenza: segnalata doppia a',
    rec_conv: 'Convergenza: segnalata di nuovo singola a',
    break_div: 'Divergenza: segnalata doppia a',
    rec_div: 'Divergenza: segnalata di nuovo singola a',
    trials: 'Passaggi completati',
    capped: 'Passaggi fino al limite, senza “Doppia”',
    no_recovery: 'Passaggi senza “Di nuovo singola”',
    control: 'Guida dello spostamento',
    max: 'Limite dello spostamento',
    target: 'Diametro del bersaglio',
  },
  metricHints: {
    break_mean:
      'Media dei valori (in diottrie prismatiche Δ) a cui hai segnalato “Doppia”. I passaggi arrivati al limite senza che tu segnalassi qualcosa non contano qui. È un valore di esercizio per confrontarti con te stesso a parità di impostazioni: un valore più alto non è “migliore” e non è una misurazione prismatica.',
    break_conv: 'Media dei valori a cui in convergenza (l’immagine sembra avvicinarsi) hai segnalato “Doppia”, in Δ.',
    rec_conv: 'Media dei valori a cui in convergenza, dopo “Doppia”, hai segnalato “Di nuovo singola”, in Δ.',
    break_div: 'Media dei valori a cui in divergenza (l’immagine sembra allontanarsi) hai segnalato “Doppia”, in Δ.',
    rec_div: 'Media dei valori a cui in divergenza, dopo “Doppia”, hai segnalato “Di nuovo singola”, in Δ.',
    trials: 'Quanti passaggi (ognuno con una salita e una discesa dello spostamento) sono stati completati.',
    capped: 'Passaggi in cui lo spostamento ha raggiunto il limite senza che tu segnalassi “Doppia”. Il loro valore è tagliato verso l’alto e quindi non conta nelle medie.',
    no_recovery: 'Passaggi in cui lo spostamento è tornato a 0 senza che tu segnalassi “Di nuovo singola”. Non contano nelle medie del ritorno. Contano anche occhiali, colori dello schermo, stanchezza e uso.',
    control: 'Come è stato guidato lo spostamento: automaticamente con Δ al secondo, oppure solo dal regolatore del trainer.',
    max: 'Spostamento massimo in Δ, in cm e pixel, convertito con la distanza della calibrazione. Sugli schermi piccoli può essere limitato perché entrambe le immagini entrino nello schermo.',
    target: 'Diametro del bersaglio in centimetri. È minore di quello impostato se il bersaglio altrimenti non entra nello schermo.',
  },
  tips: {
    few: 'Nessun passaggio è stato completato. Controlla l’immagine di controllo per gli occhiali e inizia con un bersaglio grande e una variazione lenta.',
    noRecovery:
      'In molti passaggi l’immagine non si è più unita prima che lo spostamento tornasse a 0. Controlla occhiali, luce della stanza e luminosità nell’immagine di controllo. Se vedi spesso doppio: non esercitarti da solo, fai chiarire la cosa dall’ottico o dall’oculista.',
    capped: 'In molti passaggi non hai segnalato nulla fino al limite. Controlla di toccare “Doppia” onestamente al primo segno e che occhiali e immagine di controllo siano a posto. Il limite si imposta nelle impostazioni.',
    strokes: 'Hai segnalato che mancava un trattino. È solo un’indicazione: contano anche occhiali, colori dello schermo e luminosità. Controlla prima l’immagine di controllo; se resta così per più giri, parlane con il tuo ottico.',
    compare: 'Confronta questo giro solo con giri con le stesse impostazioni – su questo dispositivo, con luce simile e alla stessa distanza.',
  },
  feedback: {
    ...anaglyphFeedbackIt,
    msgReady: 'Tieni l’immagine ferma e singola …',
    msgUp: 'Appena l’immagine diventa doppia: tocca “Doppia”',
    msgDown: 'Appena l’immagine è di nuovo singola: tocca “Di nuovo singola”',
    doubleBtn: 'Doppia',
    singleBtn: 'Di nuovo singola',
    dirConvergence: 'Convergenza',
    dirDivergence: 'Divergenza',
    hudLabel: '{dir} · {n} / {total}',
    none: '–',
    dirTitle: 'Per direzione',
    dirLabel: '{dir} (doppia · di nuovo singola)',
    dirValue: '{b}\u00A0·\u00A0{r}\u00A0Δ',
    dirCount: '{n} passaggi, {c} fino al limite, {x} senza “Di nuovo singola”',
    dirNote: 'Sono medie dei valori a cui hai segnalato qualcosa – valori di esercizio, non una misurazione prismatica. Una riga senza numero significa: non c’era nessuna segnalazione.',
    runsTitle: 'Passaggi',
    runsNote: 'I passaggi fino al limite e quelli senza “Di nuovo singola” non contano nelle medie.',
    strokeTitle: 'Trattini di controllo (indicazione, non referto)',
    strokeRow: 'Trattino mancante: {c}',
    strokeValue: 'segnalato {k} volte',
    strokeNote:
      'Si conta solo quante volte hai segnalato che mancava un trattino. È un’indicazione, non un referto: contano anche occhiali, colori dello schermo e luminosità. Se manca sempre lo stesso trattino, parlane con il tuo ottico o con l’oculista.',
    settingsTitle: 'Impostazioni e conversione',
    controlAuto: '{r} Δ al secondo',
    controlTrainer: 'solo il regolatore del trainer (inizio {s} Δ)',
    controlLive: 'automatico; il regolatore del trainer aggiunge un valore',
    controlFallback: 'Regolatore del trainer non disponibile: lo spostamento è andato in automatico',
    pdValue: 'fino a {pd} Δ',
    cmValue: '{cm} cm',
    maxDetail: 'circa {cm} cm (≈ {px} px) tra le immagini a {d} cm di distanza',
    maxLimited: 'limitato su questo schermo a {pd} Δ perché entrambe le immagini entrino',
    targetLimited: 'Limitato su questo schermo',
    notCalibrated: 'non calibrato: stima',
    valuesNote:
      'Tutti i valori sono valori di esercizio: non una misurazione prismatica e non sostituiscono una visita. Valgono solo per questo schermo, questa calibrazione e questa distanza. Confrontali solo con i tuoi valori.',
    liveTitle: 'Regolatore del trainer (durante l’esercizio)',
    liveCount: 'Spostamento modificato dal trainer',
    liveCountValue: '{n} volte, da ultimo {v} {u} (spostamento dopo {t} {u})',
    liveEntry: 'Passaggio {k}, {time}',
    liveEntryValue: '{v} {u} (spostamento dopo {t} {u})',
    liveMore: '… e altre {n} modifiche',
    liveNote:
      'Il regolatore vale solo per questo giro e non cambia le impostazioni. Con “automatico” lo spostamento è il valore automatico più l’aggiunta (l’aggiunta parte da 0 in ogni passaggio); con “Trainer” decide solo il regolatore. Si è segnalato sempre il valore mostrato in quel momento.',
  },
  progression: [
    'Più facile: variazione più lenta (da 0,5 a 1 Δ al secondo), bersaglio più grande (da 8 a 10 cm), una sola direzione, limite basso.',
    'Più difficile: variazione più rapida, bersaglio più piccolo (da 3 a 4 cm), le due direzioni alternate, più ripetizioni. Cambia sempre una sola impostazione alla volta.',
    'Tocca “Doppia” onestamente al primo segno di immagini doppie, non quando sono già molto distanti. È sapere empirico della pratica dell’optometria funzionale, non dimostrato da studi.',
    'Convergenza e divergenza spesso risultano diverse; confronta ogni direzione solo con se stessa. Confronta solo giri con le stesse impostazioni, sullo stesso dispositivo e alla stessa distanza.',
    'La nostra regola pratica (non è una indicazione della ricerca): se inizi, parti con un limite basso e variazione lenta, fai pause e smetti prima che l’immagine resti doppia o compaiano disturbi.',
    'Guida “Trainer”: lo spostamento cambia solo con il regolatore del trainer (vista del trainer o dello sviluppatore), partendo dallo spostamento iniziale. Senza regolatore l’esercizio va in automatico.',
  ],
  cautions: [
    'Alterazione della visione dei colori rosso-verde: circa 8 uomini su 100 e 4 donne su 1000 di origine europea (Birch, 2012). Allora rosso e verde vengono separati in modo errato e l’esercizio non è adatto a te. Anche con la coppia rosso–blu controlli nell’immagine di controllo se riesci a separare i colori.',
    'In caso di strabismo, visione doppia, vertigini o mal di testa: esercitarti solo dopo accordo con lo specialista che ti segue, altrimenti per niente. Se compaiono visione doppia, vertigini, mal di testa o dolore agli occhi, smetti subito e fai chiarire la cosa (Muchnick, 2008, p. 6 e 28).',
    '“Doppia” fa parte dell’esercizio: la segnali al primo segno. Se poi l’immagine resta doppia o i disturbi aumentano, smetti e fai una pausa.',
    'Tieni ogni giro breve, fai pause, sbatti le palpebre e smetti in caso di stanchezza. Tieni la testa ferma e siediti dritto a circa 40 cm dallo schermo. Non c’è sfarfallio né cambi rapidi.',
    'Stanza buia e occhiali da sovrapporre: rosso e verde si separano meglio con luce soffusa e senza riflessi sullo schermo. Se porti occhiali correttivi, usa occhiali da sovrapporre alla tua montatura. Disattiva la modalità notturna e i filtri colore del dispositivo.',
    'Prima di iniziare controlla l’immagine di controllo: con la lente rossa davanti all’occhio la superficie verde dovrebbe apparire scura e viceversa. Se con un occhio vedi entrambe le superfici (immagine fantasma), rendi più scuro il colore più chiaro.',
    'I valori sono valori di esercizio: non una misurazione prismatica, non sostituiscono una visita e non dicono fin dove i tuoi occhi riescono a unire le immagini. 1 Δ (diottria prismatica) devia di 1 cm a 1 m di distanza; lo spostamento viene convertito in centimetri e pixel con la distanza visiva della calibrazione. Imposta lo schermo una volta (“Calibra lo schermo”).',
    'Sugli schermi piccoli il bersaglio viene ridotto e il limite ristretto perché entrambe le immagini entrino; nel risultato trovi a quanto. Con valori piccoli lo spostamento si regola solo tanto finemente quanto lo schermo ha pixel.',
    'L’app non può controllare se porti gli occhiali, dove guardi o se vedi davvero doppio. Si salva solo ciò che segnali.',
    'Trattini di controllo: un trattino rosso sopra e uno nel secondo colore sotto il bersaglio mostrano se arrivano entrambe le immagini. Se ne manca uno, tocca “Manca il trattino” (tastiera: freccia su o giù). Si conta solo quante volte è successo – un’indicazione, non un referto.',
    'Regolatore del trainer: nella vista del trainer e dello sviluppatore lo spostamento può essere cambiato durante l’esercizio a piccoli passi (al massimo 2 Δ per tasto, la visualizzazione scorre dolcemente, ogni modifica viene registrata con l’orario). In caso di visione doppia, vertigini o mal di testa riduci subito e fai una pausa.',
    'Il compito stesso si basa sui colori rosso e verde; l’uso (tasti con etichetta) non dipende dal colore.',
  ],
  liveLabels: { shiftPd: 'Spostamento delle immagini' },
  params: {
    ...anaglyphParamsIt,
    direction: {
      label: 'Direzione',
      hint: 'Convergenza: l’immagine sembra avvicinarsi, gli occhi ruotano verso l’interno. Divergenza: l’immagine sembra allontanarsi, gli occhi ruotano verso l’esterno. Alternate: prima una direzione, poi l’altra.',
      options: { both: 'Alternate', convergence: 'Solo convergenza', divergence: 'Solo divergenza' },
    },
    control: {
      label: 'Guida dello spostamento',
      hint: 'Automatica: lo spostamento cambia con Δ al secondo; il regolatore del trainer (vista del trainer o dello sviluppatore) aggiunge inoltre un valore. Trainer: lo spostamento cambia solo con il regolatore del trainer, partendo dallo spostamento iniziale; senza regolatore l’esercizio va in automatico.',
      options: { auto: 'Automatica', trainer: 'Trainer' },
    },
    rampPdPerS: {
      label: 'Variazione al secondo (Δ)',
      hint: 'Quanto in fretta lo spostamento con “automatica” cresce e diminuisce, in diottrie prismatiche al secondo (da 0,5 a 6). Più lento è più calmo.',
      short: '{v} Δ al secondo',
    },
    startPd: {
      label: 'Spostamento iniziale (Δ)',
      hint: 'Spostamento all’inizio di ogni passaggio (da 0 a 10 Δ). Con “Trainer” è il valore iniziale del regolatore. Inizia da 0.',
      short: 'Inizio {v} Δ',
    },
    maxPd: {
      label: 'Limite dello spostamento (Δ)',
      hint: 'Spostamento massimo (da 5 a 40 Δ). Se viene raggiunto senza che tu abbia segnalato “Doppia”, lo spostamento torna indietro. Sugli schermi piccoli il limite può essere più basso perché entrambe le immagini entrino.',
      short: 'fino a {v} Δ',
    },
    repeats: {
      label: 'Ripetizioni per direzione',
      hint: 'Quante volte si ripete ogni direzione (da 1 a 6). Tieni il giro breve; in caso di stanchezza smetti.',
      short: '{v} ripetizione|{v} ripetizioni',
    },
    targetCm: {
      label: 'Diametro del bersaglio',
      hint: 'Diametro del bersaglio in centimetri (dopo la calibrazione dello schermo). Sugli schermi piccoli viene limitato se entrambe le immagini altrimenti non entrano.',
      short: '{v} cm',
    },
    leftLens: {
      label: 'Lente sinistra degli occhiali',
      hint: 'Quale lente è davanti al tuo occhio sinistro? Decide quale immagine con la convergenza si sposta a destra e quale a sinistra. Se l’impostazione è sbagliata, convergenza e divergenza risultano scambiate.',
      options: { red: 'Rossa', green: 'Verde, ciano o blu' },
    },
    redLevel: {
      label: 'Luminosità del rosso',
      hint: 'Quota della luminosità dell’immagine rossa, dal 30 al 100 per cento a passi di 10. Nell’immagine di controllo (“Passo dopo passo”) la regoli con “Rosso più scuro” e “Rosso più chiaro”.',
      short: 'Rosso {v} %',
    },
    secondLevel: {
      label: 'Luminosità del secondo colore',
      hint: 'Quota della luminosità dell’immagine verde, ciano o blu, dal 30 al 100 per cento a passi di 10. Nell’immagine di controllo (“Passo dopo passo”) la regoli con i tasti “più scuro” e “più chiaro”.',
      short: 'Secondo colore {v} %',
    },
  },
};
