import type { ExerciseTexts } from '../../core/types';

// Formulierungsregeln (docs/wissenschaft/01-…, 4.4 und 04-…, 9.2/10): nur beschreiben, was man in der
// Übung tut – keine IQ-/Intelligenz-Versprechen, keine Demenz-Aussagen, kein Vergleich mit anderen.
// Regel-Erklärungen: Schlüssel r_* mit Platzhaltern {k}, {a}, {b}, {s}, {s1}, {s2}, {part}, {dir}.

export const de: ExerciseTexts = {
  title: 'Reihen-Rätsel',
  tagline: 'Wie geht die Reihe weiter? Finde die Regel – ganz ohne Zeitdruck.',
  steps: ['Schau dir die Reihe an: Zahlen, Buchstaben oder Formen.', 'Tippe an, was an die Stelle mit dem ? gehört.', 'Danach siehst du die Regel – lass dir Zeit.'],
  why:
    'Beim Reihen-Rätsel suchst du die Regel hinter einer Reihe und setzt sie fort. Ähnliche Aufgaben wurden in einer großen Studie mit älteren Menschen geübt – die geübte Fähigkeit blieb dort über Jahre besser. Unsere Version selbst wurde nicht untersucht, und dass sie das Denken im Alltag verbessert, ist nicht belegt.',
  goodFor: ['Knobeln', 'Muster erkennen', 'In Ruhe nachdenken'],
  captions: {
    ask: 'Wie geht die Reihe weiter?',
    rule: 'Danach siehst du die Regel.',
    shapes: 'Auch mit Formen – ganz ohne Eile.',
  },
  metrics: {
    level: 'Erreichte Stufe',
    correct: 'Richtig gelöst (von 10)',
    hardest: 'Schwerste gelöste Stufe',
    time: 'Zeit pro Aufgabe (Mittel)',
  },
  tips: {
    steps: 'Schau auf die Abstände zwischen den Zahlen: +2, +3 … Oft steckt dort die Regel.',
    two: 'Wenn nichts passt: Schau nur auf jedes zweite Teil – manchmal laufen zwei Reihen ineinander.',
    calm: 'Lass dir ruhig Zeit – hier zählt nicht das Tempo, sondern die Regel.',
    great: 'Stark gelöst! Beim nächsten Mal warten schwierigere Regeln auf dich.',
  },
  feedback: {
    level: 'Stufe',
    ask: 'Was gehört an die Stelle mit dem ?',
    right: 'Richtig!',
    wrong: 'Nicht ganz – so geht’s:',
    next: 'Weiter',
    r_add: 'Immer +{k}.',
    r_sub: 'Immer −{k}.',
    r_double: 'Immer das Doppelte (×2).',
    r_triple: 'Immer mal 3 (×3).',
    r_alt: 'Abwechselnd +{a} und +{b}.',
    r_altMul: 'Abwechselnd +{a} und ×2.',
    r_inter: 'Zwei Reihen im Wechsel: {s1} und {s2}',
    r_grow: 'Der Abstand wird jedes Mal um 1 größer: {s}',
    r_growDouble: 'Der Abstand verdoppelt sich jedes Mal: {s}',
    r_fib: 'Jede Zahl ist die Summe der beiden davor.',
    r_mulAdd: 'Immer ×2 und dann +1.',
    r_cyc: 'Immer der Reihe nach +{a}, +{b}, +{c}.',
    r_squares: 'Jede Zahl mal sich selbst: {s}',
    r_letters: 'Im Alphabet immer {k} weiter: {s}',
    r_lettersBack: 'Im Alphabet rückwärts, immer {k} zurück: {s}',
    r_patAB: 'Zwei Formen wechseln sich immer ab.',
    r_patABC: 'Drei Formen wiederholen sich immer in derselben Reihenfolge.',
    r_patAAB: 'Immer zwei gleiche Formen, dann eine andere.',
    r_count: 'Jedes Mal eine Form mehr.',
    r_countAlt: 'Jedes Mal eine mehr – und die Form wechselt ab.',
    r_rot: 'Der Pfeil dreht sich jedes Mal {part} weiter – {dir}.',
    part1: 'eine Achteldrehung',
    part2: 'eine Vierteldrehung',
    cw: 'im Uhrzeigersinn',
    ccw: 'gegen den Uhrzeigersinn',
  },
};

export const it: ExerciseTexts = {
  title: 'Serie logiche',
  tagline: 'Come continua la serie? Trova la regola – senza alcuna fretta.',
  steps: ['Guarda la serie: numeri, lettere o forme.', 'Tocca ciò che va al posto del ?.', 'Poi vedi la regola – prenditi il tuo tempo.'],
  why:
    'In Serie logiche cerchi la regola dietro una serie e la continui. Esercizi simili sono stati praticati in un grande studio con persone anziane – lì l’abilità allenata è rimasta migliore per anni. La nostra versione non è stata studiata, e che migliori il ragionamento nella vita quotidiana non è dimostrato.',
  goodFor: ['Rompicapi', 'Riconoscere schemi', 'Riflettere con calma'],
  captions: {
    ask: 'Come continua la serie?',
    rule: 'Poi vedi la regola.',
    shapes: 'Anche con le forme – senza fretta.',
  },
  metrics: {
    level: 'Livello raggiunto',
    correct: 'Risolti (su 10)',
    hardest: 'Livello più difficile risolto',
    time: 'Tempo per esercizio (medio)',
  },
  tips: {
    steps: 'Guarda la distanza tra i numeri: +2, +3 … Spesso la regola è lì.',
    two: 'Se nulla torna: guarda solo un elemento ogni due – a volte due serie si intrecciano.',
    calm: 'Prenditi pure il tuo tempo – qui non conta la velocità, ma la regola.',
    great: 'Ottimo lavoro! La prossima volta ti aspettano regole più difficili.',
  },
  feedback: {
    level: 'Livello',
    ask: 'Cosa va al posto del ?',
    right: 'Giusto!',
    wrong: 'Non proprio – ecco come:',
    next: 'Avanti',
    r_add: 'Sempre +{k}.',
    r_sub: 'Sempre −{k}.',
    r_double: 'Ogni volta il doppio (×2).',
    r_triple: 'Ogni volta per 3 (×3).',
    r_alt: 'Alternando +{a} e +{b}.',
    r_altMul: 'Alternando +{a} e ×2.',
    r_inter: 'Due serie alternate: {s1} e {s2}',
    r_grow: 'La distanza cresce ogni volta di 1: {s}',
    r_growDouble: 'La distanza raddoppia ogni volta: {s}',
    r_fib: 'Ogni numero è la somma dei due precedenti.',
    r_mulAdd: 'Ogni volta ×2 e poi +1.',
    r_cyc: 'Sempre in ordine +{a}, +{b}, +{c}.',
    r_squares: 'Ogni numero per se stesso: {s}',
    r_letters: 'Nell’alfabeto sempre {k} avanti: {s}',
    r_lettersBack: 'Nell’alfabeto all’indietro, sempre {k} indietro: {s}',
    r_patAB: 'Due forme si alternano sempre.',
    r_patABC: 'Tre forme si ripetono sempre nello stesso ordine.',
    r_patAAB: 'Sempre due forme uguali, poi una diversa.',
    r_count: 'Ogni volta una forma in più.',
    r_countAlt: 'Ogni volta una in più – e la forma si alterna.',
    r_rot: 'La freccia gira ogni volta di {part} – {dir}.',
    part1: 'un ottavo di giro',
    part2: 'un quarto di giro',
    cw: 'in senso orario',
    ccw: 'in senso antiorario',
  },
};
