// Quellen: jede Angabe einzeln per Crossref (Metadaten, Autoren, Zeitschrift, Band, Seiten) und über PubMed/OpenAlex
// (Abstract) geprüft (02.10.2026); die Aussagen im Text wurden mit dem Abstract abgeglichen.
// Alle Quellen sind einzeln gesucht und geprüft.
// Nicht aufgenommen: Treisman & Gelade (1980), Cogn Psychol 12, 97–136 (10.1016/0010-0285(80)90005-5) – Metadaten bestätigt,
// aber weder PubMed noch OpenAlex haben einen Abstract; die Aussage zur Ähnlichkeit steht stattdessen über Duncan & Humphreys (1989)
// (Abstract bestätigt).
// Nicht aufgenommen (nicht belegt oder Wirkversprechen): „Verwechslungen von Zeichen … werden hier gezielt geübt“,
// „sind in der Lesentwicklung häufig“ (nur noch vorsichtig über Dehaene et al. 2010), „ein aussagekräftiges Maß ist …“,
// der Hinweis, Spiegelungen „fachlich abklären zu lassen“ (klingt nach Diagnose).
// Nicht belegt und im Text gekennzeichnet: ob Üben der Zeichensuche Lesen oder Rechtschreibung beeinflusst. Einzelne Buchstaben
// werden besser erkannt als gedrängte Reihen (Crowding): nur als Praxisangabe der funktionellen Optometrie genannt, nicht belegt.
import type { ScienceEntry } from '../../content/science';

const src = (label: string, url: string) => ({ label, url });

export const science: ScienceEntry = {
  id: 'labor-zeichen-finden',
  evidence: 'weak',
  texts: {
    de: {
      trains: 'Zwischen sehr ähnlichen Zeichen alle Exemplare eines Zielzeichens finden – genaues Hinsehen und Absuchen. Zeichenvorrat, Rastergröße, Anteil der Zielzeichen und Feldgröße stellst du selbst ein.',
      daily: 'Überall, wo man etwas zwischen sehr ähnlichen Dingen suchen muss: Zahlen in einer Liste, Teile in einer Schublade, Einträge in einem Formular. Ob die Übung dabei oder beim Lesen und Schreiben hilft, ist nicht belegt.',
      research:
        'Aufgaben, in denen man ein Zielzeichen zwischen anderen Zeichen sucht, gehören zur visuellen Suche. Wie schwer sie ist, hängt davon ab, wie ähnlich Ziel und Störzeichen sind: Je ähnlicher das Ziel den anderen Zeichen und je unähnlicher diese untereinander sind, desto schwerer wird die Suche (Duncan & Humphreys, 1989). Wohin die Aufmerksamkeit beim Suchen geht, wird von mehreren Faktoren gelenkt, zum Beispiel von auffälligen Merkmalen, vom gesuchten Merkmal und von der bisherigen Suche (Wolfe & Horowitz, 2017). Bei Buchstaben fasst eine Übersichtsarbeit zusammen, dass die Trefferquote beim Erkennen häufig auf Wahrnehmbarkeit, Antwortneigung und Ähnlichkeit der Buchstaben zurückgeführt wird (Mueller & Weidemann, 2012). Die Ähnlichkeit ist also nicht für alle Paare gleich, und deshalb wechselt hier das gesuchte Zeichen reihum, damit jedes etwa gleich oft vorkommt. Zu Spiegelpaaren wie b und d: Das Sehsystem behandelt Spiegelbilder von Bildern zunächst als dasselbe; beim Lesenlernen muss das für Buchstaben überwunden werden, was die Spiegelfehler kleiner Kinder erklären könnte (Dehaene et al., 2010). In der Praxis der funktionellen Optometrie gilt, dass einzelne Buchstaben besser erkannt werden als dicht gedrängte Reihen („Crowding“); Zeichengröße und Abstand sind deshalb Stellgrößen der Schwierigkeit – als Erfahrungswissen beschrieben, hier nicht belegt. Ob Üben der Zeichensuche das Lesen oder die Rechtschreibung beeinflusst, ist nicht belegt; die Übung misst das nicht und sagt nichts über deine Augen oder deine Lesefähigkeit. Touchscreens messen Zeiten durchweg etwas zu lang, je nach Gerät unterschiedlich (Pronk et al., 2020); Tablets wurden dort nicht untersucht. Darum zählt nur der Vergleich mit dir selbst auf demselben Gerät und mit denselben Einstellungen. Für genau diese Übung gibt es keine Studie.',
      improved:
        'Auf jeder Tafel trägt der eingestellte Anteil der Felder das gesuchte Zeichen (mindestens ein Feld, nie alle), die übrigen zeigen ein anderes Zeichen desselben Vorrats. Das gesuchte Zeichen wechselt von Tafel zu Tafel reihum und nie zweimal hintereinander, weil die Ähnlichkeit nicht für alle Zeichenpaare gleich ist; so kommt jedes Zeichen etwa gleich oft vor. Die Felder werden in Zentimetern angegeben (nach Kalibrierung des Bildschirms), die Zeichen sind mindestens etwa 22 Pixel groß; passt das Raster nicht auf den Bildschirm, wird es für diese Tafel gedreht dargestellt oder verkleinert, und die Ergebnisseite weist darauf hin. Die Zeit einer Tafel läuft erst, wenn sie zu sehen ist, und bereits bearbeitete Felder reagieren nicht mehr auf Tippen. Die Rückmeldung bleibt zurückhaltend: ✓ mit Ring für Treffer, ✗ mit gestricheltem Feld für falsche Zeichen, nach „Fertig“ werden übersehene Zeichen gestrichelt umrandet, ohne Blitzen und ohne Rot als einziges Signal. Jeder Durchlauf merkt sich seine Einstellungen, und Verlauf, Bestwert und „Letztes Mal“ vergleichen nur Läufe mit gleichen Einstellungen; gezeigt werden Genauigkeit, Zeit pro gefundenem Zeichen sowie gefundene, übersehene und falsch getippte Zeichen – ohne Noten, Normwerte und Ranglisten.',
    },
    it: {
      trains: 'Trovare tutti gli esemplari di un carattere cercato tra caratteri molto simili – guardare bene e passare in rassegna. Serie di caratteri, grandezza della griglia, quota dei caratteri cercati e grandezza dei campi li imposti tu.',
      daily: 'Ovunque si debba cercare qualcosa tra cose molto simili: numeri in un elenco, pezzi in un cassetto, voci in un modulo. Che l’esercizio aiuti in questo o nel leggere e scrivere non è dimostrato.',
      research:
        'I compiti in cui si cerca un carattere tra altri caratteri appartengono alla ricerca visiva. La difficoltà dipende da quanto somigliano bersaglio e distrattori: quanto più il bersaglio somiglia agli altri caratteri e quanto meno questi somigliano tra loro, tanto più difficile diventa la ricerca (Duncan e Humphreys, 1989). Dove va l’attenzione durante la ricerca è guidato da più fattori, per esempio da caratteristiche vistose, dalla caratteristica cercata e dalla ricerca precedente (Wolfe e Horowitz, 2017). Per le lettere una rassegna riassume che la precisione nel riconoscimento è spesso attribuita a percepibilità, tendenza a rispondere e somiglianza delle lettere (Mueller e Weidemann, 2012). La somiglianza non è quindi uguale per tutte le coppie, e per questo qui il carattere cercato cambia a turno, perché ciascuno compaia circa ugualmente spesso. Sulle coppie speculari come b e d: il sistema visivo tratta dapprima le immagini speculari delle figure come la stessa cosa; imparando a leggere questo va superato per le lettere, il che potrebbe spiegare gli errori speculari dei bambini piccoli (Dehaene et al., 2010). Nella pratica dell’optometria funzionale si ritiene che le singole lettere vengano riconosciute meglio delle file fitte (“crowding”); dimensione dei caratteri e spaziatura sono quindi variabili di difficoltà – descritto come sapere empirico, qui non dimostrato. Che esercitare la ricerca di caratteri influenzi la lettura o l’ortografia non è dimostrato; l’esercizio non lo misura e non dice nulla sui tuoi occhi o sulla tua capacità di lettura. I touchscreen misurano i tempi sistematicamente un po’ in eccesso, in modo diverso a seconda del dispositivo (Pronk et al., 2020); i tablet non erano stati studiati. Per questo conta solo il confronto con te stesso sullo stesso dispositivo e con le stesse impostazioni. Per questo esercizio non esiste uno studio.',
      improved:
        'In ogni tavola la quota impostata di campi porta il carattere cercato (almeno un campo, mai tutti), gli altri mostrano un altro carattere della stessa serie. Il carattere cercato cambia da una tavola all’altra a turno e mai due volte di seguito, perché la somiglianza non è uguale per tutte le coppie di caratteri; così ogni carattere compare circa ugualmente spesso. I campi sono espressi in centimetri (dopo la calibrazione dello schermo), i caratteri sono grandi almeno circa 22 pixel; se la griglia non sta sullo schermo, per questa tavola viene disegnata ruotata o ridotta, e la pagina del risultato lo segnala. Il tempo di una tavola parte solo quando è visibile, e i campi già elaborati non reagiscono più al tocco. La risposta resta sobria: ✓ con anello per i colpi a segno, ✗ con campo tratteggiato per i caratteri sbagliati, dopo “Fatto” i caratteri non visti sono circondati da un tratteggio, senza lampeggi e senza il rosso come unico segnale. Ogni giro ricorda le sue impostazioni, e andamento, record e “ultima volta” confrontano solo giri con le stesse impostazioni; vengono mostrati precisione, tempo per carattere trovato e caratteri trovati, non visti e toccati sbagliati – senza voti, valori di riferimento e classifiche.',
    },
  },
  sources: [
    src('Duncan & Humphreys (1989). Visual search and stimulus similarity. Psychological Review', 'https://doi.org/10.1037/0033-295x.96.3.433'),
    src('Wolfe & Horowitz (2017). Five factors that guide attention in visual search. Nature Human Behaviour', 'https://doi.org/10.1038/s41562-017-0058'),
    src('Mueller & Weidemann (2012). Alphabetic letter identification: Effects of perceivability, similarity, and bias. Acta Psychologica', 'https://doi.org/10.1016/j.actpsy.2011.09.014'),
    src('Dehaene, Nakamura, Jobert, Kuroki, Ogawa & Cohen (2010). Why do children make mirror errors in reading? Neural correlates of mirror invariance in the visual word form area. NeuroImage', 'https://doi.org/10.1016/j.neuroimage.2009.09.024'),
    src('Pronk, Wiers, Molenkamp & Murre (2020). Mental chronometry in the pocket? Timing accuracy of web applications on touchscreen and keyboard devices. Behavior Research Methods', 'https://doi.org/10.3758/s13428-019-01321-2'),
  ],
};
