// Quellen: jede Angabe einzeln per Crossref (Metadaten) und über PubMed (Abstract) geprüft (02.10.2026); die Aussagen im
// Text halten sich an das, was im Abstract steht. Der Labor-Prototyp (help/chart.js) hatte KEINE Quellen
// (`references: []`); alle Quellen sind neu gesucht und geprüft (teils aus docs/uebungskatalog/literatur/lit-W13, dort
// ebenfalls per Crossref/Abstract geprüft, hier erneut abgefragt):
// - Pelli & Tillman (2008): Gedränge (Crowding), Bouma-Gesetz, Größe des „ungedrängten Fensters“ begrenzt Lese- und Suchtempo (Abstract).
// - Whitney & Levi (2011): Gedränge als grundlegende Grenze des Erkennens in fast dem ganzen Gesichtsfeld (Abstract).
// - Liu & Arditi (2001): enger Buchstabenabstand (0,1 statt 1,0 Buchstabenhöhe) → mehr zufällige und neue Verwechslungen
//   (Fünf-Buchstaben-Reihen, in der Fovea) (Abstract).
// - Deubel & Schneider (1996): Aufmerksamkeit und Blicksprung-Ziel sind gekoppelt (Abstract).
// - Rayner (1998): Übersicht zu Augenbewegungen beim Lesen und Suchen (Abstract; nur als „gut untersucht“ genannt).
// - Pronk et al. (2020), Guo et al. (2025): Grenzen der Messung am Touchgerät bzw. Gewöhnungseffekt (Abstract).
// Hart-Chart-Suche: PubMed, 02.10.2026: „Hart chart“ [Titel/Abstract] = 6 Treffer (Akkommodation/Scharfstellen bzw. fachfremd),
// „Hart chart“ UND saccad* = 0 Treffer. Die Wirkangaben von Anbietern (Sehtherapie) sind Praxisangaben ohne Beleg und stehen nicht
// als Aussage im Text. Nicht übernommen: Aussagen des Prototyp-Textes ohne Quelle („die Tafel wirkt besonders, wenn man die
// Zeichen im Augenwinkel mitnimmt“; „Gleichmäßigkeit des Tempos ist eine einfache Kennzahl für flüssiges Lesen“; „schult
// Blicksprünge, Lesefluss …“ – Wirkversprechen). Für genau diese Übung wurde keine Studie gefunden. Nicht bestätigt werden
// konnte: Volltext der Studien (nur Abstracts gelesen).
import type { ScienceEntry } from '../../content/science';

const src = (label: string, url: string) => ({ label, url });

export const science: ScienceEntry = {
  id: 'labor-buchstabentafel',
  evidence: 'weak',
  texts: {
    de: {
      trains: 'Eine Tafel aus Zeichengruppen Schritt für Schritt lesen: Eine Marke zeigt das nächste Zeichen, im eigenen Tempo oder im Takt. Tafelgröße, Zeichen, Abstände und Leseordnung stellst du selbst ein.',
      daily: 'Überall, wo man viele eng gesetzte Zeichen der Reihe nach erfasst, zum Beispiel Zahlenkolonnen oder Tabellen. Ob die Übung dabei hilft, ist nicht belegt.',
      research:
        'Buchstabentafeln dieser Art (Hart-Charts) werden in der Sehtherapie verwendet. Zu ihrer Wirkung auf Blickwechsel fanden wir in der Fachdatenbank PubMed (Suche am 02.10.2026) keine Studie; die Wirkangaben von Anbietern sind Praxisangaben ohne Beleg. Aus der Forschung ist bekannt: Zeichen, die dicht nebeneinanderstehen, sind schwerer zu erkennen als einzelne (Gedränge, englisch „Crowding“). Der Abstand, den Zeichen mindestens brauchen, damit sie nicht ineinander verschwimmen, wächst mit der Entfernung von der Blickmitte (Bouma-Gesetz) und begrenzt das Lese- und Suchtempo (Pelli & Tillman, 2008); Gedränge ist in fast dem ganzen Gesichtsfeld eine Grenze des Erkennens (Whitney & Levi, 2011). Bei engem Abstand (0,1 statt 1,0 Buchstabenhöhe) kamen in einer Studie mit Fünf-Buchstaben-Reihen mehr zufällige Verwechslungen vor (Liu & Arditi, 2001) – darum kannst du den Abstand der Zeichen einstellen. Vor einem Blicksprung wandert die Aufmerksamkeit zum Zielzeichen: Dort gelingt das Erkennen am besten, an Nachbarzeichen nur noch etwa zufällig (Deubel & Schneider, 1996). Augenbewegungen beim Lesen und Suchen sind gut untersucht (Rayner, 1998). Tafelgröße, Abstände, Leseordnungen, Takt und die Kennzahl „Streuung zu Mittel“ sind eigene Festlegungen der App. Die Zeit pro Zeichen im eigenen Tempo enthält Lesen, Entscheiden und Tippen, nicht nur den Blickwechsel; wohin du schaust, ob du jedes Zeichen liest und ob du laut liest, wird nicht gemessen (kein Eye-Tracking). Ein Teil der Verbesserung beim Wiederholen ist Gewöhnung an Aufgabe und Gerät: In Studien zu solchen Übungen fiel sie deutlich größer aus, wenn die Prüfung der geübten Aufgabe ähnelte (Guo et al., 2025). Touchscreens messen Reaktionszeiten durchweg etwas zu lang, je nach Gerät unterschiedlich (Pronk et al., 2020; Tablets wurden dort nicht untersucht); darum zählt nur der Vergleich mit dir selbst auf demselben Gerät und bei gleichen Einstellungen. Dass sich das Üben auf Lesen, Sport oder Alltag überträgt, ist nicht belegt. Für genau diese Übung gibt es keine Studie.',
      improved:
        'Die Tafel passt sich der Bühne an: Reicht der Platz nicht, wird sie verkleinert (mit Hinweis unten und Angabe im Ergebnis). Größen und Abstände in Zentimetern (nach Kalibrierung des Bildschirms). Die Marke ist ein heller Kasten mit dunkler Schrift (Form und Kontrast, nicht nur Farbe), gelesene Zeichen werden blass; die Marke wechselt weich, es gibt kein Blinken im Takt, höchstens 140 Schläge pro Minute. Im eigenen Tempo zählt jeder Tipp auf der Bühne, ein Doppeltipp (unter 0,34 s) wird ignoriert. Im Takt zählt die Zeit vom ersten markierten bis zum letzten Zeichen, nicht die Wartezeit vor dem ersten Schlag. „Streuung zu Mittel“ gibt es erst ab zwei Zeitabständen. Der Ton folgt dem Ton der App. Jeder Durchlauf merkt sich seine Einstellungen: Verlauf, Bestwert und „Letztes Mal“ vergleichen nur Läufe mit gleichen Einstellungen (der Ton zählt nicht dazu). Im Takt steht die Gesamtzeit fest und sagt nichts über dich. Keine Noten, keine Normwerte, keine Ranglisten.',
    },
    it: {
      trains: 'Leggere una tavola di gruppi di segni passo dopo passo: un indicatore mostra il segno successivo, al tuo ritmo o a tempo. Dimensione della tavola, segni, distanze e ordine di lettura li scegli tu.',
      daily: 'Ovunque si colgano in sequenza molti segni ravvicinati, per esempio colonne di numeri o tabelle. Che l’esercizio aiuti non è dimostrato.',
      research:
        'Tavole di lettere di questo tipo (Hart-Chart) vengono usate nella terapia visiva. Sul loro effetto sui cambi di sguardo non abbiamo trovato alcuno studio nella banca dati PubMed (ricerca del 02.10.2026); le indicazioni di efficacia dei fornitori sono indicazioni della pratica senza prove. Dalla ricerca si sa: i segni molto ravvicinati sono più difficili da riconoscere dei segni isolati (affollamento, in inglese “crowding”). La distanza minima di cui i segni hanno bisogno per non confondersi cresce con la distanza dal punto di fissazione (legge di Bouma) e limita la velocità di lettura e di ricerca (Pelli & Tillman, 2008); l’affollamento è un limite del riconoscimento in quasi tutto il campo visivo (Whitney & Levi, 2011). Con distanza stretta (0,1 invece di 1,0 altezza della lettera) in uno studio con stringhe di cinque lettere si sono verificate più confusioni casuali (Liu & Arditi, 2001) – per questo puoi regolare la distanza tra i segni. Prima di un salto dello sguardo l’attenzione si sposta sul segno bersaglio: lì il riconoscimento riesce meglio, sui segni vicini solo più o meno a caso (Deubel & Schneider, 1996). I movimenti oculari nella lettura e nella ricerca sono ben studiati (Rayner, 1998). Dimensione della tavola, distanze, ordini di lettura, ritmo e l’indicatore “variazione rispetto alla media” sono scelte proprie dell’app. Il tempo per segno al tuo ritmo comprende leggere, decidere e toccare, non solo il cambio di sguardo; dove guardi, se leggi ogni segno e se leggi a voce alta non viene misurato (nessun eye-tracking). Una parte del miglioramento nelle ripetizioni è abitudine al compito e al dispositivo: negli studi su esercizi di questo tipo era nettamente maggiore quando la verifica somigliava al compito allenato (Guo et al., 2025). I touchscreen misurano i tempi di reazione sistematicamente un po’ in eccesso, in modo diverso a seconda del dispositivo (Pronk et al., 2020; i tablet non erano stati studiati); per questo conta solo il confronto con te stesso sullo stesso dispositivo e con le stesse impostazioni. Non è dimostrato che l’allenamento si trasferisca alla lettura, allo sport o alla vita quotidiana. Per questo esercizio non esiste uno studio.',
      improved:
        'La tavola si adatta all’area di gioco: se lo spazio non basta, viene ridotta (con avviso in basso e indicazione nel risultato). Dimensioni e distanze in centimetri (dopo la calibrazione dello schermo). L’indicatore è un riquadro chiaro con scrittura scura (forma e contrasto, non solo colore), i segni letti diventano chiari; l’indicatore cambia con dissolvenza morbida, nessun lampeggio a ritmo, al massimo 140 battiti al minuto. Al tuo ritmo conta ogni tocco sull’area di gioco, un doppio tocco (sotto 0,34 s) viene ignorato. A tempo conta il tempo dal primo segno indicato alla fine dell’ultimo, non l’attesa prima del primo battito. La “variazione rispetto alla media” c’è solo da due intervalli di tempo in poi. Il suono segue il suono dell’app. Ogni giro ricorda le sue impostazioni: andamento, record e “ultima volta” confrontano solo giri con le stesse impostazioni (il suono non conta). A tempo il tempo totale è fissato e non dice nulla su di te. Niente voti, niente valori di riferimento, niente classifiche.',
    },
  },
  sources: [
    src('Pelli & Tillman (2008). The uncrowded window of object recognition. Nature Neuroscience', 'https://doi.org/10.1038/nn.2187'),
    src('Whitney & Levi (2011). Visual crowding: A fundamental limit on conscious perception and object recognition. Trends in Cognitive Sciences', 'https://doi.org/10.1016/j.tics.2011.02.005'),
    src('Liu & Arditi (2001). How crowding affects letter confusion. Optometry and Vision Science', 'https://doi.org/10.1097/00006324-200101010-00014'),
    src('Deubel & Schneider (1996). Saccade target selection and object recognition: Evidence for a common attentional mechanism. Vision Research', 'https://doi.org/10.1016/0042-6989(95)00294-4'),
    src('Rayner (1998). Eye movements in reading and information processing: 20 years of research. Psychological Bulletin', 'https://doi.org/10.1037/0033-2909.124.3.372'),
    src('Pronk, Wiers, Molenkamp & Murre (2020). Mental chronometry in the pocket? Timing accuracy of web applications on touchscreen and keyboard devices. Behavior Research Methods', 'https://doi.org/10.3758/s13428-019-01321-2'),
    src('Guo, Yuan, Yang & Qiu (2025). Does the "learning effect" caused by digital devices exaggerate sports visual training outcomes? A systematic review and meta-analysis. Frontiers in Physiology', 'https://doi.org/10.3389/fphys.2025.1664572'),
  ],
};
