// Quellen: jede Angabe einzeln per Crossref (Metadaten) und über PubMed (Abstract) geprüft (02.10.2026); die Aussagen im
// Text halten sich an das, was im Abstract steht. Alle Quellen sind gesucht und geprüft (teils aus
// docs/uebungskatalog/literatur/lit-W13, dort ebenfalls per Crossref/Abstract geprüft, hier erneut abgefragt):
// - Deubel & Schneider (1996): Aufmerksamkeit und Blicksprung-Ziel sind gekoppelt (Abstract).
// - Baloh et al. (1975): Sprungdauer wächst linear mit der Sprungweite, im Mittel 2,7 ms je Grad, 25 Gesunde (Abstract).
// - Neggers & Bekkering (2000): Blick bleibt am Ziel einer Zeigebewegung verankert, Blicksprünge während des Zeigens im
//   Mittel 155 ms verzögert (Abstract; Laborversuch mit Zeigebewegungen, nicht Tippen auf dem Tablet).
// - Repp (2005): Übersicht zum Mitklopfen zu einem Takt; es wird nur die Tatsache der Forschungslage genannt, keine Zahl
//   (der Abstract nennt Themen, keine Ergebnisse).
// - Karantinos et al. (2025): Wiederholen von Blicksprung-Aufgaben verbesserte Genauigkeit, Tempo, Stabilität (30 Personen,
//   Eye-Tracking, andere Aufgaben) (Abstract).
// - Pronk et al. (2020), Guo et al. (2025): Grenzen der Messung am Touchgerät bzw. Gewöhnungseffekt (Abstract).
// Nicht aufgenommen: Aussagen ohne Quelle („erst in der Ruhe dazwischen wird Information aufgenommen“ – nicht
// geprüft; „stellt sicher, dass der Blick tatsächlich dort angekommen ist“ – die App kann den Blick nicht messen; „schult
// präzise Blicksprünge“ – Wirkversprechen). Das Üben zu einem Metronom, auch mit zusätzlicher Sprech- oder Denkaufgabe, ist
// als Praxisangabe der funktionellen Optometrie beschrieben und nicht belegt (nur so genannt). Für genau diese Übung (Takt, springendes Zeichen, Antippen) wurde keine Studie
// gefunden. Nicht bestätigt werden konnte: Volltext der Studien (nur Abstracts gelesen).
import type { ScienceEntry } from '../../content/science';

const src = (label: string, url: string) => ({ label, url });

export const science: ScienceEntry = {
  id: 'labor-takt-sakkaden',
  evidence: 'weak',
  texts: {
    de: {
      trains: 'Im Takt eines Metronoms ein springendes Zeichen ansehen und laut lesen, auf Wunsch zusätzlich im Takt antippen. Takt, Anordnung, Zeichenart und Größe stellst du selbst ein.',
      daily: 'Überall, wo der Blick im Rhythmus zwischen weit auseinanderliegenden Stellen wechselt, zum Beispiel beim Abgleichen zweier Listen. Ob die Übung dabei hilft, ist nicht belegt.',
      research:
        'Sakkaden sind die schnellen Sprünge der Augen von einem Punkt zum nächsten. Vor dem Sprung wandert die Aufmerksamkeit zum Ziel: Das Erkennen gelingt dort am besten, an Nachbarobjekten nur noch etwa zufällig (Deubel & Schneider, 1996). Je weiter der Sprung, desto länger dauert er – in einer Studie mit 25 Gesunden im Mittel 2,7 ms mehr je Grad (Baloh et al., 1975); darum zeigt die App den größten Sprung auch als Sehwinkel. Beim Zeigen auf ein Ziel bleibt der Blick offenbar am Ziel verankert: Blicksprünge zu einem neuen Ziel während einer Zeigebewegung waren im Mittel 155 ms verzögert (Neggers & Bekkering, 2000, Laborversuch mit Zeigebewegungen). Wir vermuten daher, dass „Berühren im Takt“ schwerer ist als nur Lesen; geprüft ist das für diese Übung nicht. Das Mitklopfen zu einem Ton ist als Aufgabe gut untersucht (Repp, 2005). In der Praxis der funktionellen Optometrie wird das Üben zu einem Metronom, auch zusammen mit einer Sprech- oder Denkaufgabe, als Erfahrungswissen beschrieben; belegt ist eine Wirkung nicht. Beim Wiederholen von Blicksprung-Aufgaben wurden gesunde Erwachsene genauer, schneller und gleichmäßiger, unabhängig von der Tageszeit (Karantinos et al., 2025; gemessen mit Eye-Tracking an anderen Aufgaben, nicht an dieser). Ein Teil der Verbesserung in der geübten Aufgabe ist Gewöhnung an Aufgabe und Gerät: In Studien zu solchen Übungen fiel sie deutlich größer aus, wenn die Prüfung der geübten Aufgabe ähnelte (Guo et al., 2025). Touchscreens messen Reaktionszeiten durchweg etwas zu lang, je nach Gerät unterschiedlich (Pronk et al., 2020; Tablets wurden dort nicht untersucht). Messwerte am Menschen streuen von Durchgang zu Durchgang, am lebenden Auge stärker als an Prüfkörpern; deshalb sind Mehrfachmessung und Mittelung üblich (Mountford et al., 2004, S. 43–44, am Beispiel der Hornhautvermessung), und die Übung zeigt Mittel und Streuung statt eines Einzelwerts. Darum zählt nur der Vergleich mit dir selbst auf demselben Gerät und mit denselben Einstellungen. Takt, Anordnungen, Zeichenarten und Größen sind eigene Festlegungen der App. Wohin du schaust und ob du laut liest, wird nicht gemessen (kein Eye-Tracking); mit Berühren wird nur die Antwort der Hand erfasst. Dass sich das Üben auf Lesen, Sport oder Alltag überträgt, ist nicht belegt. Für genau diese Übung gibt es keine Studie.',
      improved:
        'Jeder Schlag des Metronoms zeigt genau ein Zeichen an einem Punkt des gewählten Musters; die Schläge liegen exakt im Takt, auch wenn ein Bild verspätet gezeichnet wird. Weil Zeichen und Ton erst im nächsten Bild erscheinen, ist der Takt bildgenau, aber nicht millisekundengenau, und das sagt die App auch so. Die Zeichen werden weich ein- und ausgeblendet und blinken nicht im Takt; der Takt ist auf höchstens 140 Schläge pro Minute begrenzt (etwa 2,3 Wechsel pro Sekunde). Größen werden in Zentimetern angegeben (nach Kalibrierung des Bildschirms) und auf kleinen Bildschirmen so verkleinert, dass sich die Zeichen nicht überlappen; der größte Sprung des Musters wird zusätzlich als Sehwinkel ausgewiesen. Beim optionalen Berühren hat die Trefferfläche eine Mindestgröße für Touch-Eingaben, und ein zweiter Tipp direkt nach einem Treffer zählt nicht als Fehltipp. Jeder Durchlauf merkt sich seine Einstellungen, und Verlauf, Bestwert und „Letztes Mal“ vergleichen nur Läufe mit gleichen Einstellungen (der Ton zählt nicht dazu); ohne Berühren steht die Zahl der gezeigten Zeichen durch Dauer und Takt fest und sagt nichts über dich, mit Berühren ist der Hauptwert die Trefferquote – ohne Noten, Normwerte und Ranglisten.',
    },
    it: {
      trains: 'Guardare e leggere a voce alta un segno che salta a ritmo di metronomo, se vuoi anche toccarlo a ritmo. Ritmo, disposizione, tipo di segni e dimensione li scegli tu.',
      daily: 'Ovunque lo sguardo cambi a ritmo tra punti ben distanti, per esempio confrontando due elenchi. Che l’esercizio aiuti non è dimostrato.',
      research:
        'Le saccadi sono i rapidi salti degli occhi da un punto al successivo. Prima del salto l’attenzione si sposta verso il bersaglio: il riconoscimento è lì migliore, sugli oggetti vicini solo più o meno casuale (Deubel & Schneider, 1996). Più il salto è ampio, più dura – in uno studio con 25 persone sane in media 2,7 ms in più per grado (Baloh et al., 1975); per questo l’app mostra il salto più grande anche come angolo visivo. Quando si indica un bersaglio lo sguardo sembra restare ancorato al bersaglio: i salti verso un nuovo bersaglio durante un movimento di puntamento erano in media ritardati di 155 ms (Neggers & Bekkering, 2000, esperimento di laboratorio con movimenti di puntamento). Supponiamo quindi che “Tocco a ritmo” sia più difficile del solo leggere; per questo esercizio non è verificato. Battere il ritmo su un suono è un compito ben studiato (Repp, 2005). Nella pratica dell’optometria funzionale l’esercizio con un metronomo, anche insieme a un compito di lettura ad alta voce o di calcolo mentale, è descritto come sapere empirico; un effetto non è dimostrato. Ripetendo compiti di saccadi, adulti sani sono diventati più precisi, più rapidi e più regolari, indipendentemente dall’ora del giorno (Karantinos et al., 2025; misurato con eye-tracking su altri compiti, non su questo). Una parte del miglioramento nel compito allenato è abitudine al compito e al dispositivo: negli studi su esercizi di questo tipo era nettamente maggiore quando la verifica somigliava al compito allenato (Guo et al., 2025). I touchscreen misurano i tempi di reazione sistematicamente un po’ in eccesso, in modo diverso a seconda del dispositivo (Pronk et al., 2020; i tablet non erano stati studiati). I valori misurati sulle persone variano da una prova all’altra, sull’occhio vivente più che su corpi di prova; per questo sono d’uso la misurazione ripetuta e la media (Mountford et al., 2004, pag. 43–44, a proposito della misurazione della cornea), e l’esercizio mostra media e variazione invece di un singolo valore. Per questo conta solo il confronto con te stesso sullo stesso dispositivo e con le stesse impostazioni. Ritmo, disposizioni, tipi di segni e dimensioni sono scelte proprie dell’app. Dove guardi e se leggi a voce alta non viene misurato (nessun eye-tracking); con il tocco viene rilevata solo la risposta della mano. Non è dimostrato che l’allenamento si trasferisca alla lettura, allo sport o alla vita quotidiana. Per questo esercizio non esiste uno studio.',
      improved:
        'Ogni battito del metronomo mostra esattamente un segno in un punto della disposizione scelta; i battiti sono esattamente a ritmo, anche quando un’immagine viene disegnata in ritardo. Poiché segno e suono compaiono solo nell’immagine successiva, il ritmo è preciso al fotogramma ma non al millisecondo, e l’app lo dice apertamente. I segni compaiono e spariscono con dissolvenza morbida e non lampeggiano a ritmo; il ritmo è limitato a un massimo di 140 battiti al minuto (circa 2,3 cambi al secondo). Le dimensioni sono espresse in centimetri (dopo la calibrazione dello schermo) e sugli schermi piccoli ridotte in modo che i segni non si sovrappongano; il salto più grande della disposizione viene indicato anche come angolo visivo. Con il tocco facoltativo l’area di tocco ha una dimensione minima per l’input touch, e un secondo tocco subito dopo un colpo a segno non conta come tocco a vuoto. Ogni giro ricorda le sue impostazioni, e andamento, record e “ultima volta” confrontano solo giri con le stesse impostazioni (il suono non conta); senza tocco il numero di segni mostrati è fissato da durata e ritmo e non dice nulla su di te, con il tocco il valore principale è la percentuale di colpi – senza voti, valori di riferimento e classifiche.',
    },
  },
  sources: [
    src('Deubel & Schneider (1996). Saccade target selection and object recognition: Evidence for a common attentional mechanism. Vision Research', 'https://doi.org/10.1016/0042-6989(95)00294-4'),
    src('Baloh, Sills, Kumley & Honrubia (1975). Quantitative measurement of saccade amplitude, duration, and velocity. Neurology', 'https://doi.org/10.1212/WNL.25.11.1065'),
    src('Neggers & Bekkering (2000). Ocular gaze is anchored to the target of an ongoing pointing movement. Journal of Neurophysiology', 'https://doi.org/10.1152/jn.2000.83.2.639'),
    src('Repp (2005). Sensorimotor synchronization: A review of the tapping literature. Psychonomic Bulletin & Review', 'https://doi.org/10.3758/BF03206433'),
    src('Karantinos, Kotsiou, Drouza, Mantas, Anderson, Klein & Smyrnis (2025). Diurnal variation and practice effects in saccade task performance. Experimental Brain Research', 'https://doi.org/10.1007/s00221-025-07131-7'),
    src('Pronk, Wiers, Molenkamp & Murre (2020). Mental chronometry in the pocket? Timing accuracy of web applications on touchscreen and keyboard devices. Behavior Research Methods', 'https://doi.org/10.3758/s13428-019-01321-2'),
    src('Guo, Yuan, Yang & Qiu (2025). Does the "learning effect" caused by digital devices exaggerate sports visual training outcomes? A systematic review and meta-analysis. Frontiers in Physiology', 'https://doi.org/10.3389/fphys.2025.1664572'),
    src('Mountford, Ruston & Dave (2004). Orthokeratology: Principles and Practice, S. 43–44 (Wiederholbarkeit von Messungen). Butterworth-Heinemann', 'https://openlibrary.org/isbn/9780750640077'),
  ],
};
